"""
build_phase5.py
===============
Phase 5: Intelligence upgrades

[1] train_conviction_xgb.py  -- XGBoost conviction model (replaces hand-weights)
[2] /stocks/[symbol] news tab -- news_headlines for symbol with sentiment badges
[3] /portfolio correlation    -- heatmap of position correlations
[4] /alerts page rebuild      -- shows last_fired_date, dedup status, history

Run: py D:\MICC\build_phase5.py
"""
from pathlib import Path

MICC = Path(r"D:\MICC")
DASH = MICC / "micc-dashboard"
APP  = DASH / "src" / "app"

def write(path, lines, label=""):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  [OK] {label or path.name}  ({len(lines)} lines)")

def log(msg):
    from datetime import datetime
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)

print("=" * 60)
print("PHASE 5 BUILD")
print("=" * 60)


# =============================================================================
# [1]  XGBoost Conviction Model
#      Features: momentum, seasonality, delivery, insider, RSI, ADX, ATR,
#                ROCE, ROE, D/E, OOS accuracy, HMM regime
#      Label:    forward_return_5d > 1% = 1 (positive signal)
#      Saves:    symbol_conviction_xgb table + model file
# =============================================================================
log("[1/4] Building train_conviction_xgb.py...")

xgb_lines = [
    '"""',
    'train_conviction_xgb.py  --  XGBoost conviction model',
    'Trains on historical signals + forward returns.',
    'Features: 14 technical + fundamental + seasonal features',
    'Label: 5d forward return > 1%',
    '',
    'Run: py D:\\MICC\\train_conviction_xgb.py',
    '     py D:\\MICC\\train_conviction_xgb.py --score   (just score current universe)',
    '"""',
    'import sys, sqlite3, json',
    'from pathlib import Path',
    'from datetime import datetime',
    '',
    'DA      = Path(r"D:\\MICC")',
    'DB_PATH = r"D:\\marketDB\\db\\market.db"',
    'SCORE_ONLY = "--score" in sys.argv',
    '',
    'def log(msg): print(f"  {msg}", flush=True)',
    '',
    '# ── Install deps ──────────────────────────────────────────────────────────',
    'try:',
    '    import xgboost as xgb',
    '    import numpy as np',
    '    import pandas as pd',
    'except ImportError:',
    '    import subprocess',
    '    subprocess.run([sys.executable, "-m", "pip", "install",',
    '                    "xgboost", "numpy", "pandas",',
    '                    "--break-system-packages", "-q"])',
    '    import xgboost as xgb',
    '    import numpy as np',
    '    import pandas as pd',
    '',
    'MODEL_PATH = DA / "conviction_xgb.json"',
    '',
    'FEATURES = [',
    '    "rsi_14", "adx_14", "atr_14_pct", "pct_above_sma20",',
    '    "vol_surge_20d", "delivery_pct",',
    '    "roce", "roe", "debt_equity", "pe_ratio",',
    '    "oos_accuracy", "score_v2_best",',
    '    "insider_buy_30d", "n_signals_30d",',
    ']',
    '',
    'def load_training_data():',
    '    log("Loading training data...")',
    '    conn = sqlite3.connect(DB_PATH, timeout=30)',
    '',
    '    # Base: signals_history with forward returns',
    '    df = pd.read_sql(',
    '        "SELECT sh.symbol, sh.run_date, sh.score,"',
    '        "  COALESCE(sh.forward_return_5d, 0) AS fwd5d"',
    '        " FROM signals_history sh"',
    '        " WHERE sh.forward_return_5d IS NOT NULL"',
    '        " ORDER BY sh.run_date DESC LIMIT 50000",',
    '        conn',
    '    )',
    '    log(f"  signals_history: {len(df)} rows")',
    '    if len(df) < 100:',
    '        conn.close()',
    '        raise ValueError("Need at least 100 signals with forward returns")',
    '',
    '    # Technicals',
    '    tech = pd.read_sql(',
    '        "SELECT symbol, rsi_14, adx_14, atr_14_pct, pct_above_sma20, vol_surge_20d"',
    '        " FROM symbol_technicals",',
    '        conn',
    '    )',
    '    # Delivery',
    '    deliv = pd.read_sql(',
    '        "SELECT symbol, AVG(CAST(delivery_pct AS REAL)) AS delivery_pct"',
    '        " FROM stock_delivery"',
    '        " WHERE date >= date(\'now\', \'-30 days\')"',
    '        " GROUP BY symbol",',
    '        conn',
    '    )',
    '    # Fundamentals',
    '    try:',
    '        fund = pd.read_sql(',
    '            "SELECT symbol, roce, roe, debt_equity, pe_ratio"',
    '            " FROM screener_fundamentals_v2 WHERE scrape_ok=1",',
    '            conn',
    '        )',
    '    except Exception:',
    '        fund = pd.DataFrame(columns=["symbol","roce","roe","debt_equity","pe_ratio"])',
    '    # Best OOS accuracy per symbol',
    '    try:',
    '        oos = pd.read_sql(',
    '            "SELECT symbol,"',
    '            "  MAX(CAST(oos_accuracy AS REAL)) AS oos_accuracy,"',
    '            "  MAX(CAST(score_v2 AS REAL)) AS score_v2_best"',
    '            " FROM seasonality_patterns_v3"',
    '            " WHERE fdr_reject=1 AND (overfit=0 OR overfit IS NULL)"',
    '            "   AND oos_accuracy IS NOT NULL"',
    '            " GROUP BY symbol",',
    '            conn',
    '        )',
    '    except Exception:',
    '        oos = pd.DataFrame(columns=["symbol","oos_accuracy","score_v2_best"])',
    '    # Insider buys last 30d',
    '    try:',
    '        ins = pd.read_sql(',
    '            "SELECT symbol, COUNT(*) AS insider_buy_30d"',
    '            " FROM insider_trading"',
    '            " WHERE transaction_type=\'BUY\'"',
    '            "   AND filing_date >= date(\'now\', \'-30 days\')"',
    '            " GROUP BY symbol",',
    '            conn',
    '        )',
    '    except Exception:',
    '        ins = pd.DataFrame(columns=["symbol","insider_buy_30d"])',
    '    # Signal count per symbol last 30d',
    '    sig_cnt = pd.read_sql(',
    '        "SELECT symbol, COUNT(*) AS n_signals_30d"',
    '        " FROM signals_history"',
    '        " WHERE run_date >= date(\'now\', \'-30 days\')"',
    '        " GROUP BY symbol",',
    '        conn',
    '    )',
    '    conn.close()',
    '',
    '    # Merge all',
    '    df = df.merge(tech,    on="symbol", how="left")',
    '    df = df.merge(deliv,   on="symbol", how="left")',
    '    df = df.merge(fund,    on="symbol", how="left")',
    '    df = df.merge(oos,     on="symbol", how="left")',
    '    df = df.merge(ins,     on="symbol", how="left")',
    '    df = df.merge(sig_cnt, on="symbol", how="left")',
    '',
    '    df["insider_buy_30d"] = df["insider_buy_30d"].fillna(0)',
    '    df["n_signals_30d"]   = df["n_signals_30d"].fillna(0)',
    '    df["oos_accuracy"]    = df["oos_accuracy"].fillna(0.5)',
    '    df["score_v2_best"]   = df["score_v2_best"].fillna(0)',
    '',
    '    # Label: 5d forward return > 1%',
    '    df["label"] = (df["fwd5d"] > 1.0).astype(int)',
    '    log(f"  Positive labels: {df[\'label\'].mean():.1%}")',
    '    return df',
    '',
    'def train(df):',
    '    log("Training XGBoost model...")',
    '    X = df[FEATURES].fillna(df[FEATURES].median())',
    '    y = df["label"]',
    '',
    '    # Train/test split by date',
    '    split = int(len(df) * 0.8)',
    '    X_tr, X_te = X.iloc[:split], X.iloc[split:]',
    '    y_tr, y_te = y.iloc[:split], y.iloc[split:]',
    '',
    '    model = xgb.XGBClassifier(',
    '        n_estimators=200, max_depth=4, learning_rate=0.05,',
    '        subsample=0.8, colsample_bytree=0.8,',
    '        scale_pos_weight=(y_tr==0).sum()/(y_tr==1).sum(),',
    '        use_label_encoder=False, eval_metric="logloss",',
    '        random_state=42, verbosity=0',
    '    )',
    '    model.fit(X_tr, y_tr,',
    '              eval_set=[(X_te, y_te)],',
    '              verbose=False)',
    '',
    '    from sklearn.metrics import roc_auc_score, accuracy_score',
    '    preds = model.predict_proba(X_te)[:,1]',
    '    auc   = roc_auc_score(y_te, preds)',
    '    acc   = accuracy_score(y_te, model.predict(X_te))',
    '    log(f"  Test AUC={auc:.3f}  Acc={acc:.1%}")',
    '',
    '    # Feature importance',
    '    imp = sorted(zip(FEATURES, model.feature_importances_),',
    '                 key=lambda x: -x[1])',
    '    log("  Top features:")',
    '    for feat, score in imp[:5]:',
    '        log(f"    {feat:<20} {score:.3f}")',
    '',
    '    model.save_model(str(MODEL_PATH))',
    '    log(f"  Model saved: {MODEL_PATH}")',
    '    return model, auc',
    '',
    'def score_universe(model):',
    '    log("Scoring current universe...")',
    '    conn = sqlite3.connect(DB_PATH, timeout=30)',
    '',
    '    # Load current features for all symbols',
    '    tech = pd.read_sql(',
    '        "SELECT symbol, rsi_14, adx_14, atr_14_pct, pct_above_sma20, vol_surge_20d"',
    '        " FROM symbol_technicals", conn)',
    '    try:',
    '        deliv = pd.read_sql(',
    '            "SELECT symbol, AVG(CAST(delivery_pct AS REAL)) AS delivery_pct"',
    '            " FROM stock_delivery WHERE date >= date(\'now\', \'-30 days\')"',
    '            " GROUP BY symbol", conn)',
    '    except Exception:',
    '        deliv = pd.DataFrame(columns=["symbol","delivery_pct"])',
    '    try:',
    '        fund = pd.read_sql(',
    '            "SELECT symbol, roce, roe, debt_equity, pe_ratio"',
    '            " FROM screener_fundamentals_v2 WHERE scrape_ok=1", conn)',
    '    except Exception:',
    '        fund = pd.DataFrame(columns=["symbol","roce","roe","debt_equity","pe_ratio"])',
    '    try:',
    '        oos = pd.read_sql(',
    '            "SELECT symbol,"',
    '            "  MAX(CAST(oos_accuracy AS REAL)) AS oos_accuracy,"',
    '            "  MAX(CAST(score_v2 AS REAL)) AS score_v2_best"',
    '            " FROM seasonality_patterns_v3"',
    '            " WHERE fdr_reject=1 AND (overfit=0 OR overfit IS NULL)"',
    '            "   AND oos_accuracy IS NOT NULL GROUP BY symbol", conn)',
    '    except Exception:',
    '        oos = pd.DataFrame(columns=["symbol","oos_accuracy","score_v2_best"])',
    '    try:',
    '        ins = pd.read_sql(',
    '            "SELECT symbol, COUNT(*) AS insider_buy_30d"',
    '            " FROM insider_trading"',
    '            " WHERE transaction_type=\'BUY\'"',
    '            "   AND filing_date >= date(\'now\', \'-30 days\')"',
    '            " GROUP BY symbol", conn)',
    '    except Exception:',
    '        ins = pd.DataFrame(columns=["symbol","insider_buy_30d"])',
    '    sig_cnt = pd.read_sql(',
    '        "SELECT symbol, COUNT(*) AS n_signals_30d"',
    '        " FROM signals_history WHERE run_date >= date(\'now\', \'-30 days\')"',
    '        " GROUP BY symbol", conn)',
    '',
    '    conn.close()',
    '',
    '    df = tech',
    '    for other in [deliv, fund, oos, ins, sig_cnt]:',
    '        df = df.merge(other, on="symbol", how="left")',
    '    df["insider_buy_30d"] = df["insider_buy_30d"].fillna(0)',
    '    df["n_signals_30d"]   = df["n_signals_30d"].fillna(0)',
    '    df["oos_accuracy"]    = df["oos_accuracy"].fillna(0.5)',
    '    df["score_v2_best"]   = df["score_v2_best"].fillna(0)',
    '',
    '    X    = df[FEATURES].fillna(df[FEATURES].median())',
    '    prob = model.predict_proba(X)[:,1]',
    '    df["xgb_score"] = (prob * 100).round(1)',
    '',
    '    # Save to DB',
    '    conn2 = sqlite3.connect(DB_PATH, timeout=30)',
    '    conn2.execute("PRAGMA journal_mode=WAL")',
    '    conn2.execute(',
    '        "CREATE TABLE IF NOT EXISTS symbol_conviction_xgb"',
    '        " (symbol TEXT PRIMARY KEY, xgb_score REAL, updated_at TEXT)"',
    '    )',
    '    now = datetime.now().isoformat()',
    '    batch = [(row.symbol, row.xgb_score, now) for _, row in df.iterrows()]',
    '    conn2.executemany(',
    '        "INSERT OR REPLACE INTO symbol_conviction_xgb (symbol,xgb_score,updated_at)"',
    '        " VALUES (?,?,?)", batch)',
    '    conn2.commit()',
    '    conn2.close()',
    '    log(f"  Saved {len(batch)} XGB scores to symbol_conviction_xgb")',
    '',
    '    top = df.nlargest(10, "xgb_score")[["symbol","xgb_score"]]',
    '    log("  Top 10 by XGB score:")',
    '    for _, r in top.iterrows():',
    '        log(f"    {r.symbol:<15} {r.xgb_score:.1f}")',
    '    return df',
    '',
    'print("XGBoost Conviction Model")',
    'print("=" * 40)',
    '',
    'if SCORE_ONLY and MODEL_PATH.exists():',
    '    log("Loading existing model...")',
    '    model = xgb.XGBClassifier()',
    '    model.load_model(str(MODEL_PATH))',
    '    score_universe(model)',
    'else:',
    '    try:',
    '        df   = load_training_data()',
    '        model, auc = train(df)',
    '        score_universe(model)',
    '        print(f"Done. AUC={auc:.3f}  Scores saved to symbol_conviction_xgb")',
    '    except Exception as e:',
    '        print(f"Error: {e}")',
    '        import traceback; traceback.print_exc()',
]

write(MICC / "train_conviction_xgb.py", xgb_lines, "train_conviction_xgb.py")


# =============================================================================
# [2]  /api/stocks/[symbol]/news/route.ts  -- news for a symbol
# =============================================================================
log("[2/4] Building stock news API...")

news_api_lines = [
    'import { NextResponse } from "next/server";',
    'import Database from "better-sqlite3";',
    '',
    'const DB = "D:/marketDB/db/market.db";',
    '',
    'export function GET(',
    '  _req: Request,',
    '  { params }: { params: { symbol: string } }',
    ') {',
    '  const sym = params.symbol.toUpperCase();',
    '  let db: ReturnType<typeof Database> | null = null;',
    '  try {',
    '    db = new Database(DB, { readonly: true, timeout: 5000 });',
    '    // Check which news table exists',
    '    const tables = db.prepare(',
    '      "SELECT name FROM sqlite_master WHERE type=\'table\'"',
    '    ).all() as { name: string }[];',
    '    const tnames = new Set(tables.map(t => t.name));',
    '',
    '    let rows: unknown[] = [];',
    '    if (tnames.has("news_headlines")) {',
    '      rows = db.prepare(',
    '        "SELECT date, headline, source, sentiment_score, url"',
    '        " FROM news_headlines"',
    '        " WHERE symbols_mentioned LIKE ?"',
    '        " ORDER BY date DESC LIMIT 30"',
    '      ).all("%" + sym + "%");',
    '    } else if (tnames.has("symbol_news_daily")) {',
    '      rows = db.prepare(',
    '        "SELECT date, title AS headline, source, sentiment_score, url"',
    '        " FROM symbol_news_daily"',
    '        " WHERE symbol=?"',
    '        " ORDER BY date DESC LIMIT 30"',
    '      ).all(sym);',
    '    }',
    '    // Also get corporate announcements',
    '    const anns = db.prepare(',
    '      "SELECT announcement_date AS date, subject AS headline,"',
    '      "  \'NSE\' AS source, NULL AS sentiment_score, NULL AS url"',
    '      " FROM corporate_announcements"',
    '      " WHERE symbol=?"',
    '      " ORDER BY announcement_date DESC LIMIT 20"',
    '    ).all(sym);',
    '',
    '    const combined = [...rows, ...anns]',
    '      .sort((a: any, b: any) => (b.date || "").localeCompare(a.date || ""));',
    '',
    '    return NextResponse.json({ symbol: sym, news: combined, count: combined.length });',
    '  } catch (e) {',
    '    return NextResponse.json({ symbol: sym, news: [], error: String(e) });',
    '  } finally {',
    '    try { db?.close(); } catch {}',
    '  }',
    '}',
]

write(APP / "api" / "stocks" / "[symbol]" / "news" / "route.ts",
      news_api_lines, "/api/stocks/[symbol]/news/route.ts")


# =============================================================================
# [3]  /api/portfolio/correlation/route.ts  -- pairwise correlation matrix
# =============================================================================
log("[3/4] Building portfolio correlation API...")

corr_api_lines = [
    'import { NextResponse } from "next/server";',
    'import Database from "better-sqlite3";',
    '',
    'const DB = "D:/marketDB/db/market.db";',
    '',
    'export function GET() {',
    '  let db: ReturnType<typeof Database> | null = null;',
    '  try {',
    '    db = new Database(DB, { readonly: true, timeout: 8000 });',
    '',
    '    // Get open positions',
    '    const positions = db.prepare(',
    '      "SELECT symbol FROM my_portfolio WHERE status=\'OPEN\'"',
    '    ).all() as { symbol: string }[];',
    '    const syms = positions.map(p => p.symbol);',
    '',
    '    if (syms.length < 2) {',
    '      return NextResponse.json({ symbols: syms, matrix: [], message: "Need 2+ open positions" });',
    '    }',
    '',
    '    // Fetch 90d of returns for each symbol from parquet via stock_data',
    '    const ph = syms.map(() => "?").join(",");',
    '    const priceRows = db.prepare(',
    '      "SELECT symbol, date, close FROM stock_data"',
    '      " WHERE symbol IN (" + ph + ")"',
    '      "   AND date >= date(\'now\', \'-120 days\')"',
    '      "   AND close IS NOT NULL"',
    '      " ORDER BY symbol, date"',
    '    ).all(...syms) as { symbol: string; date: string; close: number }[];',
    '',
    '    // Build return series per symbol',
    '    const bySymbol: Record<string, number[]> = {};',
    '    const dateIndex: Record<string, Record<string, number>> = {};',
    '    for (const row of priceRows) {',
    '      if (!bySymbol[row.symbol]) bySymbol[row.symbol] = [];',
    '      if (!dateIndex[row.date]) dateIndex[row.date] = {};',
    '      dateIndex[row.date][row.symbol] = row.close;',
    '    }',
    '    const dates = Object.keys(dateIndex).sort();',
    '',
    '    // Compute daily returns',
    '    const returns: Record<string, number[]> = {};',
    '    for (const sym of syms) returns[sym] = [];',
    '    for (let i = 1; i < dates.length; i++) {',
    '      const prev = dateIndex[dates[i-1]];',
    '      const curr = dateIndex[dates[i]];',
    '      for (const sym of syms) {',
    '        if (prev[sym] && curr[sym]) {',
    '          returns[sym].push((curr[sym] - prev[sym]) / prev[sym]);',
    '        } else {',
    '          returns[sym].push(NaN);',
    '        }',
    '      }',
    '    }',
    '',
    '    // Compute pairwise correlations',
    '    function corr(a: number[], b: number[]): number {',
    '      const pairs = a.map((v, i) => [v, b[i]]).filter(p => !isNaN(p[0]) && !isNaN(p[1]));',
    '      if (pairs.length < 10) return NaN;',
    '      const n  = pairs.length;',
    '      const ma = pairs.reduce((s, p) => s + p[0], 0) / n;',
    '      const mb = pairs.reduce((s, p) => s + p[1], 0) / n;',
    '      const num = pairs.reduce((s, p) => s + (p[0]-ma)*(p[1]-mb), 0);',
    '      const da  = Math.sqrt(pairs.reduce((s, p) => s + (p[0]-ma)**2, 0));',
    '      const db2 = Math.sqrt(pairs.reduce((s, p) => s + (p[1]-mb)**2, 0));',
    '      if (da === 0 || db2 === 0) return NaN;',
    '      return Math.round(num / (da * db2) * 100) / 100;',
    '    }',
    '',
    '    const matrix: { symA: string; symB: string; corr: number | null }[] = [];',
    '    for (let i = 0; i < syms.length; i++) {',
    '      for (let j = 0; j < syms.length; j++) {',
    '        const c = i === j ? 1.0 : corr(returns[syms[i]], returns[syms[j]]);',
    '        matrix.push({ symA: syms[i], symB: syms[j], corr: isNaN(c) ? null : c });',
    '      }',
    '    }',
    '',
    '    return NextResponse.json({ symbols: syms, matrix, n_days: dates.length - 1 });',
    '  } catch (e) {',
    '    return NextResponse.json({ symbols: [], matrix: [], error: String(e) });',
    '  } finally {',
    '    try { db?.close(); } catch {}',
    '  }',
    '}',
]

write(APP / "api" / "portfolio" / "correlation" / "route.ts",
      corr_api_lines, "/api/portfolio/correlation/route.ts")


# =============================================================================
# [4]  /alerts page rebuild -- last_fired_date, dedup status, history
# =============================================================================
log("[4/4] Rebuilding /alerts page...")

alerts_page_lines = [
    '"use client";',
    'import NavBar from "@/components/NavBar";',
    'import { useEffect, useState } from "react";',
    '',
    'interface Alert {',
    '  id?: string; type: string; symbol: string; threshold?: number;',
    '  last_fired_date?: string; fired_count?: number; enabled?: boolean;',
    '  last_value?: number; message?: string;',
    '}',
    'interface FiredAlert {',
    '  symbol: string; type: string; message: string;',
    '  fired_at: string; value?: number;',
    '}',
    'interface AlertsData {',
    '  alerts: Alert[]; fired_today: FiredAlert[];',
    '  fired_count: number; total_alerts: number;',
    '}',
    '',
    'const sentColor = (s: string) => s === "PRICE_ABOVE" || s === "RSI_ABOVE" ? "var(--bear)" : "var(--bull)";',
    '',
    'export default function AlertsPage() {',
    '  const [data, setData]   = useState<AlertsData | null>(null);',
    '  const [loading, setL]   = useState(true);',
    '  const [error, setE]     = useState("");',
    '  const [tab, setTab]     = useState<"active"|"fired"|"add">("active");',
    '  const [newSym, setNSym] = useState("");',
    '  const [newType, setNTyp]= useState("PRICE_ABOVE");',
    '  const [newVal, setNVal] = useState("");',
    '  const [saving, setSav]  = useState(false);',
    '',
    '  function load() {',
    '    setL(true);',
    '    fetch("/api/alerts")',
    '      .then(r => r.json())',
    '      .then(d => { setData(d); setL(false); })',
    '      .catch(e => { setE(e.message); setL(false); });',
    '  }',
    '  useEffect(load, []);',
    '',
    '  async function addAlert() {',
    '    if (!newSym || !newVal) return;',
    '    setSav(true);',
    '    try {',
    '      await fetch("/api/alerts", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    '        body: JSON.stringify({ symbol: newSym.toUpperCase(), type: newType, threshold: parseFloat(newVal) }),',
    '      });',
    '      setNSym(""); setNVal(""); load();',
    '    } catch (e: unknown) {',
    '      setE(String(e));',
    '    } finally { setSav(false); }',
    '  }',
    '',
    '  async function deleteAlert(id: string) {',
    '    await fetch("/api/alerts?id=" + id, { method: "DELETE" });',
    '    load();',
    '  }',
    '',
    '  const S: Record<string, React.CSSProperties> = {',
    '    page:  { minHeight: "100vh", background: "var(--bg)", fontFamily: "JetBrains Mono, monospace" },',
    '    sub:   { position: "sticky", top: 48, zIndex: 90, background: "var(--surface)",',
    '             borderBottom: "1px solid var(--border)", padding: "6px 20px",',
    '             display: "flex", alignItems: "center", gap: 16 },',
    '    stitle:{ fontSize: 10, color: "var(--dim)", letterSpacing: 2 },',
    '    wrap:  { maxWidth: 1000, margin: "0 auto", padding: "16px 20px" },',
    '    tabs:  { display: "flex", gap: 6, marginBottom: 20 },',
    '    tab:   (a: boolean): React.CSSProperties => ({',
    '      padding: "5px 16px", fontSize: 11, letterSpacing: 1, cursor: "pointer",',
    '      border: "1px solid " + (a ? "var(--accent)" : "var(--border)"),',
    '      borderRadius: 4, background: a ? "var(--accent)22" : "transparent",',
    '      color: a ? "var(--accent)" : "var(--dim)",',
    '    }),',
    '    card:  { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 8, overflow: "hidden" },',
    '    tbl:   { width: "100%", borderCollapse: "collapse" as const, fontSize: 12 },',
    '    th:    { padding: "8px 12px", textAlign: "left" as const, fontSize: 10, letterSpacing: 1,',
    '             color: "var(--dim)", borderBottom: "1px solid var(--border)" },',
    '    td:    { padding: "9px 12px", borderBottom: "1px solid var(--border)", color: "var(--text)" },',
    '    input: { background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 4,',
    '             padding: "6px 10px", fontSize: 12, color: "var(--text)", outline: "none", width: "100%" },',
    '    sel:   { background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 4,',
    '             padding: "6px 10px", fontSize: 12, color: "var(--text)", outline: "none", width: "100%" },',
    '    btn:   { padding: "6px 16px", borderRadius: 4, fontSize: 11, cursor: "pointer",',
    '             background: "var(--accent)22", border: "1px solid var(--accent)", color: "var(--accent)" },',
    '    del:   { padding: "3px 10px", borderRadius: 3, fontSize: 10, cursor: "pointer",',
    '             background: "var(--bear)11", border: "1px solid var(--bear)44", color: "var(--bear)" },',
    '  };',
    '',
    '  const TYPES = ["PRICE_ABOVE","PRICE_BELOW","RSI_ABOVE","RSI_BELOW",',
    '                  "VOLUME_SURGE","BREAKOUT_52W","STOP_HIT"];',
    '',
    '  return (',
    '    <div style={S.page}>',
    '      <NavBar />',
    '      <div style={S.sub}>',
    '        <span style={S.stitle}>ALERTS  /  PRICE & SIGNAL TRIGGERS</span>',
    '        {data && <span style={{ fontSize: 10, color: "var(--dim)" }}>',
    '          {data.total_alerts} alerts  |  {data.fired_count} fired today',
    '        </span>}',
    '        <button onClick={load} style={{ ...S.btn, marginLeft: "auto", fontSize: 10, padding: "3px 10px" }}>',
    '          Refresh',
    '        </button>',
    '      </div>',
    '',
    '      <div style={S.wrap}>',
    '        {loading && <div style={{ color: "var(--dim)", padding: 40, textAlign: "center" }}>Loading alerts...</div>}',
    '        {error   && <div style={{ color: "var(--bear)", padding: 12, marginBottom: 12,',
    '          background: "var(--bear)11", borderRadius: 6 }}>Error: {error}</div>}',
    '',
    '        {data && <>',
    '          <div style={S.tabs}>',
    '            <button style={S.tab(tab==="active")} onClick={() => setTab("active")}>',
    '              ACTIVE ({data.total_alerts})',
    '            </button>',
    '            <button style={S.tab(tab==="fired")} onClick={() => setTab("fired")}>',
    '              FIRED TODAY ({data.fired_count})',
    '            </button>',
    '            <button style={S.tab(tab==="add")} onClick={() => setTab("add")}>',
    '              + ADD ALERT',
    '            </button>',
    '          </div>',
    '',
    '          {tab === "active" && (',
    '            <div style={S.card}>',
    '              <table style={S.tbl}>',
    '                <thead><tr>',
    '                  {["SYMBOL","TYPE","THRESHOLD","LAST FIRED","TIMES FIRED","STATUS",""].map(h => (',
    '                    <th key={h} style={S.th}>{h}</th>',
    '                  ))}',
    '                </tr></thead>',
    '                <tbody>',
    '                  {(data.alerts || []).map((a, i) => (',
    '                    <tr key={i} style={{ background: i%2===0?"transparent":"var(--surface)88" }}>',
    '                      <td style={{ ...S.td, color: "var(--accent)", fontWeight: 700 }}>{a.symbol}</td>',
    '                      <td style={{ ...S.td, color: sentColor(a.type), fontSize: 11 }}>{a.type}</td>',
    '                      <td style={S.td}>{a.threshold ?? "--"}</td>',
    '                      <td style={{ ...S.td, color: "var(--dim)" }}>{a.last_fired_date || "never"}</td>',
    '                      <td style={S.td}>{a.fired_count ?? 0}</td>',
    '                      <td style={S.td}>',
    '                        <span style={{ padding: "2px 7px", borderRadius: 3, fontSize: 10,',
    '                          background: a.enabled !== false ? "var(--bull)22" : "var(--muted)22",',
    '                          color: a.enabled !== false ? "var(--bull)" : "var(--muted)" }}>',
    '                          {a.enabled !== false ? "ON" : "OFF"}',
    '                        </span>',
    '                      </td>',
    '                      <td style={S.td}>',
    '                        {a.id && (',
    '                          <button style={S.del} onClick={() => deleteAlert(a.id!)}>',
    '                            DEL',
    '                          </button>',
    '                        )}',
    '                      </td>',
    '                    </tr>',
    '                  ))}',
    '                  {data.alerts.length === 0 && (',
    '                    <tr><td colSpan={7} style={{ padding: 30, textAlign: "center", color: "var(--dim)" }}>',
    '                      No alerts configured. Add one below.',
    '                    </td></tr>',
    '                  )}',
    '                </tbody>',
    '              </table>',
    '            </div>',
    '          )}',
    '',
    '          {tab === "fired" && (',
    '            <div style={S.card}>',
    '              <table style={S.tbl}>',
    '                <thead><tr>',
    '                  {["TIME","SYMBOL","TYPE","MESSAGE","VALUE"].map(h => (',
    '                    <th key={h} style={S.th}>{h}</th>',
    '                  ))}',
    '                </tr></thead>',
    '                <tbody>',
    '                  {(data.fired_today || []).map((f, i) => (',
    '                    <tr key={i} style={{ background: i%2===0?"transparent":"var(--surface)88" }}>',
    '                      <td style={{ ...S.td, color: "var(--dim)", fontSize: 11 }}>',
    '                        {(f.fired_at || "").slice(11,16)}',
    '                      </td>',
    '                      <td style={{ ...S.td, color: "var(--accent)", fontWeight: 700 }}>{f.symbol}</td>',
    '                      <td style={{ ...S.td, color: sentColor(f.type), fontSize: 11 }}>{f.type}</td>',
    '                      <td style={{ ...S.td, fontSize: 11 }}>{f.message}</td>',
    '                      <td style={S.td}>{f.value != null ? Number(f.value).toFixed(2) : "--"}</td>',
    '                    </tr>',
    '                  ))}',
    '                  {data.fired_today.length === 0 && (',
    '                    <tr><td colSpan={5} style={{ padding: 30, textAlign: "center", color: "var(--dim)" }}>',
    '                      No alerts fired today.',
    '                    </td></tr>',
    '                  )}',
    '                </tbody>',
    '              </table>',
    '            </div>',
    '          )}',
    '',
    '          {tab === "add" && (',
    '            <div style={{ background: "var(--surface)", border: "1px solid var(--border)",',
    '              borderRadius: 8, padding: "24px" }}>',
    '              <div style={{ fontSize: 10, color: "var(--dim)", letterSpacing: 1, marginBottom: 16 }}>',
    '                ADD NEW ALERT',
    '              </div>',
    '              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr auto", gap: 12, alignItems: "end" }}>',
    '                <div>',
    '                  <div style={{ fontSize: 10, color: "var(--dim)", marginBottom: 4 }}>SYMBOL</div>',
    '                  <input style={S.input} placeholder="e.g. RELIANCE"',
    '                    value={newSym} onChange={e => setNSym(e.target.value.toUpperCase())} />',
    '                </div>',
    '                <div>',
    '                  <div style={{ fontSize: 10, color: "var(--dim)", marginBottom: 4 }}>TYPE</div>',
    '                  <select style={S.sel} value={newType} onChange={e => setNTyp(e.target.value)}>',
    '                    {TYPES.map(t => <option key={t} value={t}>{t}</option>)}',
    '                  </select>',
    '                </div>',
    '                <div>',
    '                  <div style={{ fontSize: 10, color: "var(--dim)", marginBottom: 4 }}>THRESHOLD</div>',
    '                  <input style={S.input} placeholder="e.g. 1500"',
    '                    value={newVal} onChange={e => setNVal(e.target.value)} type="number" />',
    '                </div>',
    '                <button style={S.btn} onClick={addAlert} disabled={saving}>',
    '                  {saving ? "..." : "ADD"}',
    '                </button>',
    '              </div>',
    '              <div style={{ marginTop: 20, fontSize: 11, color: "var(--dim)", lineHeight: 1.8 }}>',
    '                <div style={{ marginBottom: 4, color: "var(--text)", fontSize: 10, letterSpacing: 1 }}>ALERT TYPES</div>',
    '                {TYPES.map(t => (',
    '                  <div key={t}><span style={{ color: sentColor(t) }}>{t}</span>',
    '                    {t === "PRICE_ABOVE" && "  -- fires when close > threshold"}',
    '                    {t === "PRICE_BELOW" && "  -- fires when close < threshold"}',
    '                    {t === "RSI_ABOVE"   && "  -- fires when RSI-14 > threshold (e.g. 70 = overbought)"}',
    '                    {t === "RSI_BELOW"   && "  -- fires when RSI-14 < threshold (e.g. 30 = oversold)"}',
    '                    {t === "VOLUME_SURGE"&& "  -- fires when volume > threshold x 20d avg"}',
    '                    {t === "BREAKOUT_52W"&& "  -- fires when close > 52w high (threshold ignored)"}',
    '                    {t === "STOP_HIT"    && "  -- fires when close < threshold (portfolio stop loss)"}',
    '                  </div>',
    '                ))}',
    '              </div>',
    '            </div>',
    '          )}',
    '        </>}',
    '      </div>',
    '    </div>',
    '  );',
    '}',
]

write(APP / "alerts" / "page.tsx", alerts_page_lines, "/alerts/page.tsx")


# /api/alerts/route.ts -- GET list + POST add + DELETE remove
alerts_api_lines = [
    'import { NextResponse } from "next/server";',
    'import { readFileSync, writeFileSync, existsSync } from "fs";',
    'import Database from "better-sqlite3";',
    '',
    'const DB         = "D:/marketDB/db/market.db";',
    'const ALERTS_FILE = "D:/MICC/alerts.json";',
    '',
    'function loadAlerts(): Record<string, unknown>[] {',
    '  try {',
    '    if (!existsSync(ALERTS_FILE)) return [];',
    '    const raw = JSON.parse(readFileSync(ALERTS_FILE, "utf-8"));',
    '    if (Array.isArray(raw)) return raw;',
    '    // Old format: {RSI_BELOW: {NIFTY50: 35}, PRICE_ABOVE: {RELIANCE: 1450}}',
    '    const out: Record<string, unknown>[] = [];',
    '    let id = 1;',
    '    for (const [type, syms] of Object.entries(raw)) {',
    '      if (typeof syms === "object" && syms !== null) {',
    '        for (const [symbol, threshold] of Object.entries(syms as Record<string,unknown>)) {',
    '          out.push({ id: String(id++), type, symbol, threshold,',
    '            enabled: true, fired_count: 0, last_fired_date: null });',
    '        }',
    '      }',
    '    }',
    '    return out;',
    '  } catch { return []; }',
    '}',
    '',
    'function saveAlerts(alerts: Record<string, unknown>[]) {',
    '  writeFileSync(ALERTS_FILE, JSON.stringify(alerts, null, 2), "utf-8");',
    '}',
    '',
    'export function GET() {',
    '  const alerts = loadAlerts();',
    '  let fired_today: unknown[] = [];',
    '  let db: ReturnType<typeof Database> | null = null;',
    '  try {',
    '    db = new Database(DB, { readonly: true, timeout: 5000 });',
    '    // Check for alert_history table',
    '    const tables = db.prepare(',
    '      "SELECT name FROM sqlite_master WHERE type=\'table\' AND name=\'alert_history\'"',
    '    ).all();',
    '    if (tables.length > 0) {',
    '      fired_today = db.prepare(',
    '        "SELECT symbol, alert_type AS type, message, fired_at, value"',
    '        " FROM alert_history"',
    '        " WHERE DATE(fired_at)=DATE(\'now\')"',
    '        " ORDER BY fired_at DESC LIMIT 50"',
    '      ).all();',
    '    }',
    '  } catch { /* no alert_history table yet */ }',
    '  finally { try { db?.close(); } catch {} }',
    '',
    '  return NextResponse.json({',
    '    alerts,',
    '    fired_today,',
    '    fired_count:   (fired_today as unknown[]).length,',
    '    total_alerts:  alerts.length,',
    '  });',
    '}',
    '',
    'export async function POST(req: Request) {',
    '  try {',
    '    const body = await req.json() as { symbol: string; type: string; threshold?: number };',
    '    const alerts = loadAlerts();',
    '    const id = String(Date.now());',
    '    alerts.push({',
    '      id,',
    '      symbol:         body.symbol.toUpperCase(),',
    '      type:           body.type,',
    '      threshold:      body.threshold ?? null,',
    '      enabled:        true,',
    '      fired_count:    0,',
    '      last_fired_date: null,',
    '      created_at:     new Date().toISOString(),',
    '    });',
    '    saveAlerts(alerts);',
    '    return NextResponse.json({ ok: true, id });',
    '  } catch (e) {',
    '    return NextResponse.json({ ok: false, error: String(e) }, { status: 400 });',
    '  }',
    '}',
    '',
    'export function DELETE(req: Request) {',
    '  try {',
    '    const url = new URL(req.url);',
    '    const id  = url.searchParams.get("id");',
    '    if (!id) return NextResponse.json({ ok: false, error: "id required" }, { status: 400 });',
    '    const alerts  = loadAlerts();',
    '    const updated = alerts.filter(a => (a as Record<string,unknown>).id !== id);',
    '    saveAlerts(updated);',
    '    return NextResponse.json({ ok: true, deleted: alerts.length - updated.length });',
    '  } catch (e) {',
    '    return NextResponse.json({ ok: false, error: String(e) }, { status: 400 });',
    '  }',
    '}',
]

write(APP / "api" / "alerts" / "route.ts", alerts_api_lines, "/api/alerts/route.ts")


print()
print("=" * 60)
print("PHASE 5 COMPLETE")
print("=" * 60)
print()
print("Files written:")
print("  D:\\MICC\\train_conviction_xgb.py            -- XGBoost model")
print("  ...api\\stocks\\[symbol]\\news\\route.ts      -- per-symbol news")
print("  ...api\\portfolio\\correlation\\route.ts     -- position correlations")
print("  ...alerts\\page.tsx                          -- full alert manager UI")
print("  ...api\\alerts\\route.ts                     -- GET/POST/DELETE alerts")
print()
print("Run XGBoost training (needs 100+ signals with forward returns):")
print("  py D:\\MICC\\train_conviction_xgb.py")
print("  (auto-installs xgboost + sklearn)")
print()
print("To just score current universe with existing model:")
print("  py D:\\MICC\\train_conviction_xgb.py --score")
print()
print("Git push all phases:")
print("  py D:\\MICC\\git_push_phase3.py")
