"""
build_phase4.py
===============
Phase 4: High-value upgrades

[1] HMM Regime Model (agent_hmm.py)
    - 3-state Hidden Markov Model on Nifty50 returns
    - States: BULL / BEAR / SIDEWAYS
    - Replaces hardcoded Nifty > 22000 check in fusion + conviction
    - Saves regime to DB table hmm_regime_daily

[2] /fusion page rebuild
    - Full drilldown: click any pick to see all 7 layer scores
    - Color-coded layer bars (beta/insider/watchlist/seasonal/conviction/quant)
    - Regime banner at top
    - Search + sort

[3] /options page rebuild
    - PCR, Max Pain, GEX, OI chart by strike
    - Participant OI (FII/DII/Retail) from participant_oi table
    - All in reference dark design

Run: py D:\MICC\build_phase4.py
"""
from pathlib import Path

MICC = Path(r"D:\MICC")
DASH = MICC / "micc-dashboard"
APP  = DASH / "src" / "app"

def write(path, lines, label=""):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  [OK] {label or path.name}  ({len(lines)} lines)")

def log(msg):
    from datetime import datetime
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)

print("=" * 60)
print("PHASE 4 BUILD")
print("=" * 60)


# =============================================================================
# [1]  HMM Regime Model — agent_hmm.py
# =============================================================================
log("[1/3] Building agent_hmm.py (HMM regime)...")

hmm_lines = [
    "\"\"\"",
    "agent_hmm.py  --  Hidden Markov Model regime detection",
    "3 states: BULL / SIDEWAYS / BEAR",
    "Fits on Nifty50 daily returns, saves to hmm_regime_daily table.",
    "Usage: py agent_hmm.py [--send]",
    "\"\"\"",
    "import sys, sqlite3, json",
    "from pathlib import Path",
    "from datetime import datetime",
    "",
    "DA      = Path(r'D:\\MICC')",
    "DB_PATH = r'D:\\marketDB\\db\\market.db'",
    "send    = '--send' in sys.argv",
    "",
    "def log(msg): print(f'  {msg}', flush=True)",
    "",
    "# ── Install hmmlearn if needed ────────────────────────────────────────────",
    "try:",
    "    from hmmlearn.hmm import GaussianHMM",
    "    import numpy as np",
    "except ImportError:",
    "    import subprocess",
    "    subprocess.run([sys.executable, '-m', 'pip', 'install',",
    "                    'hmmlearn', 'numpy', '--break-system-packages', '-q'])",
    "    from hmmlearn.hmm import GaussianHMM",
    "    import numpy as np",
    "",
    "print('Agent HMM -- Regime Detection')",
    "print('=' * 40)",
    "",
    "# ── Load Nifty50 returns from parquet or DB ───────────────────────────────",
    "def load_nifty_returns():",
    "    log('Loading Nifty50 data...')",
    "    conn = sqlite3.connect(DB_PATH, timeout=15)",
    "    # Try global_indices_daily first",
    "    rows = conn.execute(",
    "        'SELECT date, close FROM global_indices_daily'",
    "        ' WHERE symbol=\"NIFTY50\" ORDER BY date ASC'",
    "    ).fetchall()",
    "    if not rows:",
    "        # Fallback: market_snapshot",
    "        rows = conn.execute(",
    "            'SELECT date, closing_index_value FROM market_snapshot'",
    "            ' WHERE index_name=\"Nifty 50\" ORDER BY date ASC'",
    "        ).fetchall()",
    "    conn.close()",
    "    if len(rows) < 100:",
    "        raise ValueError(f'Not enough data: {len(rows)} rows')",
    "    dates  = [r[0] for r in rows]",
    "    closes = np.array([float(r[1]) for r in rows])",
    "    returns = np.diff(np.log(closes))  # log returns",
    "    dates   = dates[1:]",
    "    log(f'Loaded {len(returns)} returns ({dates[0]} to {dates[-1]})')",
    "    return dates, returns",
    "",
    "# ── Fit HMM ──────────────────────────────────────────────────────────────",
    "def fit_hmm(returns, n_states=3):",
    "    log(f'Fitting {n_states}-state Gaussian HMM...')",
    "    X = returns.reshape(-1, 1)",
    "    model = GaussianHMM(",
    "        n_components=n_states,",
    "        covariance_type='full',",
    "        n_iter=200,",
    "        random_state=42",
    "    )",
    "    model.fit(X)",
    "    states = model.predict(X)",
    "    # Assign state labels: highest mean return = BULL, lowest = BEAR",
    "    means = model.means_.flatten()",
    "    order = np.argsort(means)  # [lowest, mid, highest]",
    "    label_map = {",
    "        order[0]: 'BEAR',",
    "        order[1]: 'SIDEWAYS',",
    "        order[2]: 'BULL',",
    "    }",
    "    labels = [label_map[s] for s in states]",
    "    # State stats",
    "    for i, state_num in enumerate(order):",
    "        mask = states == state_num",
    "        name = label_map[state_num]",
    "        mu   = means[state_num] * 100",
    "        sig  = np.sqrt(model.covars_[state_num][0][0]) * 100",
    "        days = mask.sum()",
    "        log(f'  {name:<10} mean={mu:+.3f}%  vol={sig:.3f}%  days={days}')",
    "    return model, states, labels, label_map, means",
    "",
    "# ── Get current state probabilities ──────────────────────────────────────",
    "def get_current_state(model, returns):",
    "    X = returns.reshape(-1, 1)",
    "    probs = model.predict_proba(X)",
    "    # Last observation probabilities",
    "    last_probs = probs[-1]",
    "    current_state = np.argmax(last_probs)",
    "    confidence = float(last_probs[current_state])",
    "    return current_state, confidence, last_probs",
    "",
    "# ── Save to DB ────────────────────────────────────────────────────────────",
    "def save_to_db(dates, labels, means, model, returns, label_map):",
    "    conn = sqlite3.connect(DB_PATH, timeout=30)",
    "    conn.execute('PRAGMA journal_mode=WAL')",
    "    conn.execute(",
    "        'CREATE TABLE IF NOT EXISTS hmm_regime_daily ('",
    "        '  date TEXT PRIMARY KEY,'",
    "        '  regime TEXT,'",
    "        '  bull_prob REAL,'",
    "        '  bear_prob REAL,'",
    "        '  sideways_prob REAL,'",
    "        '  updated_at TEXT'",
    "        ')'",
    "    )",
    "    X     = returns.reshape(-1, 1)",
    "    probs = model.predict_proba(X)",
    "    # Map state indices to regime labels",
    "    order = np.argsort(means)",
    "    bear_idx     = int(order[0])",
    "    side_idx     = int(order[1])",
    "    bull_idx     = int(order[2])",
    "    now = datetime.now().isoformat()",
    "    batch = []",
    "    for i, (date, label) in enumerate(zip(dates, labels)):",
    "        batch.append((",
    "            date, label,",
    "            round(float(probs[i][bull_idx]), 4),",
    "            round(float(probs[i][bear_idx]), 4),",
    "            round(float(probs[i][side_idx]), 4),",
    "            now",
    "        ))",
    "    conn.executemany(",
    "        'INSERT OR REPLACE INTO hmm_regime_daily'",
    "        ' (date,regime,bull_prob,bear_prob,sideways_prob,updated_at)'",
    "        ' VALUES (?,?,?,?,?,?)',",
    "        batch",
    "    )",
    "    conn.commit()",
    "    conn.close()",
    "    log(f'Saved {len(batch)} rows to hmm_regime_daily')",
    "",
    "# ── Main ─────────────────────────────────────────────────────────────────",
    "try:",
    "    dates, returns = load_nifty_returns()",
    "    model, states, labels, label_map, means = fit_hmm(returns)",
    "    curr_state, confidence, last_probs = get_current_state(model, returns)",
    "    order = np.argsort(means)",
    "    current_regime = label_map[curr_state]",
    "    log(f'')",
    "    log(f'CURRENT REGIME: {current_regime}  (confidence={confidence:.1%})')",
    "    log(f'  Bull prob:     {float(last_probs[order[2]]):.1%}')",
    "    log(f'  Sideways prob: {float(last_probs[order[1]]):.1%}')",
    "    log(f'  Bear prob:     {float(last_probs[order[0]]):.1%}')",
    "    save_to_db(dates, labels, means, model, returns, label_map)",
    "    # Save summary JSON",
    "    out_dir = DA / 'agents' / 'hmm'",
    "    out_dir.mkdir(parents=True, exist_ok=True)",
    "    summary = {",
    "        'agent':          'hmm',",
    "        'date':           datetime.now().strftime('%Y-%m-%d'),",
    "        'current_regime': current_regime,",
    "        'confidence':     round(confidence, 4),",
    "        'bull_prob':      round(float(last_probs[order[2]]), 4),",
    "        'sideways_prob':  round(float(last_probs[order[1]]), 4),",
    "        'bear_prob':      round(float(last_probs[order[0]]), 4),",
    "        'last_date':      dates[-1],",
    "        'n_days':         len(dates),",
    "    }",
    "    (out_dir / 'last_report.json').write_text(",
    "        json.dumps(summary, indent=2), encoding='utf-8'",
    "    )",
    "    print()",
    "    print(f'Current regime: {current_regime} ({confidence:.0%} confidence)')",
    "    if send:",
    "        import re, urllib.request",
    "        env  = (DA / '.env').read_text()",
    "        BOT  = re.search(r'TELEGRAM_TOKEN=([^\\n]+)', env).group(1).strip()",
    "        CHAT = re.search(r'TELEGRAM_CHAT_ID=([^\\n]+)', env).group(1).strip()",
    "        color = {'BULL':'UP', 'BEAR':'DN', 'SIDEWAYS':'--'}[current_regime]",
    "        msg = ('HMM Regime Update\\n'",
    "               f'{color} {current_regime}  ({confidence:.0%} confidence)\\n'",
    "               f'Bull={float(last_probs[order[2]]):.0%}  '",
    "               f'Side={float(last_probs[order[1]]):.0%}  '",
    "               f'Bear={float(last_probs[order[0]]):.0%}')",
    "        data = json.dumps({'chat_id':CHAT,'text':msg}).encode()",
    "        urllib.request.urlopen(",
    "            urllib.request.Request(",
    "                f'https://api.telegram.org/bot{BOT}/sendMessage',",
    "                data=data, headers={'Content-Type':'application/json'}",
    "            ), timeout=10",
    "        )",
    "        print('  Telegram: OK')",
    "except Exception as e:",
    "    print(f'HMM failed: {e}')",
    "    import traceback; traceback.print_exc()",
]

write(MICC / "agent_hmm.py", hmm_lines, "agent_hmm.py")


# =============================================================================
# [2]  Update agent_fusion.py to use HMM regime instead of hardcoded price
# =============================================================================
log("[1b] Patching agent_fusion.py to use HMM regime...")

fusion_path = MICC / "agent_fusion.py"
fusion_src = fusion_path.read_text(encoding="utf-8")

old_regime = (
    'nr = qdb(\n'
    '    "SELECT closing_index_value AS close FROM market_snapshot "\n'
    '    "WHERE index_name=\'NIFTY 50\' ORDER BY date DESC LIMIT 1"\n'
    ')\n'
    'nifty  = float(nr[0]["close"]) if nr else 0.0\n'
    'regime = "BULLISH" if nifty > 22000 else "SIDEWAYS" if nifty > 18000 else "BEARISH" if nifty > 0 else "UNKNOWN"'
)

new_regime = (
    'nr = qdb(\n'
    '    "SELECT closing_index_value AS close FROM market_snapshot "\n'
    '    "WHERE index_name=\'NIFTY 50\' ORDER BY date DESC LIMIT 1"\n'
    ')\n'
    'nifty = float(nr[0]["close"]) if nr else 0.0\n'
    '# Try HMM regime first, fall back to price-based\n'
    'hmm_rows = qdb(\n'
    '    "SELECT regime, bull_prob, bear_prob, sideways_prob"\n'
    '    " FROM hmm_regime_daily ORDER BY date DESC LIMIT 1"\n'
    ')\n'
    'if hmm_rows:\n'
    '    regime     = hmm_rows[0]["regime"]\n'
    '    bull_p     = hmm_rows[0]["bull_prob"]\n'
    '    bear_p     = hmm_rows[0]["bear_prob"]\n'
    'else:\n'
    '    regime = "BULLISH" if nifty > 22000 else "SIDEWAYS" if nifty > 18000 else "BEARISH" if nifty > 0 else "UNKNOWN"\n'
    '    bull_p = bear_p = None'
)

if old_regime in fusion_src:
    fusion_src = fusion_src.replace(old_regime, new_regime, 1)
    # Also add bull_p/bear_p to the report meta
    fusion_src = fusion_src.replace(
        '"regime":       regime,',
        '"regime":       regime,\n        "bull_prob":    bull_p,\n        "bear_prob":    bear_p,'
    )
    fusion_path.write_text(fusion_src, encoding="utf-8")
    print("  [OK] agent_fusion.py uses HMM regime")
else:
    print("  [WARN] Could not patch agent_fusion.py regime section (pattern changed)")


# =============================================================================
# [3]  /fusion page — full rebuild with drilldown
# =============================================================================
log("[2/3] Building /fusion page with drilldown...")

fusion_page_lines = [
    '"use client";',
    'import NavBar from "@/components/NavBar";',
    'import { useEffect, useState } from "react";',
    '',
    'interface Pick {',
    '  symbol: string; n_layers: number; layers_fired: string[];',
    '  reasons: string[]; beta_score: number; regime_score: number;',
    '  insider_score: number; watchlist_score: number;',
    '  seasonal_score: number; conviction_score: number; quant_score: number;',
    '}',
    'interface FusionData {',
    '  picks: Pick[]; date?: string; generated_at?: string;',
    '  meta?: { regime: string; nifty: number; total_picks: number;',
    '           bull_prob?: number; bear_prob?: number; agents_run?: number };',
    '}',
    '',
    'const LAYER_DEFS: { key: keyof Pick; label: string; color: string; desc: string }[] = [',
    '  { key: "beta_score",       label: "BETA",       color: "var(--accent)", desc: "Momentum screens" },',
    '  { key: "regime_score",     label: "REGIME",     color: "var(--info)",   desc: "Macro/Alpha signals" },',
    '  { key: "insider_score",    label: "INSIDER",    color: "var(--warn)",   desc: "Corporate events/insider" },',
    '  { key: "watchlist_score",  label: "WATCHLIST",  color: "#a78bfa",       desc: "Manual watchlist" },',
    '  { key: "seasonal_score",   label: "SEASONAL",   color: "var(--bull)",   desc: "Engine seasonality" },',
    '  { key: "conviction_score", label: "CONVICTION", color: "#f472b6",       desc: "FII/DII flows" },',
    '  { key: "quant_score",      label: "QUANT",      color: "#34d399",       desc: "Options/GEX/Global" },',
    '];',
    '',
    'function regimeColor(r: string) {',
    '  if (!r) return "var(--dim)";',
    '  r = r.toUpperCase();',
    '  if (r === "BULL" || r === "BULLISH") return "var(--bull)";',
    '  if (r === "BEAR" || r === "BEARISH") return "var(--bear)";',
    '  return "var(--warn)";',
    '}',
    '',
    'function LayerBar({ score, color, label }: { score: number; color: string; label: string }) {',
    '  const pct = Math.round(score * 100);',
    '  return (',
    '    <div style={{ marginBottom: 6 }}>',
    '      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 2 }}>',
    '        <span style={{ fontSize: 9, color: "var(--dim)", letterSpacing: 1 }}>{label}</span>',
    '        <span style={{ fontSize: 9, color: score > 0 ? color : "var(--muted)" }}>',
    '          {score > 0 ? "HIT" : "miss"}',
    '        </span>',
    '      </div>',
    '      <div style={{ height: 4, background: "var(--bg)", borderRadius: 2 }}>',
    '        <div style={{ height: "100%", width: pct + "%", background: color,',
    '          borderRadius: 2, transition: "width 0.3s ease" }} />',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    '',
    'function PickCard({ p, expanded, onToggle }: {',
    '  p: Pick; expanded: boolean; onToggle: () => void;',
    '}) {',
    '  const S: Record<string, React.CSSProperties> = {',
    '    card:  { background: "var(--surface)", border: "1px solid var(--border)",',
    '             borderRadius: 8, marginBottom: 8, overflow: "hidden" },',
    '    header:{ display: "flex", alignItems: "center", gap: 12, padding: "10px 16px",',
    '             cursor: "pointer", userSelect: "none" },',
    '    sym:   { fontSize: 14, fontWeight: 700, color: "var(--accent)", width: 120 },',
    '    badge: { fontSize: 10, padding: "2px 8px", borderRadius: 3,',
    '             background: "var(--accent)22", color: "var(--accent)" },',
    '    layers:{ display: "flex", gap: 4, flex: 1, flexWrap: "wrap" as const },',
    '    ltag:  { fontSize: 9, padding: "2px 6px", borderRadius: 3,',
    '             background: "var(--bg)", border: "1px solid var(--border)", color: "var(--dim)" },',
    '    body:  { padding: "0 16px 16px", borderTop: "1px solid var(--border)" },',
    '    grid:  { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0 24px", marginTop: 12 },',
    '    reas:  { marginTop: 12 },',
    '    rtitle:{ fontSize: 10, color: "var(--dim)", letterSpacing: 1, marginBottom: 6 },',
    '    ritem: { fontSize: 11, color: "var(--text)", lineHeight: 1.7,',
    '             borderBottom: "1px solid var(--border)", paddingBottom: 3, marginBottom: 3 },',
    '  };',
    '  return (',
    '    <div style={S.card}>',
    '      <div style={S.header} onClick={onToggle}>',
    '        <span style={S.sym}>{p.symbol}</span>',
    '        <span style={S.badge}>{p.n_layers}L</span>',
    '        <div style={S.layers}>',
    '          {p.layers_fired.map(l => (',
    '            <span key={l} style={S.ltag}>{l.slice(0, 3).toUpperCase()}</span>',
    '          ))}',
    '        </div>',
    '        <span style={{ fontSize: 12, color: "var(--dim)" }}>{expanded ? "[-]" : "[+]"}</span>',
    '      </div>',
    '      {expanded && (',
    '        <div style={S.body}>',
    '          <div style={S.grid}>',
    '            <div>',
    '              <div style={{ fontSize: 10, color: "var(--dim)", letterSpacing: 1, marginBottom: 8, marginTop: 12 }}>',
    '                LAYER SCORES',
    '              </div>',
    '              {LAYER_DEFS.map(l => (',
    '                <LayerBar key={l.key} score={Number(p[l.key]) || 0}',
    '                  color={l.color} label={l.label} />',
    '              ))}',
    '            </div>',
    '            <div>',
    '              <div style={S.reas}>',
    '                <div style={S.rtitle}>SIGNAL REASONS</div>',
    '                {p.reasons.map((r, i) => (',
    '                  <div key={i} style={S.ritem}>{r}</div>',
    '                ))}',
    '                {p.reasons.length === 0 && (',
    '                  <div style={{ color: "var(--muted)", fontSize: 11 }}>No reasons logged</div>',
    '                )}',
    '              </div>',
    '            </div>',
    '          </div>',
    '        </div>',
    '      )}',
    '    </div>',
    '  );',
    '}',
    '',
    'export default function FusionPage() {',
    '  const [data, setData]     = useState<FusionData | null>(null);',
    '  const [loading, setL]     = useState(true);',
    '  const [error, setE]       = useState("");',
    '  const [search, setSrch]   = useState("");',
    '  const [minL, setMinL]     = useState(2);',
    '  const [expanded, setExp]  = useState<Set<string>>(new Set());',
    '  const [expandAll, setAll] = useState(false);',
    '',
    '  useEffect(() => {',
    '    fetch("/api/fusion")',
    '      .then(r => r.json())',
    '      .then(d => { setData(d); setL(false); })',
    '      .catch(e => { setE(e.message); setL(false); });',
    '  }, []);',
    '',
    '  const S: Record<string, React.CSSProperties> = {',
    '    page:  { minHeight: "100vh", background: "var(--bg)", fontFamily: "JetBrains Mono, monospace" },',
    '    sub:   { position: "sticky", top: 48, zIndex: 90, background: "var(--surface)",',
    '             borderBottom: "1px solid var(--border)", padding: "6px 20px",',
    '             display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" as const },',
    '    stitle:{ fontSize: 10, color: "var(--dim)", letterSpacing: 2 },',
    '    wrap:  { maxWidth: 1400, margin: "0 auto", padding: "16px 20px" },',
    '    kv:    { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 6,',
    '             padding: "10px 16px", display: "inline-block", marginRight: 10, marginBottom: 12 },',
    '    kvk:   { fontSize: 10, color: "var(--dim)", letterSpacing: 1 },',
    '    kvv:   { fontSize: 18, fontWeight: 700, marginTop: 2 },',
    '    input: { background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 4,',
    '             padding: "4px 10px", fontSize: 11, color: "var(--text)", outline: "none" },',
    '    btn:   (active: boolean): React.CSSProperties => ({',
    '      padding: "4px 12px", fontSize: 10, letterSpacing: 1, cursor: "pointer",',
    '      border: "1px solid " + (active ? "var(--accent)" : "var(--border)"),',
    '      borderRadius: 4, background: active ? "var(--accent)22" : "transparent",',
    '      color: active ? "var(--accent)" : "var(--dim)",',
    '    }),',
    '  };',
    '',
    '  const picks = (data?.picks || [])',
    '    .filter(p => p.n_layers >= minL)',
    '    .filter(p => !search || p.symbol.toLowerCase().includes(search.toLowerCase()));',
    '',
    '  const regime = data?.meta?.regime || "--";',
    '  const nifty  = data?.meta?.nifty;',
    '  const bullP  = data?.meta?.bull_prob;',
    '  const bearP  = data?.meta?.bear_prob;',
    '',
    '  function toggleAll() {',
    '    if (expandAll) {',
    '      setExp(new Set());',
    '      setAll(false);',
    '    } else {',
    '      setExp(new Set(picks.map(p => p.symbol)));',
    '      setAll(true);',
    '    }',
    '  }',
    '',
    '  function toggleOne(sym: string) {',
    '    setExp(prev => {',
    '      const next = new Set(prev);',
    '      if (next.has(sym)) next.delete(sym);',
    '      else next.add(sym);',
    '      return next;',
    '    });',
    '  }',
    '',
    '  return (',
    '    <div style={S.page}>',
    '      <NavBar />',
    '      <div style={S.sub}>',
    '        <span style={S.stitle}>FUSION  /  MULTI-LAYER SIGNAL PICKS</span>',
    '        <input style={S.input} placeholder="search symbol..."',
    '          value={search} onChange={e => setSrch(e.target.value)} />',
    '        {[2,3,4,5].map(n => (',
    '          <button key={n} style={S.btn(minL === n)} onClick={() => setMinL(n)}>',
    '            {n}L+',
    '          </button>',
    '        ))}',
    '        <button style={S.btn(expandAll)} onClick={toggleAll}>',
    '          {expandAll ? "COLLAPSE ALL" : "EXPAND ALL"}',
    '        </button>',
    '        {data?.generated_at && (',
    '          <span style={{ fontSize: 10, color: "var(--dim)", marginLeft: "auto" }}>',
    '            {data.generated_at}',
    '          </span>',
    '        )}',
    '      </div>',
    '',
    '      <div style={S.wrap}>',
    '        {loading && <div style={{ color: "var(--dim)", padding: 40, textAlign: "center" }}>Loading fusion picks...</div>}',
    '        {error   && <div style={{ color: "var(--bear)", padding: 20 }}>Error: {error}</div>}',
    '',
    '        {data && <>',
    '          {/* Regime + stats banner */}',
    '          <div style={{ display: "flex", flexWrap: "wrap", gap: 10, marginBottom: 20 }}>',
    '            <div style={S.kv}>',
    '              <div style={S.kvk}>REGIME (HMM)</div>',
    '              <div style={{ ...S.kvv, color: regimeColor(regime) }}>{regime}</div>',
    '            </div>',
    '            {nifty != null && <div style={S.kv}>',
    '              <div style={S.kvk}>NIFTY 50</div>',
    '              <div style={S.kvv}>{Number(nifty).toLocaleString("en-IN")}</div>',
    '            </div>}',
    '            {bullP != null && <div style={S.kv}>',
    '              <div style={S.kvk}>BULL PROB</div>',
    '              <div style={{ ...S.kvv, color: "var(--bull)" }}>{(bullP * 100).toFixed(0)}%</div>',
    '            </div>}',
    '            {bearP != null && <div style={S.kv}>',
    '              <div style={S.kvk}>BEAR PROB</div>',
    '              <div style={{ ...S.kvv, color: "var(--bear)" }}>{(bearP * 100).toFixed(0)}%</div>',
    '            </div>}',
    '            <div style={S.kv}>',
    '              <div style={S.kvk}>PICKS ({minL}L+)</div>',
    '              <div style={S.kvv}>{picks.length}</div>',
    '            </div>',
    '          </div>',
    '',
    '          {/* Layer legend */}',
    '          <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 16 }}>',
    '            {LAYER_DEFS.map(l => (',
    '              <span key={l.key} style={{ fontSize: 9, padding: "2px 8px", borderRadius: 3,',
    '                border: "1px solid " + l.color + "44", color: l.color }}>',
    '                {l.label}  {l.desc}',
    '              </span>',
    '            ))}',
    '          </div>',
    '',
    '          {/* Picks */}',
    '          {picks.length === 0 && (',
    '            <div style={{ color: "var(--dim)", padding: 40, textAlign: "center" }}>',
    '              No picks for {minL}L+ filter. Try 2L+.',
    '            </div>',
    '          )}',
    '          {picks.map(p => (',
    '            <PickCard key={p.symbol} p={p}',
    '              expanded={expanded.has(p.symbol)}',
    '              onToggle={() => toggleOne(p.symbol)} />',
    '          ))}',
    '        </>}',
    '      </div>',
    '    </div>',
    '  );',
    '}',
]

write(APP / "fusion" / "page.tsx", fusion_page_lines, "/fusion/page.tsx")


# /api/fusion/route.ts — reads last_report.json
fusion_api_lines = [
    'import { NextResponse } from "next/server";',
    'import { readFileSync } from "fs";',
    '',
    'const REPORT = "D:/MICC/agents/fusion/last_report.json";',
    '',
    'export function GET() {',
    '  try {',
    '    const raw = readFileSync(REPORT, "utf-8")',
    '      .replace(/:\\s*NaN\\b/g, ": null")',
    '      .replace(/:\\s*Infinity\\b/g, ": null");',
    '    return NextResponse.json(JSON.parse(raw));',
    '  } catch {',
    '    return NextResponse.json({ picks: [], error: "Run agent_fusion.py first" });',
    '  }',
    '}',
]

write(APP / "api" / "fusion" / "route.ts", fusion_api_lines, "/api/fusion/route.ts")


# =============================================================================
# [4]  /options page — full rebuild with PCR, max pain, participant OI
# =============================================================================
log("[3/3] Rebuilding /options page...")

options_page_lines = [
    '"use client";',
    'import NavBar from "@/components/NavBar";',
    'import { useEffect, useState } from "react";',
    '',
    'interface StrikeRow {',
    '  strike: number; call_oi: number; put_oi: number;',
    '  call_vol: number; put_vol: number; call_iv?: number; put_iv?: number;',
    '}',
    'interface ParticipantRow {',
    '  category: string;',
    '  fut_idx_long: number; fut_idx_short: number;',
    '  opt_idx_call_long: number; opt_idx_call_short: number;',
    '  opt_idx_put_long: number; opt_idx_put_short: number;',
    '}',
    'interface OptionsData {',
    '  latest_date?: string; expiry?: string; spot?: number;',
    '  pcr?: number; max_pain?: number; total_call_oi?: number; total_put_oi?: number;',
    '  strikes?: StrikeRow[]; participant_oi?: ParticipantRow[];',
    '  nifty_close?: number; nifty_change_pct?: number;',
    '  atm_iv?: number; iv_rank?: number;',
    '}',
    '',
    'const fmt  = (v: unknown, d = 0) => v == null ? "--" : Number(v).toFixed(d);',
    'const fmtK = (v: unknown) => {',
    '  if (v == null) return "--";',
    '  const n = Number(v);',
    '  return n >= 1e6 ? (n/1e6).toFixed(1)+"M" : n >= 1e3 ? (n/1e3).toFixed(0)+"K" : String(n);',
    '};',
    '',
    'function OIBar({ callOI, putOI, strike, spot }: {',
    '  callOI: number; putOI: number; strike: number; spot?: number;',
    '}) {',
    '  const total = (callOI + putOI) || 1;',
    '  const callPct = (callOI / total) * 100;',
    '  const putPct  = (putOI  / total) * 100;',
    '  const isATM   = spot != null && Math.abs(strike - spot) / spot < 0.01;',
    '  return (',
    '    <div style={{ display: "flex", height: 16, borderRadius: 2, overflow: "hidden",',
    '      border: isATM ? "1px solid var(--accent)" : "none", minWidth: 80 }}>',
    '      <div style={{ width: callPct+"%", background: "var(--bear)", opacity: 0.8 }} />',
    '      <div style={{ width: putPct+"%",  background: "var(--bull)", opacity: 0.8 }} />',
    '    </div>',
    '  );',
    '}',
    '',
    'export default function OptionsPage() {',
    '  const [data, setData] = useState<OptionsData | null>(null);',
    '  const [loading, setL] = useState(true);',
    '  const [error, setE]   = useState("");',
    '  const [tab, setTab]   = useState<"chain"|"participant"|"analysis">("chain");',
    '',
    '  useEffect(() => {',
    '    fetch("/api/options")',
    '      .then(r => r.json())',
    '      .then(d => { setData(d); setL(false); })',
    '      .catch(e => { setE(e.message); setL(false); });',
    '  }, []);',
    '',
    '  const S: Record<string, React.CSSProperties> = {',
    '    page:  { minHeight: "100vh", background: "var(--bg)", fontFamily: "JetBrains Mono, monospace" },',
    '    sub:   { position: "sticky", top: 48, zIndex: 90, background: "var(--surface)",',
    '             borderBottom: "1px solid var(--border)", padding: "6px 20px",',
    '             display: "flex", alignItems: "center", gap: 16 },',
    '    stitle:{ fontSize: 10, color: "var(--dim)", letterSpacing: 2 },',
    '    wrap:  { maxWidth: 1400, margin: "0 auto", padding: "16px 20px" },',
    '    grid:  { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(140px,1fr))", gap: 10, marginBottom: 20 },',
    '    kv:    { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 6, padding: "12px 16px" },',
    '    kvk:   { fontSize: 10, color: "var(--dim)", letterSpacing: 1, marginBottom: 4 },',
    '    kvv:   { fontSize: 20, fontWeight: 700, color: "var(--text)" },',
    '    tabs:  { display: "flex", gap: 6, marginBottom: 20 },',
    '    tab:   (a: boolean): React.CSSProperties => ({',
    '      padding: "5px 16px", fontSize: 11, letterSpacing: 1, cursor: "pointer",',
    '      border: "1px solid " + (a ? "var(--accent)" : "var(--border)"),',
    '      borderRadius: 4, background: a ? "var(--accent)22" : "transparent",',
    '      color: a ? "var(--accent)" : "var(--dim)",',
    '    }),',
    '    card:  { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 8, overflow: "hidden" },',
    '    tbl:   { width: "100%", borderCollapse: "collapse" as const, fontSize: 12 },',
    '    th:    { padding: "8px 10px", textAlign: "left" as const, fontSize: 10, letterSpacing: 1,',
    '             color: "var(--dim)", borderBottom: "1px solid var(--border)", background: "var(--surface)" },',
    '    thr:   { padding: "8px 10px", textAlign: "right" as const, fontSize: 10, letterSpacing: 1,',
    '             color: "var(--dim)", borderBottom: "1px solid var(--border)", background: "var(--surface)" },',
    '    td:    { padding: "7px 10px", borderBottom: "1px solid var(--border)", color: "var(--text)" },',
    '    tdr:   { padding: "7px 10px", borderBottom: "1px solid var(--border)",',
    '             color: "var(--text)", textAlign: "right" as const },',
    '  };',
    '',
    '  const pcr = data?.pcr;',
    '  const pcrColor = pcr == null ? "var(--text)" : pcr > 1.3 ? "var(--bull)" : pcr < 0.7 ? "var(--bear)" : "var(--warn)";',
    '  const pcrLabel = pcr == null ? "--" : pcr > 1.3 ? "BULLISH" : pcr < 0.7 ? "BEARISH" : "NEUTRAL";',
    '',
    '  return (',
    '    <div style={S.page}>',
    '      <NavBar />',
    '      <div style={S.sub}>',
    '        <span style={S.stitle}>OPTIONS  /  NIFTY CHAIN</span>',
    '        {data?.latest_date && <span style={{ fontSize: 10, color: "var(--dim)" }}>{data.latest_date}</span>}',
    '        {data?.expiry      && <span style={{ fontSize: 10, color: "var(--info)" }}>Expiry: {data.expiry}</span>}',
    '      </div>',
    '',
    '      <div style={S.wrap}>',
    '        {loading && <div style={{ color: "var(--dim)", padding: 40, textAlign: "center" }}>Loading options data...</div>}',
    '        {error   && <div style={{ color: "var(--bear)", padding: 20 }}>Error: {error} -- run pipeline to fetch options data</div>}',
    '',
    '        {data && <>',
    '          {/* KPI grid */}',
    '          <div style={S.grid}>',
    '            <div style={S.kv}>',
    '              <div style={S.kvk}>NIFTY SPOT</div>',
    '              <div style={S.kvv}>{data.nifty_close ? Number(data.nifty_close).toLocaleString("en-IN") : "--"}</div>',
    '            </div>',
    '            <div style={S.kv}>',
    '              <div style={S.kvk}>PCR</div>',
    '              <div style={{ ...S.kvv, color: pcrColor }}>{fmt(data.pcr, 2)}</div>',
    '              <div style={{ fontSize: 10, color: pcrColor }}>{pcrLabel}</div>',
    '            </div>',
    '            <div style={S.kv}>',
    '              <div style={S.kvk}>MAX PAIN</div>',
    '              <div style={S.kvv}>{data.max_pain ? Number(data.max_pain).toLocaleString("en-IN") : "--"}</div>',
    '            </div>',
    '            <div style={S.kv}>',
    '              <div style={S.kvk}>ATM IV</div>',
    '              <div style={S.kvv}>{fmt(data.atm_iv, 1)}{data.atm_iv ? "%" : ""}</div>',
    '            </div>',
    '            <div style={S.kv}>',
    '              <div style={S.kvk}>IV RANK</div>',
    '              <div style={{ ...S.kvv, color: Number(data.iv_rank) > 70 ? "var(--bear)" : "var(--bull)" }}>',
    '                {fmt(data.iv_rank, 0)}{data.iv_rank ? "%" : ""}',
    '              </div>',
    '            </div>',
    '            <div style={S.kv}>',
    '              <div style={S.kvk}>CALL OI</div>',
    '              <div style={{ ...S.kvv, color: "var(--bear)", fontSize: 16 }}>{fmtK(data.total_call_oi)}</div>',
    '            </div>',
    '            <div style={S.kv}>',
    '              <div style={S.kvk}>PUT OI</div>',
    '              <div style={{ ...S.kvv, color: "var(--bull)", fontSize: 16 }}>{fmtK(data.total_put_oi)}</div>',
    '            </div>',
    '          </div>',
    '',
    '          {/* Tabs */}',
    '          <div style={S.tabs}>',
    '            {(["chain","participant","analysis"] as const).map(t => (',
    '              <button key={t} onClick={() => setTab(t)} style={S.tab(tab === t)}>',
    '                {t.toUpperCase()}',
    '              </button>',
    '            ))}',
    '          </div>',
    '',
    '          {/* OI Chain */}',
    '          {tab === "chain" && (',
    '            <div style={S.card}>',
    '              <table style={S.tbl}>',
    '                <thead><tr>',
    '                  <th style={S.thr}>CALL OI</th>',
    '                  <th style={S.thr}>CALL VOL</th>',
    '                  <th style={{ ...S.th, textAlign: "center", fontWeight: 700, color: "var(--accent)" }}>STRIKE</th>',
    '                  <th style={S.th}>PUT OI</th>',
    '                  <th style={S.th}>PUT VOL</th>',
    '                  <th style={S.th}>OI RATIO</th>',
    '                </tr></thead>',
    '                <tbody>',
    '                  {(data.strikes || []).map((row, i) => {',
    '                    const isATM = data.spot != null && Math.abs(row.strike - data.spot) / data.spot < 0.01;',
    '                    const rowBg = isATM ? "var(--accent)11" : i%2===0 ? "transparent" : "var(--surface)88";',
    '                    return (',
    '                      <tr key={row.strike} style={{ background: rowBg }}>',
    '                        <td style={{ ...S.tdr, color: "var(--bear)" }}>{fmtK(row.call_oi)}</td>',
    '                        <td style={S.tdr}>{fmtK(row.call_vol)}</td>',
    '                        <td style={{ ...S.td, textAlign: "center", fontWeight: isATM ? 700 : 400,',
    '                          color: isATM ? "var(--accent)" : "var(--text)" }}>',
    '                          {row.strike.toLocaleString("en-IN")}',
    '                        </td>',
    '                        <td style={{ ...S.td, color: "var(--bull)" }}>{fmtK(row.put_oi)}</td>',
    '                        <td style={S.td}>{fmtK(row.put_vol)}</td>',
    '                        <td style={S.td}>',
    '                          <OIBar callOI={row.call_oi} putOI={row.put_oi}',
    '                            strike={row.strike} spot={data.spot} />',
    '                        </td>',
    '                      </tr>',
    '                    );',
    '                  })}',
    '                  {(!data.strikes || data.strikes.length === 0) && (',
    '                    <tr><td colSpan={6} style={{ padding: 30, textAlign: "center", color: "var(--dim)" }}>',
    '                      No options chain data -- run pipeline phase2_greeks_calculator.py',
    '                    </td></tr>',
    '                  )}',
    '                </tbody>',
    '              </table>',
    '            </div>',
    '          )}',
    '',
    '          {/* Participant OI */}',
    '          {tab === "participant" && (',
    '            <div style={S.card}>',
    '              <table style={S.tbl}>',
    '                <thead><tr>',
    '                  <th style={S.th}>CATEGORY</th>',
    '                  <th style={S.thr}>FUT IDX LONG</th>',
    '                  <th style={S.thr}>FUT IDX SHORT</th>',
    '                  <th style={S.thr}>NET FUT</th>',
    '                  <th style={S.thr}>CALL LONG</th>',
    '                  <th style={S.thr}>PUT LONG</th>',
    '                  <th style={S.thr}>NET OPT</th>',
    '                </tr></thead>',
    '                <tbody>',
    '                  {(data.participant_oi || []).map((r, i) => {',
    '                    const netFut = (r.fut_idx_long || 0) - (r.fut_idx_short || 0);',
    '                    const netOpt = (r.opt_idx_call_long || 0) - (r.opt_idx_call_short || 0)',
    '                               + (r.opt_idx_put_long  || 0) - (r.opt_idx_put_short  || 0);',
    '                    return (',
    '                      <tr key={r.category} style={{ background: i%2===0?"transparent":"var(--surface)88" }}>',
    '                        <td style={{ ...S.td, fontWeight: 600, color: "var(--accent)" }}>{r.category}</td>',
    '                        <td style={S.tdr}>{fmtK(r.fut_idx_long)}</td>',
    '                        <td style={S.tdr}>{fmtK(r.fut_idx_short)}</td>',
    '                        <td style={{ ...S.tdr, color: netFut >= 0 ? "var(--bull)" : "var(--bear)", fontWeight: 700 }}>',
    '                          {netFut >= 0 ? "+" : ""}{fmtK(netFut)}',
    '                        </td>',
    '                        <td style={S.tdr}>{fmtK(r.opt_idx_call_long)}</td>',
    '                        <td style={S.tdr}>{fmtK(r.opt_idx_put_long)}</td>',
    '                        <td style={{ ...S.tdr, color: netOpt >= 0 ? "var(--bull)" : "var(--bear)", fontWeight: 700 }}>',
    '                          {netOpt >= 0 ? "+" : ""}{fmtK(netOpt)}',
    '                        </td>',
    '                      </tr>',
    '                    );',
    '                  })}',
    '                  {(!data.participant_oi || data.participant_oi.length === 0) && (',
    '                    <tr><td colSpan={7} style={{ padding: 30, textAlign: "center", color: "var(--dim)" }}>',
    '                      No participant OI -- run: py D:\\MICC\\data_pipeline\\fetch_phase1_data.py --poi',
    '                    </td></tr>',
    '                  )}',
    '                </tbody>',
    '              </table>',
    '            </div>',
    '          )}',
    '',
    '          {/* Analysis */}',
    '          {tab === "analysis" && (',
    '            <div style={{ background: "var(--surface)", border: "1px solid var(--border)",',
    '              borderRadius: 8, padding: "20px" }}>',
    '              <div style={{ fontSize: 10, color: "var(--dim)", letterSpacing: 1, marginBottom: 12 }}>',
    '                MARKET STRUCTURE ANALYSIS',
    '              </div>',
    '              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>',
    '                <div>',
    '                  <div style={{ fontSize: 11, color: "var(--dim)", marginBottom: 8 }}>PCR INTERPRETATION</div>',
    '                  <div style={{ fontSize: 13, color: pcrColor, fontWeight: 600, marginBottom: 4 }}>',
    '                    {pcrLabel}',
    '                  </div>',
    '                  <div style={{ fontSize: 11, color: "var(--text)", lineHeight: 1.8 }}>',
    '                    {pcr == null ? "No data" :',
    '                      pcr > 1.5 ? "Heavy put buying -- strong bullish hedging, potential reversal zone." :',
    '                      pcr > 1.3 ? "Put-heavy positioning -- markets expect support, mild bullish bias." :',
    '                      pcr < 0.7 ? "Call-heavy positioning -- complacency or bearish outlook from market." :',
    '                      pcr < 0.5 ? "Extreme call buying -- bearish signal, watch for reversal." :',
    '                      "Balanced PCR -- no clear directional bias from options market."',
    '                    }',
    '                  </div>',
    '                </div>',
    '                <div>',
    '                  <div style={{ fontSize: 11, color: "var(--dim)", marginBottom: 8 }}>MAX PAIN ANALYSIS</div>',
    '                  <div style={{ fontSize: 13, color: "var(--accent)", fontWeight: 600, marginBottom: 4 }}>',
    '                    {data.max_pain ? Number(data.max_pain).toLocaleString("en-IN") : "--"}',
    '                  </div>',
    '                  <div style={{ fontSize: 11, color: "var(--text)", lineHeight: 1.8 }}>',
    '                    {data.max_pain && data.nifty_close',
    '                      ? `Spot is ${Number(data.nifty_close) > data.max_pain ? "ABOVE" : "BELOW"} max pain by `',
    '                        + `${Math.abs(Number(data.nifty_close) - data.max_pain).toFixed(0)} points. `',
    '                        + (Math.abs(Number(data.nifty_close) - data.max_pain) > 200',
    '                            ? "Expect gravitational pull toward max pain near expiry."',
    '                            : "Near max pain -- low directional conviction from options market.")',
    '                      : "No data"',
    '                    }',
    '                  </div>',
    '                </div>',
    '              </div>',
    '            </div>',
    '          )}',
    '        </>}',
    '      </div>',
    '    </div>',
    '  );',
    '}',
]

write(APP / "options" / "page.tsx", options_page_lines, "/options/page.tsx")

# /api/options/route.ts — reads fo_data + participant_oi
options_api_lines = [
    'import { NextResponse } from "next/server";',
    'import Database from "better-sqlite3";',
    '',
    'const DB = "D:/marketDB/db/market.db";',
    '',
    'function safeDb<T>(fn: (db: ReturnType<typeof Database>) => T, fallback: T): T {',
    '  let db: ReturnType<typeof Database> | null = null;',
    '  try {',
    '    db = new Database(DB, { readonly: true, timeout: 8000 });',
    '    return fn(db);',
    '  } catch { return fallback; }',
    '  finally { try { db?.close(); } catch {} }',
    '}',
    '',
    'export function GET() {',
    '  const result: Record<string, unknown> = {};',
    '',
    '  // Latest date + nearest expiry',
    '  const dateRow = safeDb(db => db.prepare(',
    '    "SELECT MAX(date) AS d FROM fo_data WHERE symbol=\'NIFTY\'"',
    '  ).get() as { d: string } | undefined, undefined);',
    '  const latestDate = dateRow?.d ?? "";',
    '  result.latest_date = latestDate;',
    '',
    '  if (!latestDate) {',
    '    return NextResponse.json({ ...result, error: "No fo_data found" });',
    '  }',
    '',
    '  const expiryRow = safeDb(db => db.prepare(',
    '    "SELECT MIN(expiry) AS e FROM fo_data"',
    '    " WHERE symbol=\'NIFTY\' AND date=? AND expiry>=?"',
    '  ).get(latestDate, latestDate) as { e: string } | undefined, undefined);',
    '  const expiry = expiryRow?.e ?? "";',
    '  result.expiry = expiry;',
    '',
    '  // Nifty spot from market_snapshot',
    '  const spotRow = safeDb(db => db.prepare(',
    '    "SELECT closing_index_value FROM market_snapshot"',
    '    " WHERE index_name=\'Nifty 50\' ORDER BY date DESC LIMIT 1"',
    '  ).get() as { closing_index_value: number } | undefined, undefined);',
    '  result.nifty_close = spotRow?.closing_index_value;',
    '  result.spot        = spotRow?.closing_index_value;',
    '',
    '  // PCR + Max Pain',
    '  const pcrRow = safeDb(db => db.prepare(',
    '    "SELECT"',
    '    "  ROUND(CAST(SUM(CASE WHEN option_typ=\'PE\' THEN open_int ELSE 0 END) AS REAL)"',
    '    "       /NULLIF(SUM(CASE WHEN option_typ=\'CE\' THEN open_int ELSE 0 END),0),2) AS pcr,"',
    '    "  SUM(CASE WHEN option_typ=\'CE\' THEN open_int ELSE 0 END) AS total_call_oi,"',
    '    "  SUM(CASE WHEN option_typ=\'PE\' THEN open_int ELSE 0 END) AS total_put_oi"',
    '    " FROM fo_data"',
    '    " WHERE symbol=\'NIFTY\' AND date=? AND expiry=?"',
    '    " AND instrument IN (\'OPTIDX\',\'IDO\')"',
    '  ).get(latestDate, expiry) as Record<string,number> | undefined, undefined);',
    '  result.pcr            = pcrRow?.pcr;',
    '  result.total_call_oi  = pcrRow?.total_call_oi;',
    '  result.total_put_oi   = pcrRow?.total_put_oi;',
    '',
    '  // Max pain strike',
    '  const strikes = safeDb(db => db.prepare(',
    '    "SELECT strike,"',
    '    "  SUM(CASE WHEN option_typ=\'CE\' THEN open_int ELSE 0 END) AS call_oi,"',
    '    "  SUM(CASE WHEN option_typ=\'PE\' THEN open_int ELSE 0 END) AS put_oi,"',
    '    "  SUM(CASE WHEN option_typ=\'CE\' THEN volume    ELSE 0 END) AS call_vol,"',
    '    "  SUM(CASE WHEN option_typ=\'PE\' THEN volume    ELSE 0 END) AS put_vol"',
    '    " FROM fo_data"',
    '    " WHERE symbol=\'NIFTY\' AND date=? AND expiry=?"',
    '    " AND instrument IN (\'OPTIDX\',\'IDO\')"',
    '    " GROUP BY strike ORDER BY strike"',
    '  ).all(latestDate, expiry) as { strike: number; call_oi: number; put_oi: number;',
    '    call_vol: number; put_vol: number }[], []);',
    '',
    '  // Compute max pain',
    '  let maxPain = 0, minPain = Infinity;',
    '  for (const row of strikes) {',
    '    const s = row.strike;',
    '    let pain = 0;',
    '    for (const r2 of strikes) {',
    '      if (r2.strike > s) pain += r2.call_oi * (r2.strike - s);',
    '      if (r2.strike < s) pain += r2.put_oi  * (s - r2.strike);',
    '    }',
    '    if (pain < minPain) { minPain = pain; maxPain = s; }',
    '  }',
    '  result.max_pain = maxPain || null;',
    '  result.strikes  = strikes;',
    '',
    '  // ATM IV from options_iv_history',
    '  const ivRow = safeDb(db => {',
    '    try {',
    '      return db.prepare(',
    '        "SELECT atm_iv, iv_rank FROM options_iv_history"',
    '        " WHERE symbol=\'NIFTY\' ORDER BY date DESC LIMIT 1"',
    '      ).get() as { atm_iv: number; iv_rank: number } | undefined;',
    '    } catch { return undefined; }',
    '  }, undefined);',
    '  result.atm_iv  = ivRow?.atm_iv;',
    '  result.iv_rank = ivRow?.iv_rank;',
    '',
    '  // Participant OI',
    '  const partOI = safeDb(db => {',
    '    try {',
    '      return db.prepare(',
    '        "SELECT * FROM participant_oi"',
    '        " WHERE date=(SELECT MAX(date) FROM participant_oi)"',
    '        " ORDER BY category"',
    '      ).all();',
    '    } catch { return []; }',
    '  }, []);',
    '  result.participant_oi = partOI;',
    '',
    '  return NextResponse.json(result);',
    '}',
]

write(APP / "api" / "options" / "route.ts", options_api_lines, "/api/options/route.ts")


# =============================================================================
# Summary
# =============================================================================
print()
print("=" * 60)
print("PHASE 4 COMPLETE")
print("=" * 60)
print()
print("Files written:")
print("  D:\\MICC\\agent_hmm.py                  -- HMM 3-state regime model")
print("  D:\\MICC\\micc-dashboard\\...fusion\\page.tsx -- full drilldown UI")
print("  D:\\MICC\\micc-dashboard\\...api\\fusion   -- reads last_report.json")
print("  D:\\MICC\\micc-dashboard\\...options\\page.tsx -- PCR+MaxPain+ParticipantOI")
print("  D:\\MICC\\micc-dashboard\\...api\\options  -- reads fo_data+participant_oi")
print()
print("Run HMM (one-time setup, ~2 min):")
print("  py D:\\MICC\\agent_hmm.py")
print("  Should show: BULL/BEAR/SIDEWAYS with confidence %")
print()
print("Add to daily pipeline (after daily_update.py):")
print("  py D:\\MICC\\agent_hmm.py")
print()
print("Add to run_pipeline.py phase list:")
print("  'hmm_regime': ('agent_hmm.py', 'HMM Regime Update')")
print()
print("Git push:")
print("  py D:\\MICC\\git_push_phase3.py")
