# Auto-generated by micc_full_audit.py
# Review before running!
import os
from pathlib import Path

MICC = Path(r'D:\MICC')
to_delete = [
    'build_seasonality_v2.py',
    'build_seasonality_v3.py',
    'fix_phase29.py',
    'fix_seasonality_v3.py',
    'fix_seasonality_v3c.py',
    'fix_seasonality_v3b.py',
]

for name in to_delete:
    p = MICC / name
    if p.exists():
        p.unlink()
        print(f'Deleted: {name}')
    else:
        print(f'Not found: {name}')
print(f'Done. Deleted {len(to_delete)} files.')