"""
fix_phase4_5_errors.py
======================
Fix 1: agent_hmm.py     -- hmmlearn needs MSVC, replace with pure-numpy Baum-Welch
Fix 2: train_conviction_xgb.py -- forward_return_5d -> fwd_5d,
                                   add column + compute from parquet if missing

Run: py D:\MICC\fix_phase4_5_errors.py
"""
from pathlib import Path

MICC = Path(r"D:\MICC")

def write(path, lines, label=""):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  [OK] {label or path.name}  ({len(lines)} lines)")

def log(msg):
    from datetime import datetime
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)

print("=" * 60)
print("FIX PHASE 4+5 ERRORS")
print("=" * 60)


# =============================================================================
# FIX 1: agent_hmm.py — pure numpy Gaussian HMM (no C extension needed)
# =============================================================================
log("[1/2] Rewriting agent_hmm.py (pure numpy, no hmmlearn)...")

hmm_lines = [
    '"""',
    'agent_hmm.py  --  HMM Regime Detection (pure numpy, no hmmlearn)',
    '3-state Gaussian HMM on Nifty50 log returns via Baum-Welch EM.',
    'States auto-labelled: BULL / SIDEWAYS / BEAR by mean return.',
    'Saves hmm_regime_daily table + agents/hmm/last_report.json',
    '',
    'Run: py D:\\MICC\\agent_hmm.py [--send]',
    '"""',
    'import sys, sqlite3, json',
    'from pathlib import Path',
    'from datetime import datetime',
    '',
    'try:',
    '    import numpy as np',
    'except ImportError:',
    '    import subprocess',
    '    subprocess.run([sys.executable, "-m", "pip", "install", "numpy",',
    '                    "--break-system-packages", "-q"])',
    '    import numpy as np',
    '',
    'DA      = Path(r"D:\\MICC")',
    'DB_PATH = r"D:\\marketDB\\db\\market.db"',
    'send    = "--send" in sys.argv',
    '',
    'def log(msg): print(f"  {msg}", flush=True)',
    '',
    'print("Agent HMM -- Regime Detection (pure numpy)")',
    'print("=" * 45)',
    '',
    '# ── Load Nifty50 returns ──────────────────────────────────────────────────',
    'def load_returns():',
    '    conn = sqlite3.connect(DB_PATH, timeout=15)',
    '    rows = conn.execute(',
    '        "SELECT date, close FROM global_indices_daily"',
    '        " WHERE symbol=\'NIFTY50\' ORDER BY date ASC"',
    '    ).fetchall()',
    '    if not rows:',
    '        rows = conn.execute(',
    '            "SELECT date, closing_index_value FROM market_snapshot"',
    '            " WHERE index_name=\'Nifty 50\' ORDER BY date ASC"',
    '        ).fetchall()',
    '    conn.close()',
    '    if len(rows) < 100:',
    '        raise ValueError(f"Only {len(rows)} rows -- need 100+")',
    '    dates  = [r[0] for r in rows]',
    '    closes = np.array([float(r[1]) for r in rows])',
    '    rets   = np.diff(np.log(closes))',
    '    return dates[1:], rets',
    '',
    '# ── Pure-numpy Gaussian HMM via Baum-Welch ────────────────────────────────',
    'class GaussianHMM:',
    '    """3-state Gaussian HMM, fits with EM (Baum-Welch)."""',
    '    def __init__(self, n=3, n_iter=100, tol=1e-4, seed=42):',
    '        self.n = n',
    '        self.n_iter = n_iter',
    '        self.tol = tol',
    '        rng = np.random.default_rng(seed)',
    '        # Init params',
    '        self.pi  = np.ones(n) / n                    # start probs',
    '        self.A   = rng.dirichlet(np.ones(n), size=n) # transition',
    '        self.mu  = rng.normal(0, 0.01, n)            # means',
    '        self.sig = np.full(n, 0.01)                  # stds',
    '',
    '    def _emit(self, x):',
    '        """Emission probabilities: (T, n)"""',
    '        eps = 1e-300',
    '        B = np.zeros((len(x), self.n))',
    '        for k in range(self.n):',
    '            s = max(self.sig[k], 1e-6)',
    '            B[:, k] = (np.exp(-0.5 * ((x - self.mu[k]) / s) ** 2)',
    '                       / (s * np.sqrt(2 * np.pi)) + eps)',
    '        return B',
    '',
    '    def _forward(self, B):',
    '        T = len(B)',
    '        alpha = np.zeros((T, self.n))',
    '        alpha[0] = self.pi * B[0]',
    '        scale = np.zeros(T)',
    '        scale[0] = alpha[0].sum() or 1e-300',
    '        alpha[0] /= scale[0]',
    '        for t in range(1, T):',
    '            alpha[t] = (alpha[t-1] @ self.A) * B[t]',
    '            scale[t] = alpha[t].sum() or 1e-300',
    '            alpha[t] /= scale[t]',
    '        return alpha, scale',
    '',
    '    def _backward(self, B, scale):',
    '        T = len(B)',
    '        beta = np.zeros((T, self.n))',
    '        beta[-1] = 1.0',
    '        for t in range(T-2, -1, -1):',
    '            beta[t] = (self.A @ (B[t+1] * beta[t+1])) / scale[t+1]',
    '        return beta',
    '',
    '    def fit(self, x):',
    '        prev_ll = -np.inf',
    '        for it in range(self.n_iter):',
    '            B = self._emit(x)',
    '            alpha, scale = self._forward(B)',
    '            beta  = self._backward(B, scale)',
    '            gamma = alpha * beta',
    '            gamma /= gamma.sum(axis=1, keepdims=True) + 1e-300',
    '            # xi: (T-1, n, n)',
    '            T = len(x)',
    '            xi = np.zeros((T-1, self.n, self.n))',
    '            for t in range(T-1):',
    '                xi[t] = (alpha[t:t+1].T * self.A',
    '                         * (B[t+1] * beta[t+1]))',
    '                xi[t] /= xi[t].sum() + 1e-300',
    '            # Update',
    '            self.pi = gamma[0] / gamma[0].sum()',
    '            self.A  = xi.sum(0) / (xi.sum(0).sum(1, keepdims=True) + 1e-300)',
    '            self.mu  = (gamma * x[:,None]).sum(0) / (gamma.sum(0) + 1e-300)',
    '            var = (gamma * (x[:,None] - self.mu)**2).sum(0) / (gamma.sum(0) + 1e-300)',
    '            self.sig = np.sqrt(var) + 1e-6',
    '            ll = np.log(scale + 1e-300).sum()',
    '            if abs(ll - prev_ll) < self.tol:',
    '                log(f"  Converged at iter {it+1}  LL={ll:.2f}")',
    '                break',
    '            prev_ll = ll',
    '        self._gamma = gamma',
    '        return self',
    '',
    '    def predict(self, x):',
    '        B = self._emit(x)',
    '        alpha, scale = self._forward(B)',
    '        beta = self._backward(B, scale)',
    '        gamma = alpha * beta',
    '        gamma /= gamma.sum(axis=1, keepdims=True) + 1e-300',
    '        return gamma.argmax(axis=1), gamma',
    '',
    '# ── Fit + label ───────────────────────────────────────────────────────────',
    'try:',
    '    dates, rets = load_returns()',
    '    log(f"Loaded {len(rets)} Nifty returns ({dates[0]} to {dates[-1]})")',
    '',
    '    model = GaussianHMM(n=3, n_iter=200, tol=1e-5)',
    '    model.fit(rets)',
    '',
    '    # Assign labels: sort states by mean return',
    '    order = np.argsort(model.mu)   # [lowest_mean, mid, highest_mean]',
    '    label_map = {int(order[0]): "BEAR", int(order[1]): "SIDEWAYS", int(order[2]): "BULL"}',
    '',
    '    state_seq, gamma = model.predict(rets)',
    '    labels = [label_map[int(s)] for s in state_seq]',
    '',
    '    for i in range(3):',
    '        k    = int(order[i])',
    '        name = label_map[k]',
    '        mask = state_seq == k',
    '        log(f"  {name:<10} mu={model.mu[k]*100:+.3f}%  sig={model.sig[k]*100:.3f}%  days={mask.sum()}")',
    '',
    '    current_state = int(state_seq[-1])',
    '    current_regime = label_map[current_state]',
    '    current_probs  = gamma[-1]',
    '    bull_p = float(current_probs[int(order[2])])',
    '    side_p = float(current_probs[int(order[1])])',
    '    bear_p = float(current_probs[int(order[0])])',
    '    confidence = float(current_probs.max())',
    '',
    '    log(f"")',
    '    log(f"CURRENT: {current_regime}  (conf={confidence:.1%})")',
    '    log(f"  Bull={bull_p:.1%}  Side={side_p:.1%}  Bear={bear_p:.1%}")',
    '',
    '    # ── Save to DB ────────────────────────────────────────────────────────',
    '    conn = sqlite3.connect(DB_PATH, timeout=30)',
    '    conn.execute("PRAGMA journal_mode=WAL")',
    '    conn.execute(',
    '        "CREATE TABLE IF NOT EXISTS hmm_regime_daily"',
    '        " (date TEXT PRIMARY KEY, regime TEXT,"',
    '        "  bull_prob REAL, bear_prob REAL, sideways_prob REAL, updated_at TEXT)"',
    '    )',
    '    now_ts = datetime.now().isoformat()',
    '    batch = []',
    '    for i, (date, label) in enumerate(zip(dates, labels)):',
    '        g = gamma[i]',
    '        batch.append((',
    '            date, label,',
    '            round(float(g[int(order[2])]), 4),',
    '            round(float(g[int(order[0])]), 4),',
    '            round(float(g[int(order[1])]), 4),',
    '            now_ts',
    '        ))',
    '    conn.executemany(',
    '        "INSERT OR REPLACE INTO hmm_regime_daily"',
    '        " (date,regime,bull_prob,bear_prob,sideways_prob,updated_at)"',
    '        " VALUES (?,?,?,?,?,?)", batch)',
    '    conn.commit()',
    '    conn.close()',
    '    log(f"Saved {len(batch)} rows to hmm_regime_daily")',
    '',
    '    # ── Save JSON ─────────────────────────────────────────────────────────',
    '    out_dir = DA / "agents" / "hmm"',
    '    out_dir.mkdir(parents=True, exist_ok=True)',
    '    summary = {',
    '        "agent": "hmm", "date": datetime.now().strftime("%Y-%m-%d"),',
    '        "current_regime": current_regime, "confidence": round(confidence, 4),',
    '        "bull_prob": round(bull_p, 4), "sideways_prob": round(side_p, 4),',
    '        "bear_prob": round(bear_p, 4), "last_date": dates[-1], "n_days": len(dates),',
    '    }',
    '    (out_dir / "last_report.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")',
    '',
    '    print()',
    '    print(f"Current regime: {current_regime} ({confidence:.0%} confidence)")',
    '    print(f"Bull={bull_p:.0%}  Sideways={side_p:.0%}  Bear={bear_p:.0%}")',
    '',
    '    if send:',
    '        import re, urllib.request',
    '        env  = (DA / ".env").read_text()',
    '        BOT  = re.search(r"TELEGRAM_TOKEN=([^\\n]+)", env).group(1).strip()',
    '        CHAT = re.search(r"TELEGRAM_CHAT_ID=([^\\n]+)", env).group(1).strip()',
    '        ico  = {"BULL":"UP","BEAR":"DN","SIDEWAYS":"--"}[current_regime]',
    '        msg  = (f"HMM Regime\\n{ico} {current_regime} ({confidence:.0%})\\n"',
    '                f"Bull={bull_p:.0%} Side={side_p:.0%} Bear={bear_p:.0%}")',
    '        data = json.dumps({"chat_id":CHAT,"text":msg}).encode()',
    '        urllib.request.urlopen(',
    '            urllib.request.Request(',
    '                f"https://api.telegram.org/bot{BOT}/sendMessage",',
    '                data=data, headers={"Content-Type":"application/json"}',
    '            ), timeout=10)',
    '        print("  Telegram: OK")',
    '',
    'except Exception as e:',
    '    print(f"HMM failed: {e}")',
    '    import traceback; traceback.print_exc()',
]

write(MICC / "agent_hmm.py", hmm_lines, "agent_hmm.py")


# =============================================================================
# FIX 2: train_conviction_xgb.py
#   Bug A: column is fwd_5d not forward_return_5d
#   Bug B: if fwd_5d doesn't exist yet, add it + compute from parquet
# =============================================================================
log("[2/2] Rewriting train_conviction_xgb.py (fix column names)...")

xgb_lines = [
    '"""',
    'train_conviction_xgb.py  --  XGBoost conviction model',
    '',
    'Correct signals_history columns: fwd_1d, fwd_3d, fwd_5d, fwd_10d',
    'If fwd_5d is missing, runs oos_backtest.py first to fill it.',
    '',
    'Run: py D:\\MICC\\train_conviction_xgb.py',
    '     py D:\\MICC\\train_conviction_xgb.py --score',
    '"""',
    'import sys, sqlite3, json, subprocess',
    'from pathlib import Path',
    'from datetime import datetime',
    '',
    'DA      = Path(r"D:\\MICC")',
    'DB_PATH = r"D:\\marketDB\\db\\market.db"',
    'SCORE_ONLY = "--score" in sys.argv',
    '',
    'def log(msg): print(f"  {msg}", flush=True)',
    '',
    'try:',
    '    import xgboost as xgb',
    '    import numpy as np',
    '    import pandas as pd',
    '    from sklearn.metrics import roc_auc_score, accuracy_score',
    'except ImportError:',
    '    subprocess.run([sys.executable, "-m", "pip", "install",',
    '                    "xgboost", "scikit-learn", "numpy", "pandas",',
    '                    "--break-system-packages", "-q"])',
    '    import xgboost as xgb',
    '    import numpy as np',
    '    import pandas as pd',
    '    from sklearn.metrics import roc_auc_score, accuracy_score',
    '',
    'MODEL_PATH = DA / "conviction_xgb.json"',
    '',
    'FEATURES = [',
    '    "rsi_14", "adx_14", "atr_14_pct", "pct_above_sma20",',
    '    "vol_surge_20d", "delivery_pct",',
    '    "roce", "roe", "debt_equity", "pe_ratio",',
    '    "oos_accuracy", "score_v2_best",',
    '    "insider_buy_30d", "n_signals_30d",',
    ']',
    '',
    '# ── Ensure fwd_5d column exists in signals_history ───────────────────────',
    'def ensure_fwd_columns():',
    '    conn = sqlite3.connect(DB_PATH, timeout=30)',
    '    cols = {r[1] for r in conn.execute("PRAGMA table_info(signals_history)").fetchall()}',
    '    missing = [c for c in ["fwd_1d","fwd_3d","fwd_5d","fwd_10d"] if c not in cols]',
    '    for c in missing:',
    '        conn.execute(f"ALTER TABLE signals_history ADD COLUMN {c} REAL")',
    '        log(f"Added column: {c}")',
    '    conn.commit()',
    '    # Check how many fwd_5d are filled',
    '    n_filled = conn.execute(',
    '        "SELECT COUNT(*) FROM signals_history WHERE fwd_5d IS NOT NULL"',
    '    ).fetchone()[0]',
    '    n_total  = conn.execute("SELECT COUNT(*) FROM signals_history").fetchone()[0]',
    '    conn.close()',
    '    log(f"signals_history: {n_total} rows, {n_filled} with fwd_5d")',
    '    return n_filled, n_total',
    '',
    '# ── Compute fwd_5d from parquet if not filled ─────────────────────────────',
    'def compute_fwd_returns():',
    '    log("Computing forward returns from parquet (running oos_backtest --quick)...")',
    '    result = subprocess.run(',
    '        [sys.executable, str(DA / "oos_backtest.py"), "--quick"],',
    '        cwd=str(DA), capture_output=True, text=True, timeout=300',
    '    )',
    '    if result.returncode == 0:',
    '        log("  oos_backtest --quick: OK")',
    '    else:',
    '        log(f"  oos_backtest failed: {result.stderr[:200]}")',
    '        log("  Computing directly from parquet...")',
    '        _compute_fwd_direct()',
    '',
    'def _compute_fwd_direct():',
    '    """Compute fwd_5d directly from parquet files without oos_backtest."""',
    '    PARQUET = Path(r"D:\\marketDB\\stocks\\all")',
    '    conn = sqlite3.connect(DB_PATH, timeout=60)',
    '    conn.execute("PRAGMA journal_mode=WAL")',
    '    rows = conn.execute(',
    '        "SELECT rowid, symbol, run_date FROM signals_history"',
    '        " WHERE fwd_5d IS NULL ORDER BY run_date DESC LIMIT 5000"',
    '    ).fetchall()',
    '    log(f"  Computing fwd_5d for {len(rows)} signals...")',
    '    updated = 0',
    '    cache = {}',
    '    for rowid, sym, run_date in rows:',
    '        if sym not in cache:',
    '            # Try multiple parquet year files',
    '            closes = {}',
    '            for yr in range(2020, 2027):',
    '                p = PARQUET / sym / f"{sym}_{yr}.parquet"',
    '                if not p.exists(): continue',
    '                try:',
    '                    df = pd.read_parquet(p, columns=["date","close"])',
    '                    df["date"] = df["date"].astype(str)',
    '                    for _, r in df.iterrows():',
    '                        closes[r["date"]] = float(r["close"])',
    '                except Exception:',
    '                    pass',
    '            cache[sym] = closes',
    '        closes = cache[sym]',
    '        if not closes: continue',
    '        sorted_dates = sorted(closes.keys())',
    '        try:',
    '            idx = sorted_dates.index(run_date)',
    '        except ValueError:',
    '            # Find nearest date',
    '            nearest = min(sorted_dates, key=lambda d: abs(d.replace("-","") - run_date.replace("-","")) if d else 999999, default=None)',
    '            if not nearest: continue',
    '            idx = sorted_dates.index(nearest)',
    '        if idx + 5 >= len(sorted_dates): continue',
    '        p0 = closes[sorted_dates[idx]]',
    '        p5 = closes[sorted_dates[idx + 5]]',
    '        if p0 and p0 > 0:',
    '            fwd = (p5 - p0) / p0 * 100',
    '            conn.execute("UPDATE signals_history SET fwd_5d=? WHERE rowid=?", (round(fwd,4), rowid))',
    '            updated += 1',
    '    conn.commit()',
    '    conn.close()',
    '    log(f"  Updated fwd_5d for {updated} signals")',
    '',
    '# ── Load training data ────────────────────────────────────────────────────',
    'def load_training_data():',
    '    log("Loading training data...")',
    '    conn = sqlite3.connect(DB_PATH, timeout=30)',
    '    # Use correct column name fwd_5d',
    '    df = pd.read_sql(',
    '        "SELECT symbol, run_date, score, fwd_5d"',
    '        " FROM signals_history"',
    '        " WHERE fwd_5d IS NOT NULL"',
    '        " ORDER BY run_date DESC LIMIT 50000",',
    '        conn',
    '    )',
    '    log(f"  Training rows: {len(df)}")',
    '    if len(df) < 50:',
    '        conn.close()',
    '        raise ValueError(f"Only {len(df)} labeled signals -- run oos_backtest.py first")',
    '    # Technicals',
    '    tech = pd.read_sql(',
    '        "SELECT symbol, rsi_14, adx_14, atr_14_pct, pct_above_sma20, vol_surge_20d"',
    '        " FROM symbol_technicals", conn)',
    '    # Delivery',
    '    try:',
    '        deliv = pd.read_sql(',
    '            "SELECT symbol, AVG(CAST(delivery_pct AS REAL)) AS delivery_pct"',
    '            " FROM stock_delivery WHERE date >= date(\'now\',\'-30 days\')"',
    '            " GROUP BY symbol", conn)',
    '    except Exception:',
    '        deliv = pd.DataFrame(columns=["symbol","delivery_pct"])',
    '    # Fundamentals',
    '    try:',
    '        fund = pd.read_sql(',
    '            "SELECT symbol, roce, roe, debt_equity, pe_ratio"',
    '            " FROM screener_fundamentals_v2 WHERE scrape_ok=1", conn)',
    '    except Exception:',
    '        fund = pd.DataFrame(columns=["symbol","roce","roe","debt_equity","pe_ratio"])',
    '    # OOS accuracy',
    '    try:',
    '        oos = pd.read_sql(',
    '            "SELECT symbol,"',
    '            "  MAX(CAST(oos_accuracy AS REAL)) AS oos_accuracy,"',
    '            "  MAX(CAST(score_v2 AS REAL)) AS score_v2_best"',
    '            " FROM seasonality_patterns_v3"',
    '            " WHERE fdr_reject=1 AND (overfit=0 OR overfit IS NULL)"',
    '            "   AND oos_accuracy IS NOT NULL GROUP BY symbol", conn)',
    '    except Exception:',
    '        oos = pd.DataFrame(columns=["symbol","oos_accuracy","score_v2_best"])',
    '    # Insider buys',
    '    try:',
    '        ins = pd.read_sql(',
    '            "SELECT symbol, COUNT(*) AS insider_buy_30d"',
    '            " FROM insider_trading"',
    '            " WHERE transaction_type=\'BUY\'"',
    '            "   AND filing_date >= date(\'now\',\'-30 days\')"',
    '            " GROUP BY symbol", conn)',
    '    except Exception:',
    '        ins = pd.DataFrame(columns=["symbol","insider_buy_30d"])',
    '    # Signal count',
    '    sig_cnt = pd.read_sql(',
    '        "SELECT symbol, COUNT(*) AS n_signals_30d"',
    '        " FROM signals_history WHERE run_date >= date(\'now\',\'-30 days\')"',
    '        " GROUP BY symbol", conn)',
    '    conn.close()',
    '    # Merge',
    '    df = df.merge(tech,    on="symbol", how="left")',
    '    df = df.merge(deliv,   on="symbol", how="left")',
    '    df = df.merge(fund,    on="symbol", how="left")',
    '    df = df.merge(oos,     on="symbol", how="left")',
    '    df = df.merge(ins,     on="symbol", how="left")',
    '    df = df.merge(sig_cnt, on="symbol", how="left")',
    '    df["insider_buy_30d"] = df["insider_buy_30d"].fillna(0)',
    '    df["n_signals_30d"]   = df["n_signals_30d"].fillna(0)',
    '    df["oos_accuracy"]    = df["oos_accuracy"].fillna(0.5)',
    '    df["score_v2_best"]   = df["score_v2_best"].fillna(0)',
    '    df["label"] = (df["fwd_5d"] > 1.0).astype(int)',
    '    log(f"  Positive labels: {df[\'label\'].mean():.1%}  ({df[\'label\'].sum()} of {len(df)})")',
    '    return df',
    '',
    '# ── Train ─────────────────────────────────────────────────────────────────',
    'def train(df):',
    '    log("Training XGBoost...")',
    '    X = df[FEATURES].fillna(df[FEATURES].median())',
    '    y = df["label"]',
    '    split = int(len(df) * 0.8)',
    '    X_tr, X_te = X.iloc[:split], X.iloc[split:]',
    '    y_tr, y_te = y.iloc[:split], y.iloc[split:]',
    '    pos_weight = max(1.0, float((y_tr==0).sum()) / max(float((y_tr==1).sum()), 1))',
    '    model = xgb.XGBClassifier(',
    '        n_estimators=200, max_depth=4, learning_rate=0.05,',
    '        subsample=0.8, colsample_bytree=0.8,',
    '        scale_pos_weight=pos_weight,',
    '        eval_metric="logloss", random_state=42, verbosity=0',
    '    )',
    '    model.fit(X_tr, y_tr, eval_set=[(X_te, y_te)], verbose=False)',
    '    preds = model.predict_proba(X_te)[:,1]',
    '    auc   = roc_auc_score(y_te, preds)',
    '    acc   = accuracy_score(y_te, model.predict(X_te))',
    '    log(f"  AUC={auc:.3f}  Acc={acc:.1%}  Train={len(X_tr)}  Test={len(X_te)}")',
    '    imp = sorted(zip(FEATURES, model.feature_importances_), key=lambda x:-x[1])',
    '    log("  Top 5 features:")',
    '    for feat, score in imp[:5]:',
    '        log(f"    {feat:<22} {score:.3f}")',
    '    model.save_model(str(MODEL_PATH))',
    '    log(f"  Saved: {MODEL_PATH}")',
    '    return model, auc',
    '',
    '# ── Score universe ────────────────────────────────────────────────────────',
    'def score_universe(model):',
    '    log("Scoring current universe...")',
    '    conn = sqlite3.connect(DB_PATH, timeout=30)',
    '    tech = pd.read_sql(',
    '        "SELECT symbol, rsi_14, adx_14, atr_14_pct, pct_above_sma20, vol_surge_20d"',
    '        " FROM symbol_technicals", conn)',
    '    dfs  = [tech]',
    '    for sql, cols in [',
    '        ("SELECT symbol, AVG(CAST(delivery_pct AS REAL)) AS delivery_pct"',
    '         " FROM stock_delivery WHERE date>=date(\'now\',\'-30 days\') GROUP BY symbol",',
    '         ["symbol","delivery_pct"]),',
    '        ("SELECT symbol, roce, roe, debt_equity, pe_ratio"',
    '         " FROM screener_fundamentals_v2 WHERE scrape_ok=1",',
    '         ["symbol","roce","roe","debt_equity","pe_ratio"]),',
    '    ]:',
    '        try:',
    '            dfs.append(pd.read_sql(sql, conn))',
    '        except Exception:',
    '            dfs.append(pd.DataFrame(columns=cols))',
    '    try:',
    '        dfs.append(pd.read_sql(',
    '            "SELECT symbol, MAX(CAST(oos_accuracy AS REAL)) AS oos_accuracy,"',
    '            " MAX(CAST(score_v2 AS REAL)) AS score_v2_best"',
    '            " FROM seasonality_patterns_v3"',
    '            " WHERE fdr_reject=1 AND (overfit=0 OR overfit IS NULL)"',
    '            "   AND oos_accuracy IS NOT NULL GROUP BY symbol", conn))',
    '    except Exception:',
    '        dfs.append(pd.DataFrame(columns=["symbol","oos_accuracy","score_v2_best"]))',
    '    try:',
    '        dfs.append(pd.read_sql(',
    '            "SELECT symbol, COUNT(*) AS insider_buy_30d FROM insider_trading"',
    '            " WHERE transaction_type=\'BUY\' AND filing_date>=date(\'now\',\'-30 days\')"',
    '            " GROUP BY symbol", conn))',
    '    except Exception:',
    '        dfs.append(pd.DataFrame(columns=["symbol","insider_buy_30d"]))',
    '    dfs.append(pd.read_sql(',
    '        "SELECT symbol, COUNT(*) AS n_signals_30d FROM signals_history"',
    '        " WHERE run_date>=date(\'now\',\'-30 days\') GROUP BY symbol", conn))',
    '    conn.close()',
    '    df = dfs[0]',
    '    for other in dfs[1:]:',
    '        df = df.merge(other, on="symbol", how="left")',
    '    df["insider_buy_30d"] = df.get("insider_buy_30d", pd.Series(0, index=df.index)).fillna(0)',
    '    df["n_signals_30d"]   = df.get("n_signals_30d",   pd.Series(0, index=df.index)).fillna(0)',
    '    df["oos_accuracy"]    = df.get("oos_accuracy",    pd.Series(0.5, index=df.index)).fillna(0.5)',
    '    df["score_v2_best"]   = df.get("score_v2_best",   pd.Series(0, index=df.index)).fillna(0)',
    '    X    = df[FEATURES].fillna(df[FEATURES].median())',
    '    prob = model.predict_proba(X)[:,1]',
    '    df["xgb_score"] = (prob * 100).round(1)',
    '    conn2 = sqlite3.connect(DB_PATH, timeout=30)',
    '    conn2.execute("PRAGMA journal_mode=WAL")',
    '    conn2.execute(',
    '        "CREATE TABLE IF NOT EXISTS symbol_conviction_xgb"',
    '        " (symbol TEXT PRIMARY KEY, xgb_score REAL, updated_at TEXT)")',
    '    now_ts = datetime.now().isoformat()',
    '    batch = [(r.symbol, r.xgb_score, now_ts) for _, r in df.iterrows()]',
    '    conn2.executemany(',
    '        "INSERT OR REPLACE INTO symbol_conviction_xgb (symbol,xgb_score,updated_at)"',
    '        " VALUES (?,?,?)", batch)',
    '    conn2.commit()',
    '    conn2.close()',
    '    top = df.nlargest(10, "xgb_score")[["symbol","xgb_score"]]',
    '    log(f"Saved {len(batch)} XGB scores.  Top 10:")',
    '    for _, r in top.iterrows():',
    '        log(f"  {r.symbol:<15} {r.xgb_score:.1f}")',
    '    return df',
    '',
    '# ── Main ──────────────────────────────────────────────────────────────────',
    'print("XGBoost Conviction Model")',
    'print("=" * 40)',
    '',
    '# Step 0: ensure fwd columns exist + are populated',
    'n_filled, n_total = ensure_fwd_columns()',
    'if n_filled < 50 and not SCORE_ONLY:',
    '    log(f"Only {n_filled} labeled signals -- running oos_backtest to fill...")',
    '    compute_fwd_returns()',
    '    n_filled, _ = ensure_fwd_columns()',
    '    log(f"After fill: {n_filled} labeled signals")',
    '',
    'if SCORE_ONLY and MODEL_PATH.exists():',
    '    log("Loading existing model...")',
    '    model = xgb.XGBClassifier()',
    '    model.load_model(str(MODEL_PATH))',
    '    score_universe(model)',
    'else:',
    '    try:',
    '        df = load_training_data()',
    '        model, auc = train(df)',
    '        score_universe(model)',
    '        print(f"\\nDone. AUC={auc:.3f}. Scores in symbol_conviction_xgb.")',
    '    except Exception as e:',
    '        print(f"Error: {e}")',
    '        import traceback; traceback.print_exc()',
]

write(MICC / "train_conviction_xgb.py", xgb_lines, "train_conviction_xgb.py")


print()
print("=" * 60)
print("FIXES DONE")
print("=" * 60)
print()
print("Run HMM (no compiler needed, pure numpy):")
print("  py D:\\MICC\\agent_hmm.py")
print("  Expected: BULL/BEAR/SIDEWAYS + confidence %")
print()
print("Run XGBoost (auto-fills fwd_5d if missing):")
print("  py D:\\MICC\\train_conviction_xgb.py")
print("  Expected: AUC=0.55-0.65, top 10 stocks scored")
print()
print("Git push:")
print("  py D:\\MICC\\git_push_phase3.py")
