#!/usr/bin/env python3
"""
fix_phase29_30.py - Fix all issues from Phase 29/30
====================================================
Fixes:
  1. conviction/portfolio pages in wrong dir -> copy to correct src/app path
  2. eta/page.tsx literal \\n compile error -> rewrite clean
  3. conviction/portfolio pages rewritten with MICC terminal aesthetic

Run: python fix_phase29_30.py
Location: D:/MICC/fix_phase29_30.py
"""

from pathlib import Path
import shutil

MICC = Path("D:/MICC")
DASH = MICC / "micc-dashboard"
SRC  = DASH / "src" / "app"

def write(path, lines, label):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    print("  [OK] " + label + " (" + str(len(lines)) + " lines)")

def log(msg):
    from datetime import datetime
    print("[" + datetime.now().strftime("%H:%M:%S") + "] " + msg, flush=True)


# =============================================================================
# [1] FIX eta/page.tsx compile error
# =============================================================================
log("[1/3] Fixing eta/page.tsx compile error...")

eta_path = SRC / "eta" / "page.tsx"
if eta_path.exists():
    raw = eta_path.read_text(encoding="utf-8")
    # Fix literal \n written as text
    if "\\n" in raw and "\\nimport" in raw:
        fixed = raw.replace("\\nimport", "\nimport").replace("\\n", "\n")
        eta_path.write_text(fixed, encoding="utf-8")
        log("  Fixed literal \\n in eta/page.tsx")
    else:
        # Rewrite with minimal clean page to unblock compilation
        eta_lines = [
            '"use client";',
            'import { useEffect, useState } from "react";',
            '',
            'interface ResultItem { symbol: string; date: string; subject: string; }',
            'interface InsiderCluster { symbol: string; count: number; total_value: number; }',
            'interface BigTrade { symbol: string; name: string; transaction_type: string; value: number; filing_date: string; }',
            '',
            'export default function EtaPage() {',
            '  const [data, setData] = useState<any>(null);',
            '  const [loading, setLoading] = useState(true);',
            '  const [error, setError] = useState("");',
            '  const [tab, setTab] = useState(0);',
            '',
            '  useEffect(() => {',
            '    fetch("/api/eta")',
            '      .then(r => r.json())',
            '      .then(d => { setData(d); setLoading(false); })',
            '      .catch(e => { setError(e.message); setLoading(false); });',
            '  }, []);',
            '',
            '  const tabs = ["Results", "Dividends", "Insider Clusters", "Big Trades", "Announcements", "Summary"];',
            '',
            '  return (',
            '    <div style={{minHeight:"100vh",background:"#0a0a0a",color:"#e2e8f0",fontFamily:"\'Courier New\',monospace",padding:"24px"}}>',
            '      <div style={{borderBottom:"1px solid #1e3a5f",paddingBottom:16,marginBottom:24}}>',
            '        <div style={{color:"#60a5fa",fontSize:11,letterSpacing:3,marginBottom:4}}>AGENT ETA</div>',
            '        <h1 style={{margin:0,fontSize:20,fontWeight:700,color:"#f9fafb"}}>CORPORATE EVENTS INTELLIGENCE</h1>',
            '        <div style={{color:"#4b5563",fontSize:11,marginTop:4}}>Results · Dividends · Insider Clusters · Big Trades</div>',
            '      </div>',
            '      <div style={{display:"flex",gap:4,marginBottom:20,flexWrap:"wrap"}}>',
            '        {tabs.map((t,i) => (',
            '          <button key={t} onClick={() => setTab(i)} style={{',
            '            background: tab===i ? "#1e3a5f" : "transparent",',
            '            color: tab===i ? "#60a5fa" : "#4b5563",',
            '            border: "1px solid " + (tab===i ? "#1e3a5f" : "#1f2937"),',
            '            borderRadius:4, padding:"5px 14px", fontSize:11,',
            '            cursor:"pointer", letterSpacing:1, fontFamily:"inherit",',
            '          }}>S{i+1}: {t.toUpperCase()}</button>',
            '        ))}',
            '      </div>',
            '      {loading && <div style={{color:"#4b5563",fontSize:13}}>Loading corporate events...</div>}',
            '      {error && <div style={{color:"#ef4444",fontSize:12}}>ERROR: {error}</div>}',
            '      {!loading && !error && data && (',
            '        <div>',
            '          {tab === 0 && <EventTable title="RECENT RESULTS" rows={data.results || []} cols={["symbol","date","subject"]} />}',
            '          {tab === 1 && <EventTable title="DIVIDENDS" rows={data.dividends || []} cols={["symbol","date","subject"]} />}',
            '          {tab === 2 && <ClusterTable rows={data.insider_clusters || []} />}',
            '          {tab === 3 && <BigTradeTable rows={data.big_trades || []} />}',
            '          {tab === 4 && <EventTable title="ANNOUNCEMENTS" rows={data.announcements || []} cols={["symbol","date","subject"]} />}',
            '          {tab === 5 && <SummaryView data={data} />}',
            '        </div>',
            '      )}',
            '    </div>',
            '  );',
            '}',
            '',
            'function EventTable({title, rows, cols}: {title:string; rows:any[]; cols:string[]}) {',
            '  return <div>',
            '    <div style={{color:"#4b5563",fontSize:10,letterSpacing:2,marginBottom:12}}>{title} -- {rows.length} ITEMS</div>',
            '    <table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}>',
            '      <thead><tr>{cols.map(c => <th key={c} style={{textAlign:"left",padding:"6px 12px",color:"#4b5563",fontSize:10,letterSpacing:1,borderBottom:"1px solid #1f2937"}}>{c.toUpperCase()}</th>)}</tr></thead>',
            '      <tbody>{rows.map((r,i) => <tr key={i} style={{borderBottom:"1px solid #111"}}>{cols.map(c => <td key={c} style={{padding:"7px 12px",color:c==="symbol"?"#60a5fa":"#9ca3af"}}>{r[c]}</td>)}</tr>)}</tbody>',
            '    </table>',
            '    {rows.length === 0 && <div style={{color:"#374151",fontSize:12,padding:"20px 0"}}>No data.</div>}',
            '  </div>;',
            '}',
            '',
            'function ClusterTable({rows}: {rows:any[]}) {',
            '  return <div>',
            '    <div style={{color:"#4b5563",fontSize:10,letterSpacing:2,marginBottom:12}}>INSIDER BUY CLUSTERS -- {rows.length} SYMBOLS</div>',
            '    <table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}>',
            '      <thead><tr>{["SYMBOL","BUY COUNT","TOTAL VALUE (CR)"].map(h => <th key={h} style={{textAlign:"left",padding:"6px 12px",color:"#4b5563",fontSize:10,letterSpacing:1,borderBottom:"1px solid #1f2937"}}>{h}</th>)}</tr></thead>',
            '      <tbody>{rows.map((r,i) => <tr key={i} style={{borderBottom:"1px solid #111"}}>',
            '        <td style={{padding:"7px 12px",color:"#60a5fa"}}>{r.symbol}</td>',
            '        <td style={{padding:"7px 12px",color:"#10b981"}}>{r.count}</td>',
            '        <td style={{padding:"7px 12px",color:"#f59e0b"}}>{r.total_value ? (r.total_value/1e7).toFixed(2) : "–"}</td>',
            '      </tr>)}',
            '      </tbody>',
            '    </table>',
            '  </div>;',
            '}',
            '',
            'function BigTradeTable({rows}: {rows:any[]}) {',
            '  return <div>',
            '    <div style={{color:"#4b5563",fontSize:10,letterSpacing:2,marginBottom:12}}>BIG INSIDER TRADES -- {rows.length} TRADES</div>',
            '    <table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}>',
            '      <thead><tr>{["SYMBOL","NAME","TYPE","VALUE (CR)","DATE"].map(h => <th key={h} style={{textAlign:"left",padding:"6px 12px",color:"#4b5563",fontSize:10,letterSpacing:1,borderBottom:"1px solid #1f2937"}}>{h}</th>)}</tr></thead>',
            '      <tbody>{rows.map((r,i) => <tr key={i} style={{borderBottom:"1px solid #111"}}>',
            '        <td style={{padding:"7px 12px",color:"#60a5fa"}}>{r.symbol}</td>',
            '        <td style={{padding:"7px 12px",color:"#9ca3af"}}>{r.name}</td>',
            '        <td style={{padding:"7px 12px",color:r.transaction_type==="BUY"?"#10b981":"#ef4444"}}>{r.transaction_type}</td>',
            '        <td style={{padding:"7px 12px",color:"#f59e0b"}}>{r.value ? (r.value/1e7).toFixed(2) : "–"}</td>',
            '        <td style={{padding:"7px 12px",color:"#4b5563"}}>{r.filing_date}</td>',
            '      </tr>)}',
            '      </tbody>',
            '    </table>',
            '  </div>;',
            '}',
            '',
            'function SummaryView({data}: {data:any}) {',
            '  const summary = data.summary || {};',
            '  const items = Object.entries(summary);',
            '  return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:12}}>',
            '    {items.map(([k,v]) => (',
            '      <div key={k} style={{background:"#0f1923",border:"1px solid #1e3a5f",borderRadius:6,padding:"12px 16px"}}>',
            '        <div style={{color:"#4b5563",fontSize:10,letterSpacing:1}}>{k.toUpperCase()}</div>',
            '        <div style={{color:"#60a5fa",fontSize:16,fontWeight:700,marginTop:4}}>{String(v)}</div>',
            '      </div>',
            '    ))}',
            '    {items.length===0 && <div style={{color:"#374151"}}>No summary data.</div>}',
            '  </div>;',
            '}',
        ]
        write(eta_path, eta_lines, "eta/page.tsx (rewritten)")
else:
    log("  eta/page.tsx not found — creating minimal version")
    eta_lines = [
        '"use client";',
        'export default function EtaPage() {',
        '  return <div style={{padding:40,color:"#9ca3af",fontFamily:"monospace"}}>ETA page — run agent_eta.py first</div>;',
        '}',
    ]
    write(eta_path, eta_lines, "eta/page.tsx (stub)")


# =============================================================================
# [2] FIX conviction page - correct path + MICC terminal aesthetic
# =============================================================================
log("[2/3] Writing conviction page to correct path...")

conviction_lines = [
    '"use client";',
    'import { useEffect, useState, useMemo } from "react";',
    '',
    'interface Row {',
    '  symbol: string; score: number|null;',
    '  momentum: number|null; seasonality: number|null; quality: number|null;',
    '  delivery: number|null; insider: number|null; news: number|null; fundamental: number|null;',
    '  signals: number; top_reason: string; close: number|null;',
    '  roce: number|null; roe: number|null; f_score: number|null; as_of: string;',
    '}',
    'interface Stats { total:number; avg_score:number; high:number; med:number; low:number; as_of:string; }',
    '',
    'const LAYERS = [',
    '  {key:"momentum",    label:"MOM",     color:"#60a5fa"},',
    '  {key:"seasonality", label:"SEASON",  color:"#f59e0b"},',
    '  {key:"quality",     label:"FSCORE",  color:"#10b981"},',
    '  {key:"delivery",    label:"DELIV",   color:"#818cf8"},',
    '  {key:"insider",     label:"INSIDER", color:"#ec4899"},',
    '  {key:"news",        label:"NEWS",    color:"#8b5cf6"},',
    '  {key:"fundamental", label:"FUND",    color:"#14b8a6"},',
    '];',
    '',
    'function fmt(v:number|null, d=1) { return v==null?"--":v.toFixed(d); }',
    'function scoreColor(v:number|null) { if(v==null) return "#374151"; if(v>=70) return "#10b981"; if(v>=50) return "#f59e0b"; return "#ef4444"; }',
    'function scoreGrade(v:number|null) { if(v==null) return "--"; if(v>=70) return "HIGH"; if(v>=50) return "MED"; return "LOW"; }',
    '',
    'function MiniBar({value, color}: {value:number|null; color:string}) {',
    '  return <div style={{width:"100%",height:3,background:"#1f2937",borderRadius:2}}>',
    '    <div style={{width:(value??0)+"%",height:"100%",background:color,borderRadius:2,transition:"width 0.3s"}}/>',
    '  </div>;',
    '}',
    '',
    'function ExpandedRow({row}: {row:Row}) {',
    '  return <tr><td colSpan={11} style={{padding:"0 0 8px 0",background:"#0a0f1a"}}>',
    '    <div style={{margin:"0 12px",background:"#0f1923",border:"1px solid #1e3a5f",borderRadius:6,padding:"12px 16px",display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>',
    '      <div>',
    '        <div style={{color:"#4b5563",fontSize:10,letterSpacing:2,marginBottom:8}}>LAYER BREAKDOWN</div>',
    '        {LAYERS.map(l => {',
    '          const v = row[l.key as keyof Row] as number|null;',
    '          return <div key={l.key} style={{marginBottom:6}}>',
    '            <div style={{display:"flex",justifyContent:"space-between",marginBottom:2}}>',
    '              <span style={{color:"#4b5563",fontSize:10,letterSpacing:1}}>{l.label}</span>',
    '              <span style={{color:l.color,fontSize:11,fontWeight:700}}>{v!=null?v.toFixed(0):"--"}</span>',
    '            </div>',
    '            <MiniBar value={v} color={l.color}/>',
    '          </div>;',
    '        })}',
    '      </div>',
    '      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,alignContent:"start"}}>',
    '        <div style={{color:"#4b5563",fontSize:10,letterSpacing:2,gridColumn:"1/-1",marginBottom:4}}>FUNDAMENTALS</div>',
    '        {[["ROCE",fmt(row.roce)+"%"],["ROE",fmt(row.roe)+"%"],["F-SCORE",(row.f_score!=null?row.f_score+"/9":"--")],["SIGNALS",row.signals+"/7"],["CLOSE",row.close!=null?"INR"+fmt(row.close):"--"],["AS OF",row.as_of?.slice(0,10)||"--"]].map(([k,v])=>(',
    '          <div key={k} style={{background:"#0a0f1a",borderRadius:4,padding:"6px 10px"}}>',
    '            <div style={{color:"#374151",fontSize:9,letterSpacing:1}}>{k}</div>',
    '            <div style={{color:"#e2e8f0",fontSize:13,fontWeight:700}}>{v}</div>',
    '          </div>',
    '        ))}',
    '      </div>',
    '    </div>',
    '  </td></tr>;',
    '}',
    '',
    'export default function ConvictionPage() {',
    '  const [rows, setRows] = useState<Row[]>([]);',
    '  const [stats, setStats] = useState<Stats|null>(null);',
    '  const [reasons, setReasons] = useState<{reason:string;count:number}[]>([]);',
    '  const [loading, setLoading] = useState(true);',
    '  const [error, setError] = useState("");',
    '  const [search, setSearch] = useState("");',
    '  const [minScore, setMinScore] = useState(0);',
    '  const [sortCol, setSortCol] = useState("score");',
    '  const [expanded, setExpanded] = useState<string|null>(null);',
    '  const [layerFilter, setLayerFilter] = useState<string|null>(null);',
    '',
    '  useEffect(() => {',
    '    setLoading(true);',
    '    fetch("/api/conviction?limit=200&min="+minScore)',
    '      .then(r=>r.json())',
    '      .then(d=>{setRows(d.rows||[]);setStats(d.stats||null);setReasons(d.top_reasons||[]);setError("");setLoading(false);})',
    '      .catch(e=>{setError(e.message);setLoading(false);});',
    '  }, [minScore]);',
    '',
    '  const filtered = useMemo(() => {',
    '    let r = rows;',
    '    if (search) r = r.filter(x => x.symbol.includes(search.toUpperCase()));',
    '    if (layerFilter) r = r.filter(x => x[layerFilter as keyof Row] != null);',
    '    return [...r].sort((a,b) => ((b[sortCol as keyof Row] as number)??-1) - ((a[sortCol as keyof Row] as number)??-1));',
    '  }, [rows, search, sortCol, layerFilter]);',
    '',
    '  const TH = ({col,label}:{col:string;label:string}) => (',
    '    <th onClick={()=>setSortCol(col)} style={{padding:"7px 10px",textAlign:"right",color:sortCol===col?"#60a5fa":"#374151",fontSize:10,letterSpacing:1,cursor:"pointer",fontFamily:"inherit",whiteSpace:"nowrap",userSelect:"none"}}>',
    '      {label}{sortCol===col?" v":""}',
    '    </th>',
    '  );',
    '',
    '  return (',
    '    <div style={{minHeight:"100vh",background:"#0a0a0a",color:"#e2e8f0",fontFamily:"\'Courier New\',monospace",padding:"24px"}}>',
    '',
    '      <div style={{borderBottom:"1px solid #1e3a5f",paddingBottom:16,marginBottom:24}}>',
    '        <div style={{color:"#60a5fa",fontSize:11,letterSpacing:3,marginBottom:4}}>MICC -- PHASE 29</div>',
    '        <h1 style={{margin:0,fontSize:20,fontWeight:700,color:"#f9fafb",letterSpacing:2}}>CONVICTION SCORE</h1>',
    '        <p style={{margin:"6px 0 0",color:"#4b5563",fontSize:11,letterSpacing:1}}>',
    '          7-LAYER SIGNAL FUSION: MOMENTUM · SEASONALITY · F-SCORE · DELIVERY · INSIDER · NEWS · FUNDAMENTALS',
    '        </p>',
    '      </div>',
    '',
    '      {stats && (',
    '        <div style={{display:"flex",gap:12,marginBottom:24,flexWrap:"wrap"}}>',
    '          {[',
    '            {l:"TOTAL",v:stats.total,c:"#e2e8f0"},',
    '            {l:"AVG SCORE",v:fmt(stats.avg_score),c:"#60a5fa"},',
    '            {l:"HIGH >=70",v:stats.high,c:"#10b981"},',
    '            {l:"MED 50-70",v:stats.med,c:"#f59e0b"},',
    '            {l:"LOW <50",v:stats.low,c:"#ef4444"},',
    '            {l:"AS OF",v:stats.as_of?.slice(0,10)||"--",c:"#374151"},',
    '          ].map(s=>(',
    '            <div key={s.l} style={{background:"#0f1923",border:"1px solid #1e3a5f",borderRadius:6,padding:"10px 16px",flex:1,minWidth:90}}>',
    '              <div style={{color:"#374151",fontSize:9,letterSpacing:2}}>{s.l}</div>',
    '              <div style={{color:s.c,fontSize:18,fontWeight:700,marginTop:2}}>{s.v}</div>',
    '            </div>',
    '          ))}',
    '        </div>',
    '      )}',
    '',
    '      <div style={{display:"flex",gap:8,marginBottom:16,flexWrap:"wrap",alignItems:"center"}}>',
    '        <input placeholder="SEARCH SYMBOL..." value={search} onChange={e=>setSearch(e.target.value)}',
    '          style={{background:"#0f1923",border:"1px solid #1e3a5f",borderRadius:4,color:"#e2e8f0",padding:"6px 12px",fontSize:11,width:180,outline:"none",fontFamily:"inherit",letterSpacing:1}}/>',
    '        <span style={{color:"#374151",fontSize:10,letterSpacing:1}}>MIN SCORE:</span>',
    '        {[0,30,50,70].map(v=>(',
    '          <button key={v} onClick={()=>setMinScore(v)} style={{background:minScore===v?"#1e3a5f":"transparent",color:minScore===v?"#60a5fa":"#374151",border:"1px solid "+(minScore===v?"#1e3a5f":"#1f2937"),borderRadius:4,padding:"4px 12px",fontSize:10,cursor:"pointer",fontFamily:"inherit",letterSpacing:1}}>',
    '            {v}+',
    '          </button>',
    '        ))}',
    '        <span style={{color:"#374151",fontSize:10,letterSpacing:1,marginLeft:"auto"}}>{filtered.length} SYMBOLS</span>',
    '      </div>',
    '',
    '      <div style={{display:"flex",gap:6,marginBottom:16,flexWrap:"wrap"}}>',
    '        {LAYERS.map(l=>(',
    '          <button key={l.key} onClick={()=>setLayerFilter(layerFilter===l.key?null:l.key)}',
    '            style={{background:layerFilter===l.key?"#0f1923":"transparent",color:layerFilter===l.key?l.color:"#374151",border:"1px solid "+(layerFilter===l.key?l.color:"#1f2937"),borderRadius:4,padding:"3px 12px",fontSize:10,cursor:"pointer",fontFamily:"inherit",letterSpacing:1}}>',
    '            {l.label}',
    '          </button>',
    '        ))}',
    '      </div>',
    '',
    '      {error && <div style={{background:"#1a0a0a",border:"1px solid #7f1d1d",borderRadius:6,padding:"12px 16px",color:"#fca5a5",fontSize:11,marginBottom:16,letterSpacing:1}}>ERROR: {error}</div>}',
    '      {loading && <div style={{color:"#374151",fontSize:12,letterSpacing:2,padding:"40px 0",textAlign:"center"}}>LOADING CONVICTION SCORES...</div>}',
    '',
    '      {!loading && (',
    '        <div style={{overflowX:"auto",border:"1px solid #1e3a5f",borderRadius:6}}>',
    '          <table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}>',
    '            <thead>',
    '              <tr style={{background:"#0f1923",borderBottom:"1px solid #1e3a5f"}}>',
    '                <th style={{padding:"7px 10px",textAlign:"left",color:"#374151",fontSize:10,letterSpacing:1,fontFamily:"inherit"}}>#</th>',
    '                <th style={{padding:"7px 12px",textAlign:"left",color:"#374151",fontSize:10,letterSpacing:1,fontFamily:"inherit"}}>SYMBOL</th>',
    '                <TH col="score" label="CONVICTION"/>',
    '                <TH col="momentum" label="MOM"/>',
    '                <TH col="seasonality" label="SEASON"/>',
    '                <TH col="quality" label="FSCORE"/>',
    '                <TH col="delivery" label="DELIV"/>',
    '                <TH col="insider" label="INSIDER"/>',
    '                <TH col="news" label="NEWS"/>',
    '                <TH col="fundamental" label="FUND"/>',
    '                <th style={{padding:"7px 10px",textAlign:"left",color:"#374151",fontSize:10,letterSpacing:1,fontFamily:"inherit"}}>TOP</th>',
    '              </tr>',
    '            </thead>',
    '            <tbody>',
    '              {filtered.map((row,i) => (<>',
    '                <tr key={row.symbol} onClick={()=>setExpanded(expanded===row.symbol?null:row.symbol)}',
    '                  style={{borderBottom:"1px solid #111",cursor:"pointer",background:expanded===row.symbol?"#0f1923":i%2===0?"#0a0a0a":"#0c0c0c"}}',
    '                  onMouseEnter={e=>{(e.currentTarget as HTMLElement).style.background="#0f1923";}}',
    '                  onMouseLeave={e=>{(e.currentTarget as HTMLElement).style.background=expanded===row.symbol?"#0f1923":i%2===0?"#0a0a0a":"#0c0c0c";}}>',
    '                  <td style={{padding:"7px 10px",color:"#374151",fontSize:10}}>{i+1}</td>',
    '                  <td style={{padding:"7px 12px"}}>',
    '                    <span style={{color:"#60a5fa",fontWeight:700,letterSpacing:1}}>{row.symbol}</span>',
    '                    <span style={{color:"#1e3a5f",fontSize:9,marginLeft:6}}>{row.signals}/7</span>',
    '                  </td>',
    '                  <td style={{padding:"7px 10px",textAlign:"right"}}>',
    '                    <span style={{color:scoreColor(row.score),fontWeight:700,fontSize:14}}>{fmt(row.score)}</span>',
    '                    <span style={{color:scoreColor(row.score),fontSize:9,marginLeft:6,letterSpacing:1}}>{scoreGrade(row.score)}</span>',
    '                  </td>',
    '                  {LAYERS.map(l => {',
    '                    const v = row[l.key as keyof Row] as number|null;',
    '                    return <td key={l.key} style={{padding:"7px 10px",textAlign:"right",color:v!=null?l.color:"#1f2937",fontSize:11}}>{v!=null?v.toFixed(0):"--"}</td>;',
    '                  })}',
    '                  <td style={{padding:"7px 10px"}}>',
    '                    <span style={{color:LAYERS.find(l=>l.key===row.top_reason)?.color||"#374151",fontSize:9,letterSpacing:1}}>',
    '                      {LAYERS.find(l=>l.key===row.top_reason)?.label||row.top_reason||"--"}',
    '                    </span>',
    '                  </td>',
    '                </tr>',
    '                {expanded===row.symbol && <ExpandedRow key={"exp-"+row.symbol} row={row}/>}',
    '              </>))}',
    '            </tbody>',
    '          </table>',
    '          {filtered.length===0 && <div style={{textAlign:"center",padding:40,color:"#374151",fontSize:11,letterSpacing:2}}>NO SYMBOLS MATCH FILTERS</div>}',
    '        </div>',
    '      )}',
    '',
    '      {reasons.length>0 && (',
    '        <div style={{marginTop:24,background:"#0f1923",border:"1px solid #1e3a5f",borderRadius:6,padding:16}}>',
    '          <div style={{color:"#374151",fontSize:10,letterSpacing:2,marginBottom:12}}>TOP DRIVING SIGNAL DISTRIBUTION</div>',
    '          <div style={{display:"flex",gap:10,flexWrap:"wrap"}}>',
    '            {reasons.map(({reason,count}) => {',
    '              const layer = LAYERS.find(l=>l.key===reason);',
    '              return <div key={reason} style={{background:"#0a0f1a",borderRadius:4,padding:"8px 14px",borderLeft:"2px solid "+(layer?.color||"#374151")}}>',
    '                <div style={{color:layer?.color||"#374151",fontSize:10,letterSpacing:1,fontWeight:700}}>{layer?.label||reason}</div>',
    '                <div style={{color:"#374151",fontSize:10}}>{count} symbols</div>',
    '              </div>;',
    '            })}',
    '          </div>',
    '        </div>',
    '      )}',
    '    </div>',
    '  );',
    '}',
]

write(SRC / "conviction" / "page.tsx", conviction_lines, "conviction/page.tsx")

# Also write the API route to correct path
conviction_api = [
    'import { NextRequest, NextResponse } from "next/server";',
    'import { spawnSync } from "child_process";',
    '',
    'const DB = "D:/marketDB/db/market.db";',
    'const DA = "D:/MICC";',
    'const PY = "C:/Users/marka/AppData/Local/Programs/Python/Python314/python.exe";',
    '',
    'function runPy(script: string): string {',
    '  const r = spawnSync(PY, ["-c", script], { encoding: "utf8", timeout: 30000, cwd: DA });',
    '  if (r.error) throw r.error;',
    '  return r.stdout.trim();',
    '}',
    '',
    'export async function GET(req: NextRequest) {',
    '  const { searchParams } = new URL(req.url);',
    '  const limit = parseInt(searchParams.get("limit") || "200", 10);',
    '  const minScore = parseFloat(searchParams.get("min") || "0");',
    '  const q = (searchParams.get("q") || "").toUpperCase();',
    '',
    '  const script = [',
    '    "import sqlite3, json, math",',
    '    "def s(v):",',
    '    "    if v is None: return None",',
    '    "    try:",',
    '    "        f=float(v)",',
    '    "        return None if (math.isnan(f) or math.isinf(f)) else round(f,2)",',
    '    "    except: return None",',
    '    "conn = sqlite3.connect(r\\"D:/marketDB/db/market.db\\", timeout=15)",',
    '    "conn.row_factory = sqlite3.Row",',
    '    "where = \\"WHERE c.conviction_score >= ' + '" + minScore + "' + '\\"",',
    '    "if \\"' + '" + q + "' + '\\": where += \\" AND c.symbol LIKE \'%' + '" + q + "' + '%\'\\\"",',
    '    "rows = conn.execute(\'SELECT c.*, st.close, sf.roce_pct, sf.roe_pct, sq.f_score FROM symbol_conviction c LEFT JOIN (SELECT symbol,close FROM stock_data WHERE date=(SELECT MAX(date) FROM stock_data WHERE close IS NOT NULL) AND close IS NOT NULL) st ON st.symbol=c.symbol LEFT JOIN screener_fundamentals sf ON sf.symbol=c.symbol LEFT JOIN symbol_quality_scores sq ON sq.symbol=c.symbol \' + where + \' ORDER BY c.conviction_score DESC LIMIT ' + '" + limit + "' + '\').fetchall()",',
    '    "results=[{\'symbol\':r[\'symbol\'],\'score\':s(r[\'conviction_score\']),\'momentum\':s(r[\'momentum_score\']),\'seasonality\':s(r[\'seasonality_score\']),\'quality\':s(r[\'quality_score\']),\'delivery\':s(r[\'delivery_score\']),\'insider\':s(r[\'insider_score\']),\'news\':s(r[\'news_score\']),\'fundamental\':s(r[\'fundamental_score\']),\'signals\':r[\'signal_count\'],\'top_reason\':r[\'top_reason\'],\'close\':s(r[\'close\']),\'roce\':s(r[\'roce_pct\']),\'roe\':s(r[\'roe_pct\']),\'f_score\':r[\'f_score\'],\'as_of\':r[\'computed_date\']} for r in rows]",',
    '    "stats=conn.execute(\'SELECT COUNT(*) as total, AVG(conviction_score) as avg_score, SUM(CASE WHEN conviction_score>=70 THEN 1 ELSE 0 END) as high, SUM(CASE WHEN conviction_score>=50 AND conviction_score<70 THEN 1 ELSE 0 END) as med, SUM(CASE WHEN conviction_score<50 THEN 1 ELSE 0 END) as low, MAX(computed_date) as as_of FROM symbol_conviction\').fetchone()",',
    '    "reasons=conn.execute(\'SELECT top_reason, COUNT(*) as cnt FROM symbol_conviction GROUP BY top_reason ORDER BY cnt DESC\').fetchall()",',
    '    "conn.close()",',
    '    "print(json.dumps({\'rows\':results,\'stats\':{\'total\':stats[\'total\'],\'avg_score\':s(stats[\'avg_score\']),\'high\':stats[\'high\'],\'med\':stats[\'med\'],\'low\':stats[\'low\'],\'as_of\':stats[\'as_of\']},\'top_reasons\':[{\'reason\':r[\'top_reason\'],\'count\':r[\'cnt\']} for r in reasons]}))",',
    '  ].join("\\n");',
    '  try {',
    '    return NextResponse.json(JSON.parse(runPy(script)));',
    '  } catch (e: any) {',
    '    return NextResponse.json({ error: e.message, rows: [], stats: null }, { status: 500 });',
    '  }',
    '}',
]

write(SRC / "api" / "conviction" / "route.ts", conviction_api, "/api/conviction/route.ts")


# =============================================================================
# [3] FIX portfolio page - correct path + MICC terminal aesthetic
# =============================================================================
log("[3/3] Writing portfolio page to correct path...")

portfolio_lines = [
    '"use client";',
    'import { useEffect, useState } from "react";',
    '',
    'interface Position {',
    '  id:number; symbol:string; entry_date:string; entry_price:number;',
    '  quantity:number; position_size:number; atr_at_entry:number;',
    '  stop_loss:number; target_1:number; target_2:number; risk_per_trade:number;',
    '  status:string; exit_date?:string; exit_price?:number; pnl?:number; pnl_pct?:number;',
    '  current_price?:number; unrealized?:number; unrealized_pct?:number;',
    '  f_score?:number; conviction?:number;',
    '}',
    'interface Signal {',
    '  signal_name:string; asset:string; value:number; signal_type:string;',
    '  condition_desc:string; nifty_fwd_5d?:number; nifty_fwd_10d?:number;',
    '  hit_rate_hist?:number; n_historical:number; date:string;',
    '}',
    'interface Summary {',
    '  open_count:number; closed_count:number; total_invested:number;',
    '  total_unrealized:number; total_realized:number; win_rate?:number;',
    '}',
    '',
    'const SIG_COLOR: Record<string,string> = {',
    '  FEAR:"#ef4444",SPIKE:"#f97316",CALM:"#10b981",STRONG:"#ef4444",WEAK:"#10b981",',
    '  BULLISH:"#f59e0b",BEARISH:"#3b82f6",WEAK_INR:"#ef4444",STRONG_INR:"#10b981",',
    '  RISK_ON:"#10b981",RISK_OFF:"#ef4444",RISING:"#ef4444",FALLING:"#10b981",',
    '};',
    'const SIG_IMPACT: Record<string,string> = {',
    '  FEAR:"Contrarian BUY signal", SPIKE:"Short-term caution",',
    '  CALM:"Complacency -- watch for VIX spike",',
    '  STRONG:"DXY strength = FII headwind", WEAK:"DXY weak = FII tailwind",',
    '  BULLISH:"Risk-off, gold rising", BEARISH:"Risk-on, gold falling",',
    '  WEAK_INR:"Rupee weak -- FII outflow pressure", STRONG_INR:"Rupee strong -- FII inflow",',
    '  RISK_ON:"Global risk appetite positive", RISK_OFF:"Global risk appetite negative",',
    '  RISING:"Rate tightening -- valuation headwind", FALLING:"Rate easing -- valuation tailwind",',
    '};',
    '',
    'function fmt(v?:number|null, d=1) { return v==null?"--":v.toFixed(d); }',
    'function pc(v?:number|null) { return v==null?"#374151":v>=0?"#10b981":"#ef4444"; }',
    '',
    'function StatBox({label,value,color}:{label:string;value:string|number;color:string}) {',
    '  return <div style={{background:"#0f1923",border:"1px solid #1e3a5f",borderRadius:6,padding:"10px 16px",flex:1,minWidth:90}}>',
    '    <div style={{color:"#374151",fontSize:9,letterSpacing:2}}>{label}</div>',
    '    <div style={{color,fontSize:18,fontWeight:700,marginTop:2}}>{value}</div>',
    '  </div>;',
    '}',
    '',
    'function AddForm({onAdd}:{onAdd:()=>void}) {',
    '  const [f,setF]=useState({symbol:"",entry_date:new Date().toISOString().slice(0,10),entry_price:"",quantity:"",atr_at_entry:"",account_size:"500000",risk_pct:"1.0"});',
    '  const [res,setRes]=useState<any>(null);',
    '  const [loading,setLoading]=useState(false);',
    '  const set=(k:string,v:string)=>setF(p=>({...p,[k]:v}));',
    '  const inp=(ph:string,k:string,t="text")=>(',
    '    <input placeholder={ph} type={t} value={(f as any)[k]} onChange={e=>set(k,e.target.value)}',
    '      style={{background:"#0a0f1a",border:"1px solid #1e3a5f",borderRadius:4,color:"#e2e8f0",padding:"6px 10px",fontSize:11,width:"100%",outline:"none",fontFamily:"inherit",letterSpacing:1}}/>',
    '  );',
    '  const submit=async()=>{',
    '    setLoading(true);',
    '    const r=await fetch("/api/portfolio",{method:"POST",headers:{"Content-Type":"application/json"},',
    '      body:JSON.stringify({action:"add",...f,entry_price:parseFloat(f.entry_price),quantity:parseInt(f.quantity)||0,atr_at_entry:parseFloat(f.atr_at_entry)||0,account_size:parseFloat(f.account_size),risk_pct:parseFloat(f.risk_pct)})});',
    '    const d=await r.json(); setRes(d); setLoading(false); if(d.ok) onAdd();',
    '  };',
    '  return <div style={{background:"#0f1923",border:"1px solid #1e3a5f",borderRadius:6,padding:16,marginBottom:20}}>',
    '    <div style={{color:"#374151",fontSize:10,letterSpacing:2,marginBottom:12}}>ADD POSITION -- ATR POSITION SIZING</div>',
    '    <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:10}}>',
    '      {inp("SYMBOL","symbol")}{inp("ENTRY DATE","entry_date","date")}',
    '      {inp("ENTRY PRICE","entry_price","number")}{inp("ATR 14D (0=SKIP)","atr_at_entry","number")}',
    '    </div>',
    '    <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:12}}>',
    '      {inp("QTY (0=AUTO)","quantity","number")}{inp("ACCOUNT SIZE","account_size","number")}',
    '      {inp("RISK % PER TRADE","risk_pct","number")}',
    '      <button onClick={submit} disabled={loading} style={{background:"#1e3a5f",color:"#60a5fa",border:"1px solid #1e3a5f",borderRadius:4,padding:"6px 16px",fontSize:11,cursor:"pointer",fontFamily:"inherit",letterSpacing:1,fontWeight:700}}>',
    '        {loading?"ADDING...":"ADD POSITION"}',
    '      </button>',
    '    </div>',
    '    {res&&<div style={{background:res.ok?"#0a1a0f":"#1a0a0a",border:"1px solid "+(res.ok?"#10b981":"#ef4444"),borderRadius:4,padding:"8px 12px",fontSize:11,letterSpacing:1}}>',
    '      {res.ok?<span style={{color:"#10b981"}}>ADDED -- QTY:{res.qty} STOP:INR{res.stop_loss} T1:INR{res.target_1} T2:INR{res.target_2} RISK:INR{res.risk_per_trade}</span>',
    '             :<span style={{color:"#ef4444"}}>ERROR: {res.error}</span>}',
    '    </div>}',
    '  </div>;',
    '}',
    '',
    'export default function PortfolioPage() {',
    '  const [data,setData]=useState<{positions:Position[];cross_asset:Signal[];summary:Summary}|null>(null);',
    '  const [loading,setLoading]=useState(true);',
    '  const [tab,setTab]=useState<"open"|"closed"|"signals">("open");',
    '  const [closing,setClosing]=useState<number|null>(null);',
    '  const [exitPrice,setExitPrice]=useState("");',
    '',
    '  const load=()=>{setLoading(true);fetch("/api/portfolio").then(r=>r.json()).then(d=>{setData(d);setLoading(false);});};',
    '  useEffect(()=>{load();},[]);',
    '',
    '  const closePos=async(id:number)=>{',
    '    const r=await fetch("/api/portfolio",{method:"POST",headers:{"Content-Type":"application/json"},',
    '      body:JSON.stringify({action:"close",id,exit_price:parseFloat(exitPrice),exit_date:new Date().toISOString().slice(0,10)})});',
    '    const d=await r.json(); if(d.ok){setClosing(null);setExitPrice("");load();}',
    '  };',
    '',
    '  const open=data?.positions.filter(p=>p.status==="OPEN")||[];',
    '  const closed=data?.positions.filter(p=>p.status==="CLOSED")||[];',
    '  const s=data?.summary;',
    '',
    '  const tabs:[string,string][] = [["open","OPEN ("+open.length+")"],["closed","CLOSED ("+closed.length+")"],["signals","CROSS-ASSET SIGNALS"]];',
    '',
    '  return (',
    '    <div style={{minHeight:"100vh",background:"#0a0a0a",color:"#e2e8f0",fontFamily:"\'Courier New\',monospace",padding:"24px"}}>',
    '',
    '      <div style={{borderBottom:"1px solid #1e3a5f",paddingBottom:16,marginBottom:24}}>',
    '        <div style={{color:"#60a5fa",fontSize:11,letterSpacing:3,marginBottom:4}}>MICC -- PHASE 30</div>',
    '        <h1 style={{margin:0,fontSize:20,fontWeight:700,color:"#f9fafb",letterSpacing:2}}>PORTFOLIO TRACKER</h1>',
    '        <p style={{margin:"6px 0 0",color:"#4b5563",fontSize:11,letterSpacing:1}}>ATR POSITION SIZING · CROSS-ASSET REGIME SIGNALS · CONVICTION OVERLAY</p>',
    '      </div>',
    '',
    '      {s&&<div style={{display:"flex",gap:12,marginBottom:24,flexWrap:"wrap"}}>',
    '        <StatBox label="OPEN" value={s.open_count} color="#e2e8f0"/>',
    '        <StatBox label="INVESTED" value={"INR"+(s.total_invested/1000).toFixed(0)+"K"} color="#60a5fa"/>',
    '        <StatBox label="UNREALIZED" value={(s.total_unrealized>=0?"+":"")+s.total_unrealized.toFixed(0)} color={pc(s.total_unrealized)}/>',
    '        <StatBox label="REALIZED" value={(s.total_realized>=0?"+":"")+s.total_realized.toFixed(0)} color={pc(s.total_realized)}/>',
    '        <StatBox label="WIN RATE" value={s.win_rate!=null?s.win_rate+"%":"--"} color="#f59e0b"/>',
    '        <StatBox label="CLOSED" value={s.closed_count} color="#374151"/>',
    '      </div>}',
    '',
    '      <AddForm onAdd={load}/>',
    '',
    '      <div style={{display:"flex",gap:4,marginBottom:16}}>',
    '        {tabs.map(([k,label])=>(',
    '          <button key={k} onClick={()=>setTab(k as any)} style={{background:tab===k?"#1e3a5f":"transparent",color:tab===k?"#60a5fa":"#374151",border:"1px solid "+(tab===k?"#1e3a5f":"#1f2937"),borderRadius:4,padding:"6px 18px",fontSize:10,cursor:"pointer",fontFamily:"inherit",letterSpacing:1,fontWeight:tab===k?700:400}}>',
    '            {label}',
    '          </button>',
    '        ))}',
    '      </div>',
    '',
    '      {loading&&<div style={{color:"#374151",fontSize:11,letterSpacing:2,padding:"40px 0",textAlign:"center"}}>LOADING...</div>}',
    '',
    '      {!loading&&tab==="open"&&<div style={{overflowX:"auto",border:"1px solid #1e3a5f",borderRadius:6}}>',
    '        <table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}>',
    '          <thead><tr style={{background:"#0f1923",borderBottom:"1px solid #1e3a5f"}}>',
    '            {["SYMBOL","DATE","QTY","ENTRY","CMP","UNREAL","UNREAL%","STOP","T1","T2","RISK","CONV","F","ACTION"].map(h=>',
    '              <th key={h} style={{padding:"7px 10px",color:"#374151",fontSize:9,letterSpacing:1,textAlign:"right",fontFamily:"inherit",whiteSpace:"nowrap"}}>{h}</th>',
    '            )}',
    '          </tr></thead>',
    '          <tbody>',
    '            {open.map(p=>(',
    '              <tr key={p.id} style={{borderBottom:"1px solid #111"}}>',
    '                <td style={{padding:"7px 10px",color:"#60a5fa",fontWeight:700,letterSpacing:1}}>{p.symbol}</td>',
    '                <td style={{padding:"7px 10px",color:"#374151",textAlign:"right"}}>{p.entry_date?.slice(5)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#e2e8f0"}}>{p.quantity}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#9ca3af"}}>INR{fmt(p.entry_price)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#60a5fa"}}>INR{fmt(p.current_price)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:pc(p.unrealized)}}>{p.unrealized!=null?(p.unrealized>=0?"+":"")+fmt(p.unrealized,0):"--"}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:pc(p.unrealized_pct)}}>{p.unrealized_pct!=null?(p.unrealized_pct>=0?"+":"")+fmt(p.unrealized_pct)+"%":"--"}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#ef4444"}}>INR{fmt(p.stop_loss)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#10b981"}}>INR{fmt(p.target_1)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#34d399"}}>INR{fmt(p.target_2)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#f59e0b"}}>INR{fmt(p.risk_per_trade,0)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#818cf8"}}>{fmt(p.conviction,0)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#374151"}}>{p.f_score!=null?p.f_score+"/9":"--"}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right"}}>',
    '                  {closing===p.id?<span style={{display:"flex",gap:4}}>',
    '                    <input value={exitPrice} onChange={e=>setExitPrice(e.target.value)} placeholder="EXIT" type="number"',
    '                      style={{width:65,background:"#0a0f1a",border:"1px solid #1e3a5f",borderRadius:3,color:"#e2e8f0",padding:"3px 6px",fontSize:10,fontFamily:"inherit"}}/>',
    '                    <button onClick={()=>closePos(p.id)} style={{background:"#0a1a0f",color:"#10b981",border:"1px solid #10b981",borderRadius:3,padding:"2px 8px",fontSize:9,cursor:"pointer",fontFamily:"inherit",letterSpacing:1}}>OK</button>',
    '                    <button onClick={()=>setClosing(null)} style={{background:"transparent",color:"#374151",border:"1px solid #1f2937",borderRadius:3,padding:"2px 8px",fontSize:9,cursor:"pointer",fontFamily:"inherit"}}>X</button>',
    '                  </span>:<button onClick={()=>setClosing(p.id)} style={{background:"transparent",color:"#374151",border:"1px solid #1f2937",borderRadius:3,padding:"3px 10px",fontSize:9,cursor:"pointer",fontFamily:"inherit",letterSpacing:1}}>CLOSE</button>}',
    '                </td>',
    '              </tr>',
    '            ))}',
    '            {open.length===0&&<tr><td colSpan={14} style={{textAlign:"center",padding:30,color:"#374151",fontSize:10,letterSpacing:2}}>NO OPEN POSITIONS -- ADD ONE ABOVE</td></tr>}',
    '          </tbody>',
    '        </table>',
    '      </div>}',
    '',
    '      {!loading&&tab==="closed"&&<div style={{overflowX:"auto",border:"1px solid #1e3a5f",borderRadius:6}}>',
    '        <table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}>',
    '          <thead><tr style={{background:"#0f1923",borderBottom:"1px solid #1e3a5f"}}>',
    '            {["SYMBOL","ENTRY","EXIT","QTY","ENTRY","EXIT","P&L","P&L%"].map(h=><th key={h} style={{padding:"7px 10px",color:"#374151",fontSize:9,letterSpacing:1,textAlign:"right",fontFamily:"inherit"}}>{h}</th>)}',
    '          </tr></thead>',
    '          <tbody>',
    '            {closed.map(p=>(',
    '              <tr key={p.id} style={{borderBottom:"1px solid #111"}}>',
    '                <td style={{padding:"7px 10px",color:"#60a5fa",fontWeight:700,letterSpacing:1}}>{p.symbol}</td>',
    '                <td style={{padding:"7px 10px",color:"#374151",textAlign:"right"}}>{p.entry_date?.slice(5)}</td>',
    '                <td style={{padding:"7px 10px",color:"#374151",textAlign:"right"}}>{p.exit_date?.slice(5)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right"}}>{p.quantity}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#9ca3af"}}>INR{fmt(p.entry_price)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:"#9ca3af"}}>INR{fmt(p.exit_price)}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:pc(p.pnl)}}>{p.pnl!=null?(p.pnl>=0?"+":"")+fmt(p.pnl,0):"--"}</td>',
    '                <td style={{padding:"7px 10px",textAlign:"right",color:pc(p.pnl_pct)}}>{p.pnl_pct!=null?(p.pnl_pct>=0?"+":"")+fmt(p.pnl_pct)+"%":"--"}</td>',
    '              </tr>',
    '            ))}',
    '            {closed.length===0&&<tr><td colSpan={8} style={{textAlign:"center",padding:30,color:"#374151",fontSize:10,letterSpacing:2}}>NO CLOSED TRADES YET</td></tr>}',
    '          </tbody>',
    '        </table>',
    '      </div>}',
    '',
    '      {!loading&&tab==="signals"&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:12}}>',
    '        {(data?.cross_asset||[]).map(sig=>{',
    '          const color=SIG_COLOR[sig.signal_type]||"#374151";',
    '          const hr=sig.hit_rate_hist;',
    '          return <div key={sig.signal_name} style={{background:"#0f1923",border:"1px solid #1e3a5f",borderLeft:"2px solid "+color,borderRadius:6,padding:14}}>',
    '            <div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}>',
    '              <span style={{color:"#374151",fontSize:9,letterSpacing:2}}>{sig.asset}</span>',
    '              <span style={{color,fontSize:9,letterSpacing:1,fontWeight:700}}>{sig.signal_type}</span>',
    '            </div>',
    '            <div style={{color:"#e2e8f0",fontSize:12,fontWeight:700,letterSpacing:1,marginBottom:4}}>{sig.signal_name.replace(/_/g," ")}</div>',
    '            <div style={{color:"#4b5563",fontSize:10,marginBottom:6}}>{sig.condition_desc}</div>',
    '            <div style={{color,fontSize:10,fontStyle:"italic",marginBottom:10}}>{SIG_IMPACT[sig.signal_type]||""}</div>',
    '            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6}}>',
    '              {[["VALUE",fmt(sig.value,2),"#e2e8f0"],["HIT RATE",hr!=null?(hr*100).toFixed(0)+"%":"--",hr!=null?(hr>0.6?"#10b981":hr>0.4?"#f59e0b":"#ef4444"):"#374151"],["NIFTY FWD10",sig.nifty_fwd_10d!=null?(sig.nifty_fwd_10d>0?"+":"")+fmt(sig.nifty_fwd_10d)+"%":"--",pc(sig.nifty_fwd_10d)]].map(([lbl,val,col])=>(',
    '                <div key={lbl as string} style={{background:"#0a0f1a",borderRadius:4,padding:"5px 8px"}}>',
    '                  <div style={{color:"#374151",fontSize:8,letterSpacing:1}}>{lbl}</div>',
    '                  <div style={{color:col as string,fontSize:12,fontWeight:700}}>{val}</div>',
    '                </div>',
    '              ))}',
    '            </div>',
    '            <div style={{marginTop:8,color:"#1e3a5f",fontSize:9}}>n={sig.n_historical} | {sig.date}</div>',
    '          </div>;',
    '        })}',
    '        {(data?.cross_asset||[]).length===0&&<div style={{color:"#374151",padding:40,gridColumn:"1/-1",textAlign:"center",fontSize:10,letterSpacing:2}}>NO CROSS-ASSET SIGNALS -- RUN build_phase30.py FIRST</div>}',
    '      </div>}',
    '',
    '    </div>',
    '  );',
    '}',
]

write(SRC / "portfolio" / "page.tsx", portfolio_lines, "portfolio/page.tsx")

# Also fix portfolio API to correct path
portfolio_api_lines = [
    'import { NextRequest, NextResponse } from "next/server";',
    'import { spawnSync } from "child_process";',
    '',
    'const DA = "D:/MICC";',
    'const PY = "C:/Users/marka/AppData/Local/Programs/Python/Python314/python.exe";',
    'const DB = "D:/marketDB/db/market.db";',
    '',
    'function runPy(script: string): string {',
    '  const r = spawnSync(PY, ["-c", script], { encoding: "utf8", timeout: 20000, cwd: DA });',
    '  if (r.error) throw r.error;',
    '  return r.stdout.trim();',
    '}',
    '',
    'export async function GET() {',
    '  const script = [',
    '    "import sqlite3, json, math",',
    '    "def s(v):",',
    '    "    if v is None: return None",',
    '    "    try:",',
    '    "        f=float(v)",',
    '    "        return None if (math.isnan(f) or math.isinf(f)) else round(f,2)",',
    '    "    except: return None",',
    '    "conn=sqlite3.connect(r\\"' + "D:/marketDB/db/market.db" + '\\",timeout=15)",',
    '    "conn.row_factory=sqlite3.Row",',
    '    "rows=conn.execute(\'SELECT p.*,st.close as cp,sc.conviction_score,sq.f_score FROM my_portfolio p LEFT JOIN (SELECT symbol,close FROM stock_data WHERE date=(SELECT MAX(date) FROM stock_data WHERE close IS NOT NULL) AND close IS NOT NULL) st ON st.symbol=p.symbol LEFT JOIN symbol_conviction sc ON sc.symbol=p.symbol LEFT JOIN symbol_quality_scores sq ON sq.symbol=p.symbol ORDER BY p.status,p.added_at DESC\').fetchall()",',
    '    "positions=[]",',
    '    "for r in rows:",',
    '    "    cur=s(r[\'cp\']) or s(r[\'entry_price\']) or 0",',
    '    "    ep=s(r[\'entry_price\']) or 0; qty=r[\'quantity\'] or 0",',
    '    "    unr=round((cur-ep)*qty,2) if ep and cur else None",',
    '    "    unrp=round((cur-ep)/ep*100,2) if ep and cur else None",',
    '    "    positions.append({\'id\':r[\'id\'],\'symbol\':r[\'symbol\'],\'entry_date\':r[\'entry_date\'],\'entry_price\':s(r[\'entry_price\']),\'quantity\':qty,\'position_size\':s(r[\'position_size\']),\'atr_at_entry\':s(r[\'atr_at_entry\']),\'stop_loss\':s(r[\'stop_loss\']),\'target_1\':s(r[\'target_1\']),\'target_2\':s(r[\'target_2\']),\'risk_per_trade\':s(r[\'risk_per_trade\']),\'status\':r[\'status\'],\'exit_price\':s(r[\'exit_price\']),\'pnl\':s(r[\'pnl\']),\'pnl_pct\':s(r[\'pnl_pct\']),\'current_price\':s(r[\'cp\']),\'unrealized\':unr,\'unrealized_pct\':unrp,\'f_score\':r[\'f_score\'],\'conviction\':s(r[\'conviction_score\'])})",',
    '    "sigs=conn.execute(\'SELECT * FROM cross_asset_signals WHERE date=(SELECT MAX(date) FROM cross_asset_signals) ORDER BY signal_name\').fetchall()",',
    '    "op=[p for p in positions if p[\'status\']==\'OPEN\']",',
    '    "cl=[p for p in positions if p[\'status\']==\'CLOSED\']",',
    '    "wins=[p for p in cl if (p[\'pnl\'] or 0)>0]",',
    '    "conn.close()",',
    '    "print(json.dumps({\'positions\':positions,\'cross_asset\':[dict(r) for r in sigs],\'summary\':{\'open_count\':len(op),\'closed_count\':len(cl),\'total_invested\':round(sum((p[\'position_size\'] or 0) for p in op),2),\'total_unrealized\':round(sum((p[\'unrealized\'] or 0) for p in op),2),\'total_realized\':round(sum((p[\'pnl\'] or 0) for p in cl),2),\'win_rate\':round(len(wins)/len(cl)*100,1) if cl else None}},default=str))",',
    '  ].join("\\n");',
    '  try { return NextResponse.json(JSON.parse(runPy(script))); }',
    '  catch (e: any) { return NextResponse.json({ error: e.message, positions: [], cross_asset: [], summary: {} }, { status: 500 }); }',
    '}',
    '',
    'export async function POST(req: NextRequest) {',
    '  const body = await req.json();',
    '  if (body.action === "add") {',
    '    const ep = parseFloat(body.entry_price) || 0;',
    '    const atr = parseFloat(body.atr_at_entry) || 0;',
    '    const acc = parseFloat(body.account_size) || 500000;',
    '    const rp = parseFloat(body.risk_pct) || 1.0;',
    '    const qtyIn = parseInt(body.quantity) || 0;',
    '    const sym = JSON.stringify(body.symbol || "");',
    '    const dt = JSON.stringify(body.entry_date || "");',
    '    const script = [',
    '      "import sqlite3, json",',
    '      "ep=" + ep + "; atr=" + atr + "; acc=" + acc + "; rp=" + rp + "; qi=" + qtyIn,',
    '      "sl=round(ep-2*atr,2) if atr>0 else round(ep*0.95,2)",',
    '      "rps=ep-sl; ra=acc*rp/100",',
    '      "qty=qi if qi>0 else (int(ra/rps) if rps>0 else 0)",',
    '      "ps=round(ep*qty,2); rpt=round(rps*qty,2)",',
    '      "t1=round(ep+2*atr,2) if atr>0 else round(ep*1.06,2)",',
    '      "t2=round(ep+4*atr,2) if atr>0 else round(ep*1.12,2)",',
    '      "conn=sqlite3.connect(r\\"D:/marketDB/db/market.db\\",timeout=15)",',
    '      "conn.execute(\\"INSERT INTO my_portfolio (symbol,entry_date,entry_price,quantity,position_size,atr_at_entry,stop_loss,target_1,target_2,risk_per_trade,status) VALUES (?,?,?,?,?,?,?,?,?,?,\'OPEN\')\\",(" + sym + "," + dt + ",ep,qty,ps,atr,sl,t1,t2,rpt))",',
    '      "conn.commit(); conn.close()",',
    '      "print(json.dumps({\'ok\':True,\'qty\':qty,\'stop_loss\':sl,\'target_1\':t1,\'target_2\':t2,\'position_size\':ps,\'risk_per_trade\':rpt}))",',
    '    ].join("\\n");',
    '    try { return NextResponse.json(JSON.parse(runPy(script))); }',
    '    catch (e: any) { return NextResponse.json({ error: e.message }, { status: 500 }); }',
    '  }',
    '  if (body.action === "close") {',
    '    const xp = parseFloat(body.exit_price) || 0;',
    '    const id = body.id;',
    '    const dt = JSON.stringify(body.exit_date || "");',
    '    const script = [',
    '      "import sqlite3, json",',
    '      "conn=sqlite3.connect(r\\"D:/marketDB/db/market.db\\",timeout=15); conn.row_factory=sqlite3.Row",',
    '      "pos=conn.execute(\'SELECT * FROM my_portfolio WHERE id=?\',(" + id + ",)).fetchone()",',
    '      "ep=pos[\'entry_price\'] or 0; qty=pos[\'quantity\'] or 0; xp=" + xp,',
    '      "pnl=round((xp-ep)*qty,2); pnlp=round((xp-ep)/ep*100,2) if ep else 0",',
    '      "conn.execute(\\"UPDATE my_portfolio SET status=\'CLOSED\',exit_date=?,exit_price=?,pnl=?,pnl_pct=? WHERE id=?\\",(" + dt + ",xp,pnl,pnlp," + id + "))",',
    '      "conn.commit(); conn.close()",',
    '      "print(json.dumps({\'ok\':True,\'pnl\':pnl,\'pnl_pct\':pnlp}))",',
    '    ].join("\\n");',
    '    try { return NextResponse.json(JSON.parse(runPy(script))); }',
    '    catch (e: any) { return NextResponse.json({ error: e.message }, { status: 500 }); }',
    '  }',
    '  return NextResponse.json({ error: "unknown action" }, { status: 400 });',
    '}',
]

write(SRC / "api" / "portfolio" / "route.ts", portfolio_api_lines, "/api/portfolio/route.ts")


print("")
print("=" * 55)
print("ALL FIXES APPLIED")
print("=" * 55)
print("")
print("Fixed:")
print("  1. eta/page.tsx -- compile error resolved")
print("  2. conviction/page.tsx -- correct path + terminal UI")
print("  3. portfolio/page.tsx -- correct path + terminal UI")
print("  4. API routes -- correct paths")
print("")
print("Dashboard should now compile clean.")
print("Visit: http://localhost:3000/conviction")
print("Visit: http://localhost:3000/portfolio")
