"""
fix_oos_degradation.py
======================
The OOS script has in_acc stored as 0-100 (e.g. 72.0) but oos_acc
computed as 0-1 (e.g. 0.688), so degradation = 72.0 - 0.688 = 71.3pp
instead of 0.72 - 0.688 = 0.032pp.

Fix: normalise in_acc to 0-1 range before computing degradation.
Also resets any bad data written by the test run (50k rows with wrong values).

Run: py D:\MICC\fix_oos_degradation.py
"""
from pathlib import Path

MICC = Path(r"D:\MICC")

lines = [
    "import sqlite3, json, sys",
    "from datetime import datetime",
    "",
    "DB            = r'D:\\marketDB\\db\\market.db'",
    "OOS_YEAR      = 2019",
    "MIN_OOS       = 5",
    "OVERFIT_THRESH = 0.10",
    "TEST_MODE     = '--test' in sys.argv",
    "",
    "print('OOS Pattern Validation (fixed degradation calc)')",
    "print(f'  OOS year    : {OOS_YEAR}')",
    "print(f'  Min OOS obs : {MIN_OOS}')",
    "print(f'  Overfit thr : {int(OVERFIT_THRESH*100)}pp')",
    "print(f'  Mode        : {\"TEST (50k rows)\" if TEST_MODE else \"FULL RUN\"}')",
    "print()",
    "",
    "conn = sqlite3.connect(DB, timeout=120)",
    "conn.execute('PRAGMA journal_mode=WAL')",
    "conn.execute('PRAGMA synchronous=NORMAL')",
    "conn.execute('PRAGMA cache_size=-256000')",
    "",
    "# -- Reset bad data from previous test run --",
    "print('[0] Resetting any bad OOS data from prior run...')",
    "conn.execute('UPDATE seasonality_patterns_v3 SET oos_accuracy=NULL, oos_n_obs=NULL, oos_degradation=NULL, overfit=0 WHERE oos_degradation > 1.0')",
    "reset_n = conn.execute('SELECT changes()').fetchone()[0]",
    "conn.commit()",
    "print(f'  Reset {reset_n:,} rows with bad degradation values')",
    "",
    "# -- Detect in_acc scale --",
    "print('[1] Detecting accuracy column scale...')",
    "acc_sample = conn.execute(",
    "    'SELECT accuracy FROM seasonality_patterns_v3 WHERE accuracy IS NOT NULL LIMIT 5'",
    ").fetchall()",
    "acc_vals = [float(r[0]) for r in acc_sample]",
    "print(f'  Sample accuracy values: {acc_vals}')",
    "# If values > 1.0 they are stored as percentages (0-100), normalise",
    "ACC_IS_PCT = any(v > 1.5 for v in acc_vals)",
    "print(f'  Stored as pct (0-100): {ACC_IS_PCT}')",
    "",
    "# -- Check all_returns format --",
    "print('[2] Checking all_returns format...')",
    "sample = conn.execute(",
    "    'SELECT all_returns FROM seasonality_patterns_v3'",
    "    ' WHERE all_returns IS NOT NULL AND all_returns != \"[]\" LIMIT 1'",
    ").fetchone()",
    "if not sample:",
    "    print('  [ERROR] all_returns empty'); sys.exit(1)",
    "parsed = json.loads(sample[0])",
    "first  = parsed[0]",
    "if isinstance(first, dict):",
    "    YEAR_KEY, RET_KEY = 'year', 'ret'",
    "    print(f'  Format: dict {{year, ret}}')",
    "elif isinstance(first, (list, tuple)):",
    "    YEAR_KEY, RET_KEY = 0, 1",
    "    print(f'  Format: list [year, ret]')",
    "else:",
    "    print(f'  [ERROR] Unknown: {first}'); sys.exit(1)",
    "",
    "# -- Create temp table --",
    "print('[3] Computing OOS accuracy...')",
    "conn.execute('DROP TABLE IF EXISTS _oos_temp')",
    "conn.execute(",
    "    'CREATE TEMP TABLE _oos_temp ('",
    "    '  id INTEGER PRIMARY KEY,'",
    "    '  oos_accuracy REAL,'",
    "    '  oos_n_obs INTEGER,'",
    "    '  oos_degradation REAL,'",
    "    '  overfit INTEGER'",
    "    ')'",
    ")",
    "",
    "limit_clause = 'LIMIT 50000' if TEST_MODE else ''",
    "rows = conn.execute(",
    "    'SELECT id, accuracy, all_returns FROM seasonality_patterns_v3'",
    "    ' WHERE all_returns IS NOT NULL AND all_returns != \"[]\"'",
    "    f' {limit_clause}'",
    ").fetchall()",
    "",
    "print(f'  Rows to process: {len(rows):,}')",
    "batch = []",
    "t0 = datetime.now()",
    "ok_count = skip_count = err_count = 0",
    "",
    "for i, (pid, in_acc_raw, raw) in enumerate(rows):",
    "    if i % 200000 == 0 and i > 0:",
    "        elapsed = (datetime.now() - t0).total_seconds()",
    "        rate = i / elapsed",
    "        eta  = (len(rows) - i) / rate / 60",
    "        print(f'  {i:,}/{len(rows):,} ({i/len(rows)*100:.1f}%)  {rate:.0f}/s  ETA {eta:.1f}m'",
    "              f'  ok={ok_count:,} skip={skip_count:,}', flush=True)",
    "    try:",
    "        returns = json.loads(raw)",
    "    except Exception:",
    "        err_count += 1; continue",
    "    if not returns:",
    "        skip_count += 1; continue",
    "",
    "    oos_rets = []",
    "    for r in returns:",
    "        try:",
    "            y   = int(r[YEAR_KEY])",
    "            ret = float(r[RET_KEY])",
    "            if y >= OOS_YEAR:",
    "                oos_rets.append(ret)",
    "        except (KeyError, IndexError, TypeError, ValueError):",
    "            continue",
    "",
    "    if len(oos_rets) < MIN_OOS:",
    "        skip_count += 1",
    "        batch.append((None, len(oos_rets), None, 0, pid))",
    "        continue",
    "",
    "    # OOS accuracy: fraction of years where return > 0",
    "    oos_acc = sum(1 for r in oos_rets if r > 0) / len(oos_rets)",
    "",
    "    # Normalise in_acc to 0-1 range regardless of storage format",
    "    if in_acc_raw is None:",
    "        in_acc_f = 0.5",
    "    else:",
    "        in_acc_f = float(in_acc_raw)",
    "        if ACC_IS_PCT and in_acc_f > 1.5:",
    "            in_acc_f = in_acc_f / 100.0",
    "",
    "    degrade = in_acc_f - oos_acc          # both now 0-1, so result is pp as fraction",
    "    overfit = 1 if degrade > OVERFIT_THRESH else 0",
    "    ok_count += 1",
    "    batch.append((round(oos_acc, 4), len(oos_rets), round(degrade, 4), overfit, pid))",
    "",
    "    if len(batch) >= 100000:",
    "        conn.executemany(",
    "            'INSERT OR REPLACE INTO _oos_temp(oos_accuracy,oos_n_obs,oos_degradation,overfit,id)'",
    "            ' VALUES(?,?,?,?,?)',",
    "            batch",
    "        )",
    "        conn.commit()",
    "        batch = []",
    "",
    "if batch:",
    "    conn.executemany(",
    "        'INSERT OR REPLACE INTO _oos_temp(oos_accuracy,oos_n_obs,oos_degradation,overfit,id)'",
    "        ' VALUES(?,?,?,?,?)',",
    "        batch",
    "    )",
    "    conn.commit()",
    "",
    "print(f'  Done processing. ok={ok_count:,}  skip={skip_count:,}  err={err_count:,}')",
    "",
    "# -- Bulk UPDATE --",
    "print('[4] Bulk UPDATE...')",
    "t1 = datetime.now()",
    "conn.execute(",
    "    'UPDATE seasonality_patterns_v3'",
    "    ' SET oos_accuracy    = (SELECT oos_accuracy    FROM _oos_temp t WHERE t.id = seasonality_patterns_v3.id),'",
    "    '     oos_n_obs       = (SELECT oos_n_obs       FROM _oos_temp t WHERE t.id = seasonality_patterns_v3.id),'",
    "    '     oos_degradation = (SELECT oos_degradation FROM _oos_temp t WHERE t.id = seasonality_patterns_v3.id),'",
    "    '     overfit         = (SELECT overfit         FROM _oos_temp t WHERE t.id = seasonality_patterns_v3.id)'",
    "    ' WHERE id IN (SELECT id FROM _oos_temp WHERE oos_accuracy IS NOT NULL)'",
    ")",
    "conn.commit()",
    "print(f'  UPDATE done in {(datetime.now()-t1).total_seconds():.1f}s')",
    "",
    "# -- Results --",
    "print('[5] Results...')",
    "stats = conn.execute(",
    "    'SELECT COUNT(*), COUNT(oos_accuracy), SUM(overfit),'",
    "    ' ROUND(AVG(oos_accuracy)*100,1), ROUND(AVG(oos_degradation)*100,1)'",
    "    ' FROM seasonality_patterns_v3'",
    ").fetchone()",
    "total, with_oos, overfit_n, avg_oos, avg_deg = stats",
    "print(f'  Total patterns   : {total:,}')",
    "print(f'  With OOS data    : {with_oos:,}')",
    "print(f'  Overfit (>10pp)  : {overfit_n or 0:,}')",
    "print(f'  Avg OOS accuracy : {avg_oos or 0:.1f}%')",
    "print(f'  Avg degradation  : {avg_deg or 0:.1f}pp')",
    "",
    "# -- Sanity check: show a few rows --",
    "sample = conn.execute(",
    "    'SELECT symbol, anchor_mm_dd, window_days, accuracy, oos_accuracy, oos_degradation, overfit'",
    "    ' FROM seasonality_patterns_v3'",
    "    ' WHERE oos_accuracy IS NOT NULL ORDER BY RANDOM() LIMIT 5'",
    ").fetchall()",
    "print()",
    "print('  Sample rows (in_acc | oos_acc | degrade | overfit):')",
    "for r in sample:",
    "    sym, anchor, wd, acc, oos_acc, deg, ovf = r",
    "    acc_disp = f'{float(acc)*100:.1f}%' if acc and float(acc) <= 1.0 else f'{acc}%'",
    "    oos_disp = f'{float(oos_acc)*100:.1f}%' if oos_acc else '--'",
    "    deg_disp = f'{float(deg)*100:.1f}pp' if deg else '--'",
    "    print(f'  {sym:12} {anchor} {wd:3}d  in={acc_disp}  oos={oos_disp}  deg={deg_disp}  ovf={ovf}')",
    "",
    "conn.close()",
    "print(f'Done in {(datetime.now()-t0).total_seconds()/60:.1f} min')",
    "if not TEST_MODE:",
    "    print()",
    "    print('OOS columns populated. Pattern cards will now show OOS badges.')",
    "    print('Recommend: filter overfit=0 for cleaner signals.')",
]

path = MICC / "validate_patterns_oos.py"
path.write_text("\n".join(lines), encoding="utf-8")
print(f"[OK] validate_patterns_oos.py  ({len(lines)} lines)")
print()
print("Run test first:")
print("  py D:\\MICC\\validate_patterns_oos.py --test")
print("  Expected: Avg degradation ~2-8pp (NOT 6809pp)")
print()
print("Then full run:")
print("  py D:\\MICC\\validate_patterns_oos.py")
