"""
migrate_to_env.py
==================
Move hardcoded API keys from micc_data.py to a .env file.

Creates D:/MICC/.env with all sensitive credentials.
Patches micc_data.py to load them via python-dotenv (or os.environ).

KEYS MIGRATED:
  GROQ_API_KEY
  TELEGRAM_BOT_TOKEN
  TELEGRAM_CHAT_ID

SAFE: .env is never committed to git (adds to .gitignore).
      Falls back to hardcoded values if .env missing (backward compat during transition).

RUN:
  python migrate_to_env.py           -- create .env + patch micc_data.py
  python migrate_to_env.py --verify  -- check .env is loaded correctly
"""

import sys
import os
from pathlib import Path

MICC = Path(r"D:\MICC")
ENV_FILE = MICC / ".env"
DATA_FILE = MICC / "micc_data.py"
GITIGNORE = MICC / ".gitignore"


# Current hardcoded values (will be moved to .env)
# These are the defaults — .env will override them
DEFAULTS = {
    "GROQ_API_KEY":         "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",
    "TELEGRAM_BOT_TOKEN":   "8420620581:AAGz9ztaCkj8KUJ5etBOaB0vmH69vHpeMRI",
    "TELEGRAM_CHAT_ID":     "6505636241",
    "GROQ_MODEL":           "llama-3.3-70b-versatile",
    "OLLAMA_MODEL":         "gemma3:4b",
}

ENV_TEMPLATE = """\
# MICC Credentials — DO NOT COMMIT
# Generated by migrate_to_env.py

# Groq LLM API (free tier)
GROQ_API_KEY={GROQ_API_KEY}
GROQ_MODEL={GROQ_MODEL}

# Telegram Bot
TELEGRAM_BOT_TOKEN={TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID={TELEGRAM_CHAT_ID}

# Ollama local LLM
OLLAMA_MODEL={OLLAMA_MODEL}
OLLAMA_URL=http://localhost:11434/api/chat
"""

# New config block for micc_data.py (replaces hardcoded section)
NEW_CONFIG_BLOCK = '''# ── Credentials: loaded from .env, fallback to defaults ──────────────────────
try:
    from dotenv import load_dotenv as _load_dotenv
    _load_dotenv(Path(__file__).parent / ".env", override=False)
except ImportError:
    pass  # python-dotenv not installed; use os.environ or hardcoded fallbacks

GROQ_API_KEY   = os.environ.get("GROQ_API_KEY",       "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")
GROQ_MODEL     = os.environ.get("GROQ_MODEL",          "llama-3.3-70b-versatile")
GROQ_URL       = "https://api.groq.com/openai/v1/chat/completions"
GROQ_TIMEOUT   = 90
GROQ_RATE_DELAY= 6
_groq_last_call= 0.0

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "8420620581:AAGz9ztaCkj8KUJ5etBOaB0vmH69vHpeMRI")
TELEGRAM_CHAT_ID   = os.environ.get("TELEGRAM_CHAT_ID",   "6505636241")

OLLAMA_URL     = os.environ.get("OLLAMA_URL",    "http://localhost:11434/api/chat")
OLLAMA_MODEL   = os.environ.get("OLLAMA_MODEL",  "gemma3:4b")
OLLAMA_TIMEOUT = 180
'''

# Old config section to find and replace in micc_data.py
OLD_CONFIG_MARKER_START = "# LLM config"
OLD_CONFIG_MARKER_END   = "# Groq free tier:"


def create_env_file():
    if ENV_FILE.exists():
        print(f"  [SKIP] .env already exists: {ENV_FILE}")
        print(f"         Delete it and re-run to regenerate.")
        return False
    content = ENV_TEMPLATE.format(**DEFAULTS)
    ENV_FILE.write_text(content, encoding="utf-8")
    print(f"  [OK]   Created: {ENV_FILE}")
    # Set file permissions to owner-only on Windows (best effort)
    try:
        import stat
        ENV_FILE.chmod(stat.S_IRUSR | stat.S_IWUSR)
    except Exception:
        pass
    return True


def update_gitignore():
    entries = [".env", "*.env", "__pycache__/", "*.pyc"]
    if GITIGNORE.exists():
        current = GITIGNORE.read_text(encoding="utf-8")
    else:
        current = ""
    added = []
    for e in entries:
        if e not in current:
            current += f"\n{e}"
            added.append(e)
    GITIGNORE.write_text(current.strip() + "\n", encoding="utf-8")
    if added:
        print(f"  [OK]   .gitignore: added {added}")
    else:
        print(f"  [SKIP] .gitignore already has all entries")


def patch_micc_data():
    if not DATA_FILE.exists():
        print(f"  [SKIP] micc_data.py not found: {DATA_FILE}")
        return False

    text = DATA_FILE.read_text(encoding="utf-8")

    # Find the block between OLD_CONFIG_MARKER_START and OLD_CONFIG_MARKER_END
    start_idx = text.find(OLD_CONFIG_MARKER_START)
    end_idx   = text.find(OLD_CONFIG_MARKER_END)

    if start_idx == -1:
        print(f"  [WARN] Could not find '{OLD_CONFIG_MARKER_START}' in micc_data.py")
        print(f"         Manual patch needed. Add this to the config section:")
        print(NEW_CONFIG_BLOCK)
        return False

    if end_idx == -1:
        print(f"  [WARN] Could not find '{OLD_CONFIG_MARKER_END}' — using start marker only")
        # Find the next double-newline after start
        end_idx = text.find("\n\n", start_idx + len(OLD_CONFIG_MARKER_START))
        if end_idx == -1:
            end_idx = start_idx + 500

    # Find end of the marker line
    end_of_section = text.find("\n\n", end_idx)
    if end_of_section == -1:
        end_of_section = end_idx + 200

    old_block = text[start_idx:end_of_section]

    # Check if already patched
    if "load_dotenv" in text or "dotenv" in text:
        print(f"  [SKIP] micc_data.py already uses dotenv (already patched)")
        return False

    new_text = text[:start_idx] + NEW_CONFIG_BLOCK + text[end_of_section:]
    DATA_FILE.write_text(new_text, encoding="utf-8")
    print(f"  [OK]   Patched micc_data.py config block")
    print(f"         Old block ({len(old_block)} chars) → new block ({len(NEW_CONFIG_BLOCK)} chars)")
    return True


def install_dotenv():
    """Install python-dotenv if not available."""
    try:
        import dotenv
        print(f"  [SKIP] python-dotenv already installed")
        return True
    except ImportError:
        pass
    import subprocess
    py = sys.executable
    result = subprocess.run(
        [py, "-m", "pip", "install", "python-dotenv", "--break-system-packages", "-q"],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print(f"  [OK]   python-dotenv installed")
        return True
    else:
        print(f"  [WARN] python-dotenv install failed: {result.stderr[:200]}")
        print(f"         Run manually: {py} -m pip install python-dotenv --break-system-packages")
        return False


def verify():
    print("\n[VERIFY] Testing .env loading...")
    if not ENV_FILE.exists():
        print(f"  [FAIL] .env not found: {ENV_FILE}")
        return

    try:
        from dotenv import load_dotenv, dotenv_values
        vals = dotenv_values(str(ENV_FILE))
        for k, v in vals.items():
            masked = v[:4] + "***" + v[-4:] if len(v) > 8 else "***"
            print(f"  {k:<25} = {masked}")
        print(f"  [OK]   {len(vals)} keys loaded from .env")
    except ImportError:
        print("  [WARN] python-dotenv not installed — reading raw file")
        for line in ENV_FILE.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                masked = v[:4] + "***" + v[-4:] if len(v) > 8 else "***"
                print(f"  {k.strip():<25} = {masked}")


def main():
    print("=" * 60)
    print("  MICC API Key Migration → .env")
    print("=" * 60)

    verify_only = "--verify" in sys.argv

    if verify_only:
        verify()
        return

    print("\n[STEP 1] Create .env file")
    create_env_file()

    print("\n[STEP 2] Update .gitignore")
    update_gitignore()

    print("\n[STEP 3] Install python-dotenv")
    install_dotenv()

    print("\n[STEP 4] Patch micc_data.py")
    patch_micc_data()

    print("\n[STEP 5] Verify")
    verify()

    print("\n" + "=" * 60)
    print("  DONE")
    print()
    print("  Keys are now in: D:/MICC/.env")
    print("  micc_data.py loads them via python-dotenv on import.")
    print("  Hardcoded fallbacks remain for safety.")
    print()
    print("  NEXT: Rotate the Groq API key and Telegram token")
    print("  (they were briefly exposed in source — new keys go in .env)")
    print("=" * 60)


if __name__ == "__main__":
    main()
