"""
patch_oos_and_scraper.py
=========================
Directly writes the fixed files without any heredoc/indent issues.
Fixes:
  1. validate_patterns_oos.py  -- all_returns dict parsing was broken (always 0)
  2. scrape_fundamentals.py    -- resume logic + db-locked retry

Run: py D:\MICC\patch_oos_and_scraper.py
"""
from pathlib import Path

MICC = Path(r"D:\MICC")

# ---- helper ----
def write(path, lines):
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  [OK] {path.name}  ({len(lines)} lines)")


print("=" * 60)
print("Writing validate_patterns_oos.py (fixed)")
print("=" * 60)

oos_lines = [
    "import sqlite3, json, sys",
    "from datetime import datetime",
    "",
    "DB            = r'D:\\marketDB\\db\\market.db'",
    "OOS_YEAR      = 2019",
    "MIN_OOS       = 5",
    "OVERFIT_THRESH = 0.10",
    "TEST_MODE     = '--test' in sys.argv",
    "",
    "print('OOS Pattern Validation')",
    "print(f'  OOS year cutoff : {OOS_YEAR}')",
    "print(f'  Min OOS obs     : {MIN_OOS}')",
    "print(f'  Overfit thresh  : {int(OVERFIT_THRESH*100)}pp')",
    "print(f'  Mode            : {\"TEST (50k rows)\" if TEST_MODE else \"FULL RUN\"}')",
    "print()",
    "",
    "conn = sqlite3.connect(DB, timeout=120)",
    "conn.execute('PRAGMA journal_mode=WAL')",
    "conn.execute('PRAGMA synchronous=NORMAL')",
    "conn.execute('PRAGMA cache_size=-256000')",
    "",
    "# Step 1: Add columns if missing",
    "print('[1] Adding OOS columns...')",
    "existing = [r[1] for r in conn.execute('PRAGMA table_info(seasonality_patterns_v3)').fetchall()]",
    "for col, td in [",
    "    ('oos_accuracy',    'REAL'),",
    "    ('oos_n_obs',       'INTEGER'),",
    "    ('oos_degradation', 'REAL'),",
    "    ('overfit',         'INTEGER DEFAULT 0'),",
    "]:",
    "    if col not in existing:",
    "        conn.execute(f'ALTER TABLE seasonality_patterns_v3 ADD COLUMN {col} {td}')",
    "        print(f'  Added: {col}')",
    "    else:",
    "        print(f'  OK: {col}')",
    "conn.commit()",
    "",
    "# Step 2: Check all_returns format",
    "print()",
    "print('[2] Checking all_returns format...')",
    "sample = conn.execute(",
    "    'SELECT all_returns FROM seasonality_patterns_v3'",
    "    ' WHERE all_returns IS NOT NULL AND all_returns != \"[]\" LIMIT 1'",
    ").fetchone()",
    "if not sample:",
    "    print('  [ERROR] all_returns is empty. Cannot compute OOS.')",
    "    sys.exit(1)",
    "parsed = json.loads(sample[0])",
    "first  = parsed[0]",
    "print(f'  Raw sample: {str(sample[0])[:120]}')",
    "print(f'  First element type: {type(first).__name__}')",
    "if isinstance(first, dict):",
    "    YEAR_KEY, RET_KEY = 'year', 'ret'",
    "    print('  Format: dict {year, ret}  -- CORRECT')",
    "elif isinstance(first, (list, tuple)):",
    "    YEAR_KEY, RET_KEY = 0, 1",
    "    print('  Format: list [year, ret]')",
    "else:",
    "    print(f'  [ERROR] Unknown format: {first}')",
    "    sys.exit(1)",
    "",
    "# Step 3: Create temp table",
    "print()",
    "print('[3] Computing OOS accuracy...')",
    "conn.execute('DROP TABLE IF EXISTS _oos_temp')",
    "conn.execute(",
    "    'CREATE TEMP TABLE _oos_temp ('",
    "    '  id INTEGER PRIMARY KEY,'",
    "    '  oos_accuracy REAL,'",
    "    '  oos_n_obs INTEGER,'",
    "    '  oos_degradation REAL,'",
    "    '  overfit INTEGER'",
    "    ')'",
    ")",
    "",
    "limit_clause = 'LIMIT 50000' if TEST_MODE else ''",
    "rows = conn.execute(",
    "    'SELECT id, accuracy, all_returns FROM seasonality_patterns_v3'",
    "    ' WHERE all_returns IS NOT NULL AND all_returns != \"[]\"'",
    "    f' {limit_clause}'",
    ").fetchall()",
    "",
    "print(f'  Rows to process: {len(rows):,}')",
    "batch = []",
    "t0 = datetime.now()",
    "ok_count = skip_count = err_count = 0",
    "",
    "for i, (pid, in_acc, raw) in enumerate(rows):",
    "    if i % 200000 == 0 and i > 0:",
    "        elapsed = (datetime.now() - t0).total_seconds()",
    "        rate    = i / elapsed",
    "        eta     = (len(rows) - i) / rate / 60",
    "        pct     = i / len(rows) * 100",
    "        print(f'  {i:,}/{len(rows):,} ({pct:.1f}%)  {rate:.0f}/s  ETA {eta:.1f}m'",
    "              f'  ok={ok_count:,} skip={skip_count:,}', flush=True)",
    "    try:",
    "        returns = json.loads(raw)",
    "    except Exception:",
    "        err_count += 1",
    "        continue",
    "    if not returns:",
    "        skip_count += 1",
    "        continue",
    "    # Parse {year, ret} dicts OR [year, ret] lists",
    "    oos_rets = []",
    "    for r in returns:",
    "        try:",
    "            y   = int(r[YEAR_KEY])",
    "            ret = float(r[RET_KEY])",
    "            if y >= OOS_YEAR:",
    "                oos_rets.append(ret)",
    "        except (KeyError, IndexError, TypeError, ValueError):",
    "            continue",
    "    if len(oos_rets) < MIN_OOS:",
    "        skip_count += 1",
    "        batch.append((None, len(oos_rets), None, 0, pid))",
    "        continue",
    "    oos_acc  = sum(1 for r in oos_rets if r > 0) / len(oos_rets)",
    "    in_acc_f = float(in_acc) if in_acc is not None else 0.5",
    "    degrade  = in_acc_f - oos_acc",
    "    overfit  = 1 if degrade > OVERFIT_THRESH else 0",
    "    ok_count += 1",
    "    batch.append((oos_acc, len(oos_rets), round(degrade, 4), overfit, pid))",
    "    if len(batch) >= 100000:",
    "        conn.executemany(",
    "            'INSERT OR REPLACE INTO _oos_temp(oos_accuracy,oos_n_obs,oos_degradation,overfit,id)'",
    "            ' VALUES(?,?,?,?,?)',",
    "            batch",
    "        )",
    "        conn.commit()",
    "        batch = []",
    "",
    "if batch:",
    "    conn.executemany(",
    "        'INSERT OR REPLACE INTO _oos_temp(oos_accuracy,oos_n_obs,oos_degradation,overfit,id)'",
    "        ' VALUES(?,?,?,?,?)',",
    "        batch",
    "    )",
    "    conn.commit()",
    "",
    "print(f'  Done. ok={ok_count:,}  skip={skip_count:,}  err={err_count:,}')",
    "",
    "# Step 4: Bulk UPDATE",
    "print()",
    "print('[4] Bulk UPDATE from temp table...')",
    "t1 = datetime.now()",
    "conn.execute(",
    "    'UPDATE seasonality_patterns_v3'",
    "    ' SET oos_accuracy    = (SELECT oos_accuracy    FROM _oos_temp t WHERE t.id = seasonality_patterns_v3.id),'",
    "    '     oos_n_obs       = (SELECT oos_n_obs       FROM _oos_temp t WHERE t.id = seasonality_patterns_v3.id),'",
    "    '     oos_degradation = (SELECT oos_degradation FROM _oos_temp t WHERE t.id = seasonality_patterns_v3.id),'",
    "    '     overfit         = (SELECT overfit         FROM _oos_temp t WHERE t.id = seasonality_patterns_v3.id)'",
    "    ' WHERE id IN (SELECT id FROM _oos_temp WHERE oos_accuracy IS NOT NULL)'",
    ")",
    "conn.commit()",
    "print(f'  UPDATE done in {(datetime.now()-t1).total_seconds():.1f}s')",
    "",
    "# Step 5: Results",
    "print()",
    "print('[5] Results...')",
    "stats = conn.execute(",
    "    'SELECT COUNT(*), COUNT(oos_accuracy), SUM(overfit),'",
    "    ' ROUND(AVG(oos_accuracy)*100,1), ROUND(AVG(oos_degradation)*100,1)'",
    "    ' FROM seasonality_patterns_v3'",
    ").fetchone()",
    "total, with_oos, overfit_n, avg_oos, avg_deg = stats",
    "print(f'  Total patterns   : {total:,}')",
    "print(f'  With OOS data    : {with_oos:,}')",
    "print(f'  Overfit (>10pp)  : {overfit_n or 0:,}')",
    "print(f'  Avg OOS accuracy : {avg_oos or 0:.1f}%')",
    "print(f'  Avg degradation  : {avg_deg or 0:.1f}pp')",
    "conn.close()",
    "print(f'Done in {(datetime.now()-t0).total_seconds()/60:.1f} min')",
]

write(MICC / "validate_patterns_oos.py", oos_lines)


print()
print("=" * 60)
print("Writing scrape_fundamentals.py (with resume + db-retry)")
print("=" * 60)

scraper_lines = [
    "import sqlite3, time, sys, json",
    "from pathlib import Path",
    "from datetime import datetime, timedelta",
    "",
    "DB = r'D:\\marketDB\\db\\market.db'",
    "",
    "try:",
    "    import requests",
    "    from bs4 import BeautifulSoup",
    "except ImportError:",
    "    import subprocess",
    "    subprocess.run([sys.executable, '-m', 'pip', 'install',",
    "                    'requests', 'beautifulsoup4', 'lxml',",
    "                    '--break-system-packages', '-q'])",
    "    import requests",
    "    from bs4 import BeautifulSoup",
    "",
    "LIMIT      = int(sys.argv[1]) if len(sys.argv) > 1 and sys.argv[1].isdigit() else 2000",
    "RESUME     = '--resume' in sys.argv",
    "FRESH      = '--fresh'  in sys.argv",
    "DELAY      = 1.5",
    "BATCH      = 30",
    "STALE_DAYS = 7",
    "CKPT       = Path(r'D:\\MICC\\fundamentals_checkpoint.json')",
    "",
    "HEADERS = {",
    "    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0',",
    "    'Accept-Language': 'en-US,en;q=0.9',",
    "}",
    "BASE = 'https://www.screener.in/company'",
    "",
    "print(f'Screener.in fundamentals scraper')",
    "print(f'  Target : {LIMIT}   Resume: {RESUME}   Fresh: {FRESH}')",
    "",
    "# ---- DB write helper with retry on locked ----",
    "def db_write(conn, sql, params_list, retries=8, wait=3.0):",
    "    for attempt in range(retries):",
    "        try:",
    "            conn.executemany(sql, params_list)",
    "            conn.commit()",
    "            return True",
    "        except sqlite3.OperationalError as e:",
    "            if 'locked' in str(e).lower():",
    "                print(f'  [DB LOCKED] attempt {attempt+1}/{retries}, waiting {wait}s...')",
    "                time.sleep(wait)",
    "                wait = min(wait * 1.5, 30.0)",
    "            else:",
    "                raise",
    "    print('  [ERROR] DB still locked after all retries, skipping batch')",
    "    return False",
    "",
    "def db_single(conn, sql, params=(), retries=8, wait=3.0):",
    "    for attempt in range(retries):",
    "        try:",
    "            conn.execute(sql, params)",
    "            conn.commit()",
    "            return True",
    "        except sqlite3.OperationalError as e:",
    "            if 'locked' in str(e).lower():",
    "                print(f'  [DB LOCKED] attempt {attempt+1}/{retries}, waiting {wait}s...')",
    "                time.sleep(wait)",
    "                wait = min(wait * 1.5, 30.0)",
    "            else:",
    "                raise",
    "    return False",
    "",
    "conn = sqlite3.connect(DB, timeout=60)",
    "conn.execute('PRAGMA journal_mode=WAL')",
    "conn.execute('PRAGMA busy_timeout=30000')",
    "",
    "# ---- Create / update table ----",
    "conn.execute(",
    "    'CREATE TABLE IF NOT EXISTS screener_fundamentals_v2 ('",
    "    '  symbol TEXT PRIMARY KEY, pe_ratio REAL, pb_ratio REAL,'",
    "    '  roce REAL, roe REAL, debt_equity REAL, promoter_pct REAL,'",
    "    '  market_cap_cr REAL, sales_cr REAL, profit_cr REAL,'",
    "    '  eps REAL, div_yield REAL, face_value REAL, book_value REAL,'",
    "    '  current_price REAL, high_52w REAL, low_52w REAL,'",
    "    '  current_ratio REAL, revenue_growth REAL, profit_growth REAL,'",
    "    '  interest_coverage REAL, roic REAL, ebitda_growth REAL,'",
    "    '  scraped_date TEXT, scrape_ok INTEGER DEFAULT 1'",
    "    ')'",
    ")",
    "for col, td in [",
    "    ('current_ratio','REAL'), ('revenue_growth','REAL'), ('profit_growth','REAL'),",
    "    ('interest_coverage','REAL'), ('roic','REAL'), ('ebitda_growth','REAL'),",
    "    ('scrape_ok','INTEGER DEFAULT 1'),",
    "]:",
    "    existing = [r[1] for r in conn.execute('PRAGMA table_info(screener_fundamentals_v2)').fetchall()]",
    "    if col not in existing:",
    "        conn.execute(f'ALTER TABLE screener_fundamentals_v2 ADD COLUMN {col} {td}')",
    "conn.commit()",
    "",
    "# ---- Build symbol list ----",
    "all_rows = conn.execute(",
    "    'SELECT s.symbol FROM (SELECT symbol FROM symbol_conviction'",
    "    ' ORDER BY CAST(conviction_score AS REAL) DESC LIMIT ?) s',",
    "    (LIMIT,)",
    ").fetchall()",
    "if not all_rows:",
    "    all_rows = conn.execute('SELECT DISTINCT symbol FROM stock_data ORDER BY symbol LIMIT ?', (LIMIT,)).fetchall()",
    "all_symbols = [r[0] for r in all_rows]",
    "",
    "# ---- Build skip set ----",
    "cutoff = (datetime.now() - timedelta(days=STALE_DAYS)).strftime('%Y-%m-%d')",
    "done_set = set()",
    "if RESUME and not FRESH:",
    "    done_rows = conn.execute(",
    "        'SELECT symbol FROM screener_fundamentals_v2 WHERE scraped_date >= ? AND scrape_ok = 1',",
    "        (cutoff,)",
    "    ).fetchall()",
    "    done_set = {r[0] for r in done_rows}",
    "",
    "# ---- Checkpoint skip ----",
    "ckpt_done = set()",
    "if CKPT.exists() and not FRESH:",
    "    try:",
    "        ckpt_done = set(json.loads(CKPT.read_text())['done'])",
    "    except Exception:",
    "        pass",
    "",
    "symbols = [s for s in all_symbols if s not in done_set and s not in ckpt_done]",
    "print(f'  Total: {len(all_symbols)}  Done in DB: {len(done_set)}  Ckpt done: {len(ckpt_done)}  To scrape: {len(symbols)}')",
    "print()",
    "",
    "if not symbols:",
    "    print('All symbols already scraped. Use --fresh to force rescrape.')",
    "    conn.close()",
    "    sys.exit(0)",
    "",
    "# ---- Helpers ----",
    "def clean_num(text):",
    "    if not text: return None",
    "    t = str(text).replace(',','').replace('%','').replace('Cr.','').strip()",
    "    t = t.split()[0] if t.split() else t",
    "    try: return float(t)",
    "    except: return None",
    "",
    "def scrape(symbol):",
    "    url = f'{BASE}/{symbol}/consolidated/'",
    "    try:",
    "        r = requests.get(url, headers=HEADERS, timeout=14)",
    "        if r.status_code == 404:",
    "            r = requests.get(f'{BASE}/{symbol}/', headers=HEADERS, timeout=14)",
    "        if r.status_code != 200:",
    "            return None",
    "    except Exception as e:",
    "        print(f'    [{symbol}] err: {e}')",
    "        return None",
    "    soup = BeautifulSoup(r.text, 'lxml')",
    "    def rv(label):",
    "        for li in soup.select('ul.company-ratios li, #top-ratios li'):",
    "            n = li.select_one('.name, span:first-child')",
    "            v = li.select_one('.number, .value, span:last-child')",
    "            if n and v and label.lower() in n.get_text(strip=True).lower():",
    "                return clean_num(v.get_text(strip=True))",
    "        return None",
    "    d = {",
    "        'symbol': symbol,",
    "        'pe_ratio':      rv('P/E'),",
    "        'pb_ratio':      rv('P/B'),",
    "        'roce':          rv('ROCE'),",
    "        'roe':           rv('ROE'),",
    "        'debt_equity':   rv('Debt / Equity') or rv('Debt/Equity'),",
    "        'promoter_pct':  None,",
    "        'market_cap_cr': rv('Market Cap'),",
    "        'eps':           rv('EPS'),",
    "        'div_yield':     rv('Div Yield') or rv('Dividend Yield'),",
    "        'face_value':    rv('Face Value'),",
    "        'book_value':    rv('Book Value'),",
    "        'current_price': rv('Current Price') or rv('CMP'),",
    "        'high_52w':      rv('52 Week High'),",
    "        'low_52w':       rv('52 Week Low'),",
    "        'current_ratio': rv('Current Ratio'),",
    "        'interest_coverage': rv('Interest Coverage'),",
    "        'sales_cr':      None, 'profit_cr': None,",
    "        'revenue_growth': None, 'profit_growth': None,",
    "        'roic': None, 'ebitda_growth': None,",
    "        'scraped_date':  datetime.now().strftime('%Y-%m-%d'),",
    "    }",
    "    for tbl in soup.select('table'):",
    "        hdrs = [th.get_text(strip=True).lower() for th in tbl.select('th')]",
    "        if any('promoter' in h for h in hdrs):",
    "            for row in tbl.select('tr'):",
    "                cells = row.select('td')",
    "                if cells and 'promoter' in cells[0].get_text(strip=True).lower():",
    "                    d['promoter_pct'] = clean_num(cells[-1].get_text(strip=True))",
    "                    break",
    "    for section in soup.select('section, div.card'):",
    "        h2 = section.select_one('h2, h3')",
    "        if h2 and 'profit' in h2.get_text(strip=True).lower():",
    "            for tr in section.select('tr'):",
    "                cells = tr.select('td')",
    "                if not cells: continue",
    "                lbl = cells[0].get_text(strip=True).lower()",
    "                if 'sales' in lbl or 'revenue' in lbl:",
    "                    d['sales_cr'] = clean_num(cells[-1].get_text(strip=True))",
    "                if 'net profit' in lbl or 'profit after' in lbl:",
    "                    d['profit_cr'] = clean_num(cells[-1].get_text(strip=True))",
    "    return d",
    "",
    "SQL = (",
    "    'INSERT OR REPLACE INTO screener_fundamentals_v2'",
    "    ' (symbol,pe_ratio,pb_ratio,roce,roe,debt_equity,promoter_pct,'",
    "    '  market_cap_cr,sales_cr,profit_cr,eps,div_yield,face_value,'",
    "    '  book_value,current_price,high_52w,low_52w,current_ratio,'",
    "    '  revenue_growth,profit_growth,interest_coverage,roic,ebitda_growth,'",
    "    '  scraped_date,scrape_ok)'",
    "    ' VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'",
    ")",
    "",
    "ok = 0; err = 0; batch_data = []",
    "done_this_run = []",
    "t0 = datetime.now()",
    "total = len(all_symbols)",
    "",
    "for i, sym in enumerate(symbols):",
    "    elapsed = (datetime.now() - t0).total_seconds()",
    "    eta = ((len(symbols) - i) / max(i, 1)) * elapsed / 60 if i > 0 else 0",
    "    done_total = len(done_set) + len(ckpt_done) + i + 1",
    "",
    "    data = scrape(sym)",
    "    if data:",
    "        g = data.get",
    "        batch_data.append((",
    "            sym, g('pe_ratio'), g('pb_ratio'), g('roce'), g('roe'),",
    "            g('debt_equity'), g('promoter_pct'), g('market_cap_cr'),",
    "            g('sales_cr'), g('profit_cr'), g('eps'), g('div_yield'),",
    "            g('face_value'), g('book_value'), g('current_price'),",
    "            g('high_52w'), g('low_52w'), g('current_ratio'),",
    "            g('revenue_growth'), g('profit_growth'), g('interest_coverage'),",
    "            g('roic'), g('ebitda_growth'), g('scraped_date'), 1,",
    "        ))",
    "        ok += 1",
    "        pe   = f\"PE={data['pe_ratio']:.1f}\"     if data.get('pe_ratio')   else 'PE=--   '",
    "        roe  = f\"ROE={data['roe']:.1f}\"         if data.get('roe')        else 'ROE=--  '",
    "        roce = f\"ROCE={data['roce']:.1f}\"       if data.get('roce')       else 'ROCE=-- '",
    "        pro  = f\"Pro={data['promoter_pct']:.1f}\" if data.get('promoter_pct') else 'Pro=--  '",
    "        print(f'  [{done_total:4}/{total}] {sym:15} {pe}  {roe}  {roce}  {pro}  ETA {eta:.0f}m')",
    "    else:",
    "        db_single(conn, 'INSERT OR REPLACE INTO screener_fundamentals_v2 (symbol,scraped_date,scrape_ok) VALUES(?,?,0)', (sym, datetime.now().strftime('%Y-%m-%d')))",
    "        err += 1",
    "        print(f'  [{done_total:4}/{total}] {sym:15} FAILED  ETA {eta:.0f}m')",
    "",
    "    done_this_run.append(sym)",
    "",
    "    if len(batch_data) >= BATCH:",
    "        db_write(conn, SQL, batch_data)",
    "        batch_data = []",
    "",
    "    if (i + 1) % 50 == 0:",
    "        # Save checkpoint",
    "        all_done = list(ckpt_done) + done_this_run",
    "        CKPT.write_text(json.dumps({'done': all_done, 'ts': datetime.now().isoformat()}))",
    "",
    "    time.sleep(DELAY)",
    "",
    "if batch_data:",
    "    db_write(conn, SQL, batch_data)",
    "",
    "# Final checkpoint save",
    "all_done = list(ckpt_done) + done_this_run",
    "CKPT.write_text(json.dumps({'done': all_done, 'ts': datetime.now().isoformat()}))",
    "",
    "total_db = conn.execute('SELECT COUNT(*) FROM screener_fundamentals_v2 WHERE scrape_ok=1').fetchone()[0]",
    "print(f'Done. OK={ok} Failed={err} Total in DB={total_db}')",
    "print(f'Run time: {(datetime.now()-t0).total_seconds()/60:.1f} min')",
    "print()",
    "print('To resume: py D:\\\\MICC\\\\scrape_fundamentals.py 2000 --resume')",
    "conn.close()",
]

write(MICC / "scrape_fundamentals.py", scraper_lines)


print()
print("=" * 60)
print("DONE. Both files written.")
print("=" * 60)
print()
print("OOS is already running in your other terminal.")
print("Let it finish (it will work now -- the new file is what matters).")
print()
print("WAIT for OOS to finish, THEN start scraper:")
print("  py D:\\MICC\\scrape_fundamentals.py 2000 --resume")
print()
print("Why wait: SQLite WAL allows concurrent reads but only ONE writer.")
print("OOS holds a write lock for the bulk UPDATE step (~10 min).")
print("Running scraper at same time = 'database is locked' error.")
print()
print("To verify OOS fix works first (30 sec test):")
print("  py D:\\MICC\\validate_patterns_oos.py --test")
print("  Should show 'With OOS data: 1000+' this time")
